# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_modelarmor as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = []

HELPER_CASES = [
    {
        "command": "+create-template",
        "fn": "create_template",
        "required": {"location": "x", "project": "x", "template_id": "x"},
        "service": "modelarmor",
    },
    {
        "command": "+sanitize-prompt",
        "fn": "sanitize_prompt",
        "required": {"template": "x"},
        "service": "modelarmor",
    },
    {
        "command": "+sanitize-response",
        "fn": "sanitize_response",
        "required": {"template": "x"},
        "service": "modelarmor",
    },
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_modelarmor"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
