# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_meet as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "conference_records_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_list",
        "method": "list",
        "orig_required": {},
        "path": ["conferenceRecords"],
        "required": {},
        "service": "meet",
    },
    {
        "fn": "conference_records_participants_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "participants"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_participants_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "participants"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_participants_participant_sessions_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "participants", "participantSessions"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_participants_participant_sessions_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "participants", "participantSessions"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_recordings_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "recordings"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_recordings_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "recordings"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_smart_notes_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "smartNotes"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_smart_notes_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "smartNotes"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_transcripts_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "transcripts"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_transcripts_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "transcripts"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_transcripts_entries_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["conferenceRecords", "transcripts", "entries"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "conference_records_transcripts_entries_list",
        "method": "list",
        "orig_required": {"parent": "x"},
        "path": ["conferenceRecords", "transcripts", "entries"],
        "required": {"parent": "x"},
        "service": "meet",
    },
    {
        "fn": "spaces_create",
        "method": "create",
        "orig_required": {},
        "path": ["spaces"],
        "required": {},
        "service": "meet",
    },
    {
        "fn": "spaces_end_active_conference",
        "method": "endActiveConference",
        "orig_required": {"name": "x"},
        "path": ["spaces"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "spaces_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["spaces"],
        "required": {"name": "x"},
        "service": "meet",
    },
    {
        "fn": "spaces_patch",
        "method": "patch",
        "orig_required": {"name": "x"},
        "path": ["spaces"],
        "required": {"name": "x"},
        "service": "meet",
    },
]

HELPER_CASES = []


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_meet"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True
