# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_drive as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "about_get",
        "method": "get",
        "orig_required": {},
        "path": ["about"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "accessproposals_get",
        "method": "get",
        "orig_required": {"fileId": "x", "proposalId": "x"},
        "path": ["accessproposals"],
        "required": {"fileId": "x", "proposalId": "x"},
        "service": "drive",
    },
    {
        "fn": "accessproposals_list",
        "method": "list",
        "orig_required": {"fileId": "x"},
        "path": ["accessproposals"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "accessproposals_resolve",
        "method": "resolve",
        "orig_required": {"fileId": "x", "proposalId": "x"},
        "path": ["accessproposals"],
        "required": {"fileId": "x", "proposalId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_approve",
        "method": "approve",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_cancel",
        "method": "cancel",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_comment",
        "method": "comment",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_decline",
        "method": "decline",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_get",
        "method": "get",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_list",
        "method": "list",
        "orig_required": {"fileId": "x"},
        "path": ["approvals"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_reassign",
        "method": "reassign",
        "orig_required": {"approvalId": "x", "fileId": "x"},
        "path": ["approvals"],
        "required": {"approvalId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "approvals_start",
        "method": "start",
        "orig_required": {"fileId": "x"},
        "path": ["approvals"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "apps_get",
        "method": "get",
        "orig_required": {"appId": "x"},
        "path": ["apps"],
        "required": {"appId": "x"},
        "service": "drive",
    },
    {
        "fn": "apps_list",
        "method": "list",
        "orig_required": {},
        "path": ["apps"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "changes_get_start_page_token",
        "method": "getStartPageToken",
        "orig_required": {},
        "path": ["changes"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "changes_list",
        "method": "list",
        "orig_required": {"pageToken": "x"},
        "path": ["changes"],
        "required": {"pageToken": "x"},
        "service": "drive",
    },
    {
        "fn": "changes_watch",
        "method": "watch",
        "orig_required": {"pageToken": "x"},
        "path": ["changes"],
        "required": {"pageToken": "x"},
        "service": "drive",
    },
    {
        "fn": "channels_stop",
        "method": "stop",
        "orig_required": {},
        "path": ["channels"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "comments_create",
        "method": "create",
        "orig_required": {"fileId": "x"},
        "path": ["comments"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "comments_delete",
        "method": "delete",
        "orig_required": {"commentId": "x", "fileId": "x"},
        "path": ["comments"],
        "required": {"commentId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "comments_get",
        "method": "get",
        "orig_required": {"commentId": "x", "fileId": "x"},
        "path": ["comments"],
        "required": {"commentId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "comments_list",
        "method": "list",
        "orig_required": {"fileId": "x"},
        "path": ["comments"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "comments_update",
        "method": "update",
        "orig_required": {"commentId": "x", "fileId": "x"},
        "path": ["comments"],
        "required": {"commentId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_create",
        "method": "create",
        "orig_required": {"requestId": "x"},
        "path": ["drives"],
        "required": {"requestId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_delete",
        "method": "delete",
        "orig_required": {"driveId": "x"},
        "path": ["drives"],
        "required": {"driveId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_get",
        "method": "get",
        "orig_required": {"driveId": "x"},
        "path": ["drives"],
        "required": {"driveId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_hide",
        "method": "hide",
        "orig_required": {"driveId": "x"},
        "path": ["drives"],
        "required": {"driveId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_list",
        "method": "list",
        "orig_required": {},
        "path": ["drives"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "drives_unhide",
        "method": "unhide",
        "orig_required": {"driveId": "x"},
        "path": ["drives"],
        "required": {"driveId": "x"},
        "service": "drive",
    },
    {
        "fn": "drives_update",
        "method": "update",
        "orig_required": {"driveId": "x"},
        "path": ["drives"],
        "required": {"driveId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_copy",
        "method": "copy",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_create",
        "method": "create",
        "orig_required": {},
        "path": ["files"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "files_delete",
        "method": "delete",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_download",
        "method": "download",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_empty_trash",
        "method": "emptyTrash",
        "orig_required": {},
        "path": ["files"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "files_export",
        "method": "export",
        "orig_required": {"fileId": "x", "mimeType": "x"},
        "path": ["files"],
        "required": {"fileId": "x", "mimeType": "x"},
        "service": "drive",
    },
    {
        "fn": "files_generate_cse_token",
        "method": "generateCseToken",
        "orig_required": {},
        "path": ["files"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "files_generate_ids",
        "method": "generateIds",
        "orig_required": {},
        "path": ["files"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "files_get",
        "method": "get",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_list",
        "method": "list",
        "orig_required": {},
        "path": ["files"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "files_list_labels",
        "method": "listLabels",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_modify_labels",
        "method": "modifyLabels",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_update",
        "method": "update",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "files_watch",
        "method": "watch",
        "orig_required": {"fileId": "x"},
        "path": ["files"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "operations_get",
        "method": "get",
        "orig_required": {"name": "x"},
        "path": ["operations"],
        "required": {"name": "x"},
        "service": "drive",
    },
    {
        "fn": "permissions_create",
        "method": "create",
        "orig_required": {"fileId": "x"},
        "path": ["permissions"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "permissions_delete",
        "method": "delete",
        "orig_required": {"fileId": "x", "permissionId": "x"},
        "path": ["permissions"],
        "required": {"fileId": "x", "permissionId": "x"},
        "service": "drive",
    },
    {
        "fn": "permissions_get",
        "method": "get",
        "orig_required": {"fileId": "x", "permissionId": "x"},
        "path": ["permissions"],
        "required": {"fileId": "x", "permissionId": "x"},
        "service": "drive",
    },
    {
        "fn": "permissions_list",
        "method": "list",
        "orig_required": {"fileId": "x"},
        "path": ["permissions"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "permissions_update",
        "method": "update",
        "orig_required": {"fileId": "x", "permissionId": "x"},
        "path": ["permissions"],
        "required": {"fileId": "x", "permissionId": "x"},
        "service": "drive",
    },
    {
        "fn": "replies_create",
        "method": "create",
        "orig_required": {"commentId": "x", "fileId": "x"},
        "path": ["replies"],
        "required": {"commentId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "replies_delete",
        "method": "delete",
        "orig_required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "path": ["replies"],
        "required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "service": "drive",
    },
    {
        "fn": "replies_get",
        "method": "get",
        "orig_required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "path": ["replies"],
        "required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "service": "drive",
    },
    {
        "fn": "replies_list",
        "method": "list",
        "orig_required": {"commentId": "x", "fileId": "x"},
        "path": ["replies"],
        "required": {"commentId": "x", "fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "replies_update",
        "method": "update",
        "orig_required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "path": ["replies"],
        "required": {"commentId": "x", "fileId": "x", "replyId": "x"},
        "service": "drive",
    },
    {
        "fn": "revisions_delete",
        "method": "delete",
        "orig_required": {"fileId": "x", "revisionId": "x"},
        "path": ["revisions"],
        "required": {"fileId": "x", "revisionId": "x"},
        "service": "drive",
    },
    {
        "fn": "revisions_get",
        "method": "get",
        "orig_required": {"fileId": "x", "revisionId": "x"},
        "path": ["revisions"],
        "required": {"fileId": "x", "revisionId": "x"},
        "service": "drive",
    },
    {
        "fn": "revisions_list",
        "method": "list",
        "orig_required": {"fileId": "x"},
        "path": ["revisions"],
        "required": {"fileId": "x"},
        "service": "drive",
    },
    {
        "fn": "revisions_update",
        "method": "update",
        "orig_required": {"fileId": "x", "revisionId": "x"},
        "path": ["revisions"],
        "required": {"fileId": "x", "revisionId": "x"},
        "service": "drive",
    },
    {
        "fn": "teamdrives_create",
        "method": "create",
        "orig_required": {"requestId": "x"},
        "path": ["teamdrives"],
        "required": {"requestId": "x"},
        "service": "drive",
    },
    {
        "fn": "teamdrives_delete",
        "method": "delete",
        "orig_required": {"teamDriveId": "x"},
        "path": ["teamdrives"],
        "required": {"teamDriveId": "x"},
        "service": "drive",
    },
    {
        "fn": "teamdrives_get",
        "method": "get",
        "orig_required": {"teamDriveId": "x"},
        "path": ["teamdrives"],
        "required": {"teamDriveId": "x"},
        "service": "drive",
    },
    {
        "fn": "teamdrives_list",
        "method": "list",
        "orig_required": {},
        "path": ["teamdrives"],
        "required": {},
        "service": "drive",
    },
    {
        "fn": "teamdrives_update",
        "method": "update",
        "orig_required": {"teamDriveId": "x"},
        "path": ["teamdrives"],
        "required": {"teamDriveId": "x"},
        "service": "drive",
    },
]

HELPER_CASES = [
    {"command": "+upload", "fn": "upload", "required": {"file": "x"}, "service": "drive"}
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_drive"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
