# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_gmail as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "users_get_profile",
        "method": "getProfile",
        "orig_required": {"userId": "x"},
        "path": ["users"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_stop",
        "method": "stop",
        "orig_required": {"userId": "x"},
        "path": ["users"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_watch",
        "method": "watch",
        "orig_required": {"userId": "x"},
        "path": ["users"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "drafts"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_delete",
        "method": "delete",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "drafts"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_get",
        "method": "get",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "drafts"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "drafts"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_send",
        "method": "send",
        "orig_required": {"userId": "x"},
        "path": ["users", "drafts"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_drafts_update",
        "method": "update",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "drafts"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_history_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "history"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "labels"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_delete",
        "method": "delete",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "labels"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_get",
        "method": "get",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "labels"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "labels"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_patch",
        "method": "patch",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "labels"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_labels_update",
        "method": "update",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "labels"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_batch_delete",
        "method": "batchDelete",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_batch_modify",
        "method": "batchModify",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_delete",
        "method": "delete",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "messages"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_get",
        "method": "get",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "messages"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_import",
        "method": "import",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_insert",
        "method": "insert",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_modify",
        "method": "modify",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "messages"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_send",
        "method": "send",
        "orig_required": {"userId": "x"},
        "path": ["users", "messages"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_trash",
        "method": "trash",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "messages"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_untrash",
        "method": "untrash",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "messages"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_messages_attachments_get",
        "method": "get",
        "orig_required": {"id": "x", "messageId": "x", "userId": "x"},
        "path": ["users", "messages", "attachments"],
        "required": {"id": "x", "messageId": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_get_auto_forwarding",
        "method": "getAutoForwarding",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_get_imap",
        "method": "getImap",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_get_language",
        "method": "getLanguage",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_get_pop",
        "method": "getPop",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_get_vacation",
        "method": "getVacation",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_update_auto_forwarding",
        "method": "updateAutoForwarding",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_update_imap",
        "method": "updateImap",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_update_language",
        "method": "updateLanguage",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_update_pop",
        "method": "updatePop",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_update_vacation",
        "method": "updateVacation",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_identities_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "cse", "identities"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_identities_delete",
        "method": "delete",
        "orig_required": {"cseEmailAddress": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "identities"],
        "required": {"cseEmailAddress": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_identities_get",
        "method": "get",
        "orig_required": {"cseEmailAddress": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "identities"],
        "required": {"cseEmailAddress": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_identities_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "cse", "identities"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_identities_patch",
        "method": "patch",
        "orig_required": {"emailAddress": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "identities"],
        "required": {"emailAddress": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_disable",
        "method": "disable",
        "orig_required": {"keyPairId": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"keyPairId": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_enable",
        "method": "enable",
        "orig_required": {"keyPairId": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"keyPairId": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_get",
        "method": "get",
        "orig_required": {"keyPairId": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"keyPairId": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_cse_keypairs_obliterate",
        "method": "obliterate",
        "orig_required": {"keyPairId": "x", "userId": "x"},
        "path": ["users", "settings", "cse", "keypairs"],
        "required": {"keyPairId": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_delegates_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "delegates"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_delegates_delete",
        "method": "delete",
        "orig_required": {"delegateEmail": "x", "userId": "x"},
        "path": ["users", "settings", "delegates"],
        "required": {"delegateEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_delegates_get",
        "method": "get",
        "orig_required": {"delegateEmail": "x", "userId": "x"},
        "path": ["users", "settings", "delegates"],
        "required": {"delegateEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_delegates_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "delegates"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_filters_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "filters"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_filters_delete",
        "method": "delete",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "settings", "filters"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_filters_get",
        "method": "get",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "settings", "filters"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_filters_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "filters"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_forwarding_addresses_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "forwardingAddresses"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_forwarding_addresses_delete",
        "method": "delete",
        "orig_required": {"forwardingEmail": "x", "userId": "x"},
        "path": ["users", "settings", "forwardingAddresses"],
        "required": {"forwardingEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_forwarding_addresses_get",
        "method": "get",
        "orig_required": {"forwardingEmail": "x", "userId": "x"},
        "path": ["users", "settings", "forwardingAddresses"],
        "required": {"forwardingEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_forwarding_addresses_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "forwardingAddresses"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_create",
        "method": "create",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_delete",
        "method": "delete",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_get",
        "method": "get",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_patch",
        "method": "patch",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_update",
        "method": "update",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_verify",
        "method": "verify",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_smime_info_delete",
        "method": "delete",
        "orig_required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs", "smimeInfo"],
        "required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_smime_info_get",
        "method": "get",
        "orig_required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs", "smimeInfo"],
        "required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_smime_info_insert",
        "method": "insert",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs", "smimeInfo"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_smime_info_list",
        "method": "list",
        "orig_required": {"sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs", "smimeInfo"],
        "required": {"sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_settings_send_as_smime_info_set_default",
        "method": "setDefault",
        "orig_required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "path": ["users", "settings", "sendAs", "smimeInfo"],
        "required": {"id": "x", "sendAsEmail": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_delete",
        "method": "delete",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "threads"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_get",
        "method": "get",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "threads"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_list",
        "method": "list",
        "orig_required": {"userId": "x"},
        "path": ["users", "threads"],
        "required": {"userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_modify",
        "method": "modify",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "threads"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_trash",
        "method": "trash",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "threads"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
    {
        "fn": "users_threads_untrash",
        "method": "untrash",
        "orig_required": {"id": "x", "userId": "x"},
        "path": ["users", "threads"],
        "required": {"id": "x", "userId": "x"},
        "service": "gmail",
    },
]

HELPER_CASES = [
    {
        "command": "+forward",
        "fn": "forward",
        "required": {"message_id": "x", "to": "x"},
        "service": "gmail",
    },
    {"command": "+read", "fn": "read", "required": {"id": "x"}, "service": "gmail"},
    {
        "command": "+reply",
        "fn": "reply",
        "required": {"body_": "x", "message_id": "x"},
        "service": "gmail",
    },
    {
        "command": "+reply-all",
        "fn": "reply_all",
        "required": {"body_": "x", "message_id": "x"},
        "service": "gmail",
    },
    {
        "command": "+send",
        "fn": "send",
        "required": {"body_": "x", "subject": "x", "to": "x"},
        "service": "gmail",
    },
    {"command": "+triage", "fn": "triage", "required": {}, "service": "gmail"},
    {"command": "+watch", "fn": "watch", "required": {}, "service": "gmail"},
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_gmail"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
