# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_workflow as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = []

HELPER_CASES = [
    {
        "command": "+email-to-task",
        "fn": "email_to_task",
        "required": {"message_id": "x"},
        "service": "workflow",
    },
    {
        "command": "+file-announce",
        "fn": "file_announce",
        "required": {"file_id": "x", "space": "x"},
        "service": "workflow",
    },
    {"command": "+meeting-prep", "fn": "meeting_prep", "required": {}, "service": "workflow"},
    {"command": "+standup-report", "fn": "standup_report", "required": {}, "service": "workflow"},
    {"command": "+weekly-digest", "fn": "weekly_digest", "required": {}, "service": "workflow"},
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_workflow"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
