# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_people as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "contact_groups_batch_get",
        "method": "batchGet",
        "orig_required": {},
        "path": ["contactGroups"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "contact_groups_create",
        "method": "create",
        "orig_required": {},
        "path": ["contactGroups"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "contact_groups_delete",
        "method": "delete",
        "orig_required": {"resourceName": "x"},
        "path": ["contactGroups"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "contact_groups_get",
        "method": "get",
        "orig_required": {"resourceName": "x"},
        "path": ["contactGroups"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "contact_groups_list",
        "method": "list",
        "orig_required": {},
        "path": ["contactGroups"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "contact_groups_update",
        "method": "update",
        "orig_required": {"resourceName": "x"},
        "path": ["contactGroups"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "contact_groups_members_modify",
        "method": "modify",
        "orig_required": {"resourceName": "x"},
        "path": ["contactGroups", "members"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "other_contacts_copy_other_contact_to_my_contacts_group",
        "method": "copyOtherContactToMyContactsGroup",
        "orig_required": {"resourceName": "x"},
        "path": ["otherContacts"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "other_contacts_list",
        "method": "list",
        "orig_required": {},
        "path": ["otherContacts"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "other_contacts_search",
        "method": "search",
        "orig_required": {},
        "path": ["otherContacts"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_batch_create_contacts",
        "method": "batchCreateContacts",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_batch_delete_contacts",
        "method": "batchDeleteContacts",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_batch_update_contacts",
        "method": "batchUpdateContacts",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_create_contact",
        "method": "createContact",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_delete_contact",
        "method": "deleteContact",
        "orig_required": {"resourceName": "x"},
        "path": ["people"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "people_delete_contact_photo",
        "method": "deleteContactPhoto",
        "orig_required": {"resourceName": "x"},
        "path": ["people"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "people_get",
        "method": "get",
        "orig_required": {"resourceName": "x"},
        "path": ["people"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "people_get_batch_get",
        "method": "getBatchGet",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_list_directory_people",
        "method": "listDirectoryPeople",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_search_contacts",
        "method": "searchContacts",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_search_directory_people",
        "method": "searchDirectoryPeople",
        "orig_required": {},
        "path": ["people"],
        "required": {},
        "service": "people",
    },
    {
        "fn": "people_update_contact",
        "method": "updateContact",
        "orig_required": {"resourceName": "x"},
        "path": ["people"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "people_update_contact_photo",
        "method": "updateContactPhoto",
        "orig_required": {"resourceName": "x"},
        "path": ["people"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
    {
        "fn": "people_connections_list",
        "method": "list",
        "orig_required": {"resourceName": "x"},
        "path": ["people", "connections"],
        "required": {"resourceName": "x"},
        "service": "people",
    },
]

HELPER_CASES = []


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_people"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True
