# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_slides as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "presentations_batch_update",
        "method": "batchUpdate",
        "orig_required": {"presentationId": "x"},
        "path": ["presentations"],
        "required": {"presentationId": "x"},
        "service": "slides",
    },
    {
        "fn": "presentations_create",
        "method": "create",
        "orig_required": {},
        "path": ["presentations"],
        "required": {},
        "service": "slides",
    },
    {
        "fn": "presentations_get",
        "method": "get",
        "orig_required": {"presentationId": "x"},
        "path": ["presentations"],
        "required": {"presentationId": "x"},
        "service": "slides",
    },
    {
        "fn": "presentations_pages_get",
        "method": "get",
        "orig_required": {"pageObjectId": "x", "presentationId": "x"},
        "path": ["presentations", "pages"],
        "required": {"pageObjectId": "x", "presentationId": "x"},
        "service": "slides",
    },
    {
        "fn": "presentations_pages_get_thumbnail",
        "method": "getThumbnail",
        "orig_required": {"pageObjectId": "x", "presentationId": "x"},
        "path": ["presentations", "pages"],
        "required": {"pageObjectId": "x", "presentationId": "x"},
        "service": "slides",
    },
]

HELPER_CASES = []


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_slides"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True
