# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_script as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "processes_list",
        "method": "list",
        "orig_required": {},
        "path": ["processes"],
        "required": {},
        "service": "script",
    },
    {
        "fn": "processes_list_script_processes",
        "method": "listScriptProcesses",
        "orig_required": {},
        "path": ["processes"],
        "required": {},
        "service": "script",
    },
    {
        "fn": "projects_create",
        "method": "create",
        "orig_required": {},
        "path": ["projects"],
        "required": {},
        "service": "script",
    },
    {
        "fn": "projects_get",
        "method": "get",
        "orig_required": {"scriptId": "x"},
        "path": ["projects"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_get_content",
        "method": "getContent",
        "orig_required": {"scriptId": "x"},
        "path": ["projects"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_get_metrics",
        "method": "getMetrics",
        "orig_required": {"scriptId": "x"},
        "path": ["projects"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_update_content",
        "method": "updateContent",
        "orig_required": {"scriptId": "x"},
        "path": ["projects"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_deployments_create",
        "method": "create",
        "orig_required": {"scriptId": "x"},
        "path": ["projects", "deployments"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_deployments_delete",
        "method": "delete",
        "orig_required": {"deploymentId": "x", "scriptId": "x"},
        "path": ["projects", "deployments"],
        "required": {"deploymentId": "x", "scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_deployments_get",
        "method": "get",
        "orig_required": {"deploymentId": "x", "scriptId": "x"},
        "path": ["projects", "deployments"],
        "required": {"deploymentId": "x", "scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_deployments_list",
        "method": "list",
        "orig_required": {"scriptId": "x"},
        "path": ["projects", "deployments"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_deployments_update",
        "method": "update",
        "orig_required": {"deploymentId": "x", "scriptId": "x"},
        "path": ["projects", "deployments"],
        "required": {"deploymentId": "x", "scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_versions_create",
        "method": "create",
        "orig_required": {"scriptId": "x"},
        "path": ["projects", "versions"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "projects_versions_get",
        "method": "get",
        "orig_required": {"scriptId": "x", "versionNumber": 1},
        "path": ["projects", "versions"],
        "required": {"scriptId": "x", "versionNumber": 1},
        "service": "script",
    },
    {
        "fn": "projects_versions_list",
        "method": "list",
        "orig_required": {"scriptId": "x"},
        "path": ["projects", "versions"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
    {
        "fn": "scripts_run",
        "method": "run",
        "orig_required": {"scriptId": "x"},
        "path": ["scripts"],
        "required": {"scriptId": "x"},
        "service": "script",
    },
]

HELPER_CASES = [
    {"command": "+push", "fn": "push", "required": {"script": "x"}, "service": "script"}
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_script"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
