# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import patch

import pytest

import saltext.gsuite.modules.gsuite_calendar as mod


@pytest.fixture
def configure_loader_modules():
    return {mod: {"__opts__": {"test": False}, "__pillar__": {}}}


METHOD_CASES = [
    {
        "fn": "acl_delete",
        "method": "delete",
        "orig_required": {"calendarId": "x", "ruleId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x", "ruleId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_get",
        "method": "get",
        "orig_required": {"calendarId": "x", "ruleId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x", "ruleId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_insert",
        "method": "insert",
        "orig_required": {"calendarId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_list",
        "method": "list",
        "orig_required": {"calendarId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_patch",
        "method": "patch",
        "orig_required": {"calendarId": "x", "ruleId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x", "ruleId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_update",
        "method": "update",
        "orig_required": {"calendarId": "x", "ruleId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x", "ruleId": "x"},
        "service": "calendar",
    },
    {
        "fn": "acl_watch",
        "method": "watch",
        "orig_required": {"calendarId": "x"},
        "path": ["acl"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_delete",
        "method": "delete",
        "orig_required": {"calendarId": "x"},
        "path": ["calendarList"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_get",
        "method": "get",
        "orig_required": {"calendarId": "x"},
        "path": ["calendarList"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_insert",
        "method": "insert",
        "orig_required": {},
        "path": ["calendarList"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_list",
        "method": "list",
        "orig_required": {},
        "path": ["calendarList"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_patch",
        "method": "patch",
        "orig_required": {"calendarId": "x"},
        "path": ["calendarList"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_update",
        "method": "update",
        "orig_required": {"calendarId": "x"},
        "path": ["calendarList"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendar_list_watch",
        "method": "watch",
        "orig_required": {},
        "path": ["calendarList"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "calendars_clear",
        "method": "clear",
        "orig_required": {"calendarId": "x"},
        "path": ["calendars"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendars_delete",
        "method": "delete",
        "orig_required": {"calendarId": "x"},
        "path": ["calendars"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendars_get",
        "method": "get",
        "orig_required": {"calendarId": "x"},
        "path": ["calendars"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendars_insert",
        "method": "insert",
        "orig_required": {},
        "path": ["calendars"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "calendars_patch",
        "method": "patch",
        "orig_required": {"calendarId": "x"},
        "path": ["calendars"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "calendars_transfer_ownership",
        "method": "transferOwnership",
        "orig_required": {"calendarId": "x", "newDataOwner": "x", "useAdminAccess": True},
        "path": ["calendars"],
        "required": {"calendarId": "x", "newDataOwner": "x", "useAdminAccess": True},
        "service": "calendar",
    },
    {
        "fn": "calendars_update",
        "method": "update",
        "orig_required": {"calendarId": "x"},
        "path": ["calendars"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "channels_stop",
        "method": "stop",
        "orig_required": {},
        "path": ["channels"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "colors_get",
        "method": "get",
        "orig_required": {},
        "path": ["colors"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "events_delete",
        "method": "delete",
        "orig_required": {"calendarId": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_get",
        "method": "get",
        "orig_required": {"calendarId": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_import",
        "method": "import",
        "orig_required": {"calendarId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_insert",
        "method": "insert",
        "orig_required": {"calendarId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_instances",
        "method": "instances",
        "orig_required": {"calendarId": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_list",
        "method": "list",
        "orig_required": {"calendarId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_move",
        "method": "move",
        "orig_required": {"calendarId": "x", "destination": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "destination": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_patch",
        "method": "patch",
        "orig_required": {"calendarId": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_quick_add",
        "method": "quickAdd",
        "orig_required": {"calendarId": "x", "text": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "text": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_update",
        "method": "update",
        "orig_required": {"calendarId": "x", "eventId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x", "eventId": "x"},
        "service": "calendar",
    },
    {
        "fn": "events_watch",
        "method": "watch",
        "orig_required": {"calendarId": "x"},
        "path": ["events"],
        "required": {"calendarId": "x"},
        "service": "calendar",
    },
    {
        "fn": "freebusy_query",
        "method": "query",
        "orig_required": {},
        "path": ["freebusy"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "settings_get",
        "method": "get",
        "orig_required": {"setting": "x"},
        "path": ["settings"],
        "required": {"setting": "x"},
        "service": "calendar",
    },
    {
        "fn": "settings_list",
        "method": "list",
        "orig_required": {},
        "path": ["settings"],
        "required": {},
        "service": "calendar",
    },
    {
        "fn": "settings_watch",
        "method": "watch",
        "orig_required": {},
        "path": ["settings"],
        "required": {},
        "service": "calendar",
    },
]

HELPER_CASES = [
    {"command": "+agenda", "fn": "agenda", "required": {}, "service": "calendar"},
    {
        "command": "+insert",
        "fn": "insert",
        "required": {"end": "x", "start": "x", "summary": "x"},
        "service": "calendar",
    },
]


def test_virtual_available():
    with patch.object(mod._binary, "is_available", return_value=True):
        assert mod.__virtual__() == "gsuite_calendar"


def test_virtual_unavailable():
    with patch.object(mod._binary, "is_available", return_value=False):
        result = mod.__virtual__()
    assert result[0] is False


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dispatch(case):
    with patch.object(mod._gws, "call", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["path"]
    assert args[4] == case["method"]
    sent = call.call_args.kwargs.get("params") or {}
    for key, value in case["orig_required"].items():
        assert sent.get(key) == value


@pytest.mark.parametrize("case", METHOD_CASES, ids=[c["fn"] for c in METHOD_CASES])
def test_method_dry_run(case):
    with patch.object(mod._gws, "call", return_value={}) as call:
        getattr(mod, case["fn"])(test=True, **case["required"])
    sent = call.call_args.kwargs.get("params") or {}
    assert sent.get("test") is True


@pytest.mark.parametrize("case", HELPER_CASES, ids=[c["fn"] for c in HELPER_CASES])
def test_helper_dispatch(case):
    with patch.object(mod._gws, "run_helper", return_value={"ok": True}) as call:
        result = getattr(mod, case["fn"])(**case["required"])
    assert result == {"ok": True}
    args = call.call_args.args
    assert args[2] == case["service"]
    assert args[3] == case["command"]
