# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Audit logs and usage reports execution module.

Audit logs and usage reports

This module is generated from the Google Discovery document for ``admin/reports_v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_admin_reports"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def activities_list(userKey, applicationName, **params):
    """
    Retrieves a list of activities for a specific customer's account and application
    such as the Admin console application or the Google Drive application. For more
    information, see the guides for administrator and Google Drive activity reports. For
    more information about the activity report's parameters, see the activity parameters
    reference guides.

    HTTP: ``GET``  Discovery: ``activities.list``

    Required parameters:

    * ``userKey`` (str): Represents the profile ID or the user email for which the data should be filtered. Can be \`all\` for all information, or \`userKey\` for a user's unique Google Workspace profile ID or their primary emai…
    * ``applicationName`` (str): Application name for which the events are to be retrieved.

    Optional parameters (pass via keyword args):

    * ``actorIpAddress`` (str): The Internet Protocol (IP) Address of host where the event was performed. This is an additional way to filter a report's summary using the IP address of the user whose activity is being reported. Thi…
    * ``applicationInfoFilter`` (str): Optional. Used to filter on the \`oAuthClientId\` field present in [\`ApplicationInfo\`](#applicationinfo) message. \*\*Usage\*\* \`\`\` GET...&applicationInfoFilter=oAuthClientId="clientId" GET...&applicationI…
    * ``customerId`` (str): The unique ID of the customer to retrieve data for.
    * ``endTime`` (str): Sets the end of the range of time shown in the report. The date is in the RFC 3339 format, for example 2010-10-28T10:26:35.000Z. The default value is the approximate time of the API request. An API r…
    * ``eventName`` (str): The name of the event being queried by the API. Each \`eventName\` is related to a specific Google Workspace service or feature which the API organizes into types of events. An example is the Google Ca…
    * ``filters`` (str): The \`filters\` query string is a comma-separated list composed of event parameters manipulated by relational operators. Event parameters are in the form \`{parameter1 name}{relational operator}{paramet…
    * ``groupIdFilter`` (str): Comma separated group ids (obfuscated) on which user activities are filtered, i.e. the response will contain activities for only those users that are a part of at least one of the group ids mentioned…
    * ``includeSensitiveData`` (bool): Optional. When set to \`true\`, this field allows sensitive user-generated content to be included in the returned audit logs. This parameter is supported only for Rules (DLP) and Chat applications; usi…
    * ``maxResults`` (int): Determines how many activity records are shown on each response page. For example, if the request sets \`maxResults=1\` and the report has two activities, the report has two pages. The response's \`next…
    * ``networkInfoFilter`` (str): Optional. Used to filter on the \`regionCode\` field present in [\`NetworkInfo\`](#networkinfo) message. \*\*Usage\*\* \`\`\` GET...&networkInfoFilter=regionCode="IN" GET...&networkInfoFilter=regionCode=%22IN%2…
    * ``orgUnitID`` (str): ID of the organizational unit to report on. Activity records will be shown only for users who belong to the specified organizational unit. Data before Dec 17, 2018 doesn't appear in the filtered resu…
    * ``pageToken`` (str): The token to specify next page. A report with multiple pages has a \`nextPageToken\` property in the response. In your follow-on request getting the next page of the report, enter the \`nextPageToken\` v…
    * ``resourceDetailsFilter`` (str): Optional. The \`resourceDetailsFilter\` query string is an AND separated list composed of [Resource Details](#resourcedetails) fields manipulated by relational operators. Resource Details Filters are i…
    * ``startTime`` (str): Sets the beginning of the range of time shown in the report. The date is in the RFC 3339 format, for example 2010-10-28T10:26:35.000Z. The report returns all activities from \`startTime\` until \`endTim…
    * ``statusFilter`` (str): Optional. Used to filter on the \`statusCode\` field present in [\`Status\`](#status) message. \*\*Usage\*\* \`\`\` GET...&statusFilter=statusCode="200" GET...&statusFilter=statusCode=%22200%22 \`\`\`

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.activities_list userKey=<str> applicationName=<str>
    """
    _params = dict(params)
    _params["userKey"] = userKey
    _params["applicationName"] = applicationName
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["activities"],
        "list",
        params=_params or None,
    )


def activities_watch(userKey, applicationName, body=None, **params):
    """
    Start receiving notifications for account activities. For more information, see
    Receiving Push Notifications.

    HTTP: ``POST``  Discovery: ``activities.watch``

    Required parameters:

    * ``userKey`` (str): Represents the profile ID or the user email for which the data should be filtered. Can be \`all\` for all information, or \`userKey\` for a user's unique Google Workspace profile ID or their primary emai…
    * ``applicationName`` (str): Application name for which the events are to be retrieved.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``actorIpAddress`` (str): The Internet Protocol (IP) Address of host where the event was performed. This is an additional way to filter a report's summary using the IP address of the user whose activity is being reported. Thi…
    * ``customerId`` (str): The unique ID of the customer to retrieve data for.
    * ``endTime`` (str): Sets the end of the range of time shown in the report. The date is in the RFC 3339 format, for example 2010-10-28T10:26:35.000Z. The default value is the approximate time of the API request. An API r…
    * ``eventName`` (str): The name of the event being queried by the API. Each \`eventName\` is related to a specific Google Workspace service or feature which the API organizes into types of events. An example is the Google Ca…
    * ``filters`` (str): The \`filters\` query string is a comma-separated list composed of event parameters manipulated by relational operators. Event parameters are in the form \`{parameter1 name}{relational operator}{paramet…
    * ``groupIdFilter`` (str) *(deprecated)*: \`Deprecated\`. This field is deprecated and is no longer supported. Comma separated group ids (obfuscated) on which user activities are filtered, i.e. the response will contain activities for only tho…
    * ``maxResults`` (int): Determines how many activity records are shown on each response page. For example, if the request sets \`maxResults=1\` and the report has two activities, the report has two pages. The response's \`next…
    * ``orgUnitID`` (str) *(deprecated)*: \`Deprecated\`. This field is deprecated and is no longer supported. ID of the organizational unit to report on. Activity records will be shown only for users who belong to the specified organizational…
    * ``pageToken`` (str): The token to specify next page. A report with multiple pages has a \`nextPageToken\` property in the response. In your follow-on request getting the next page of the report, enter the \`nextPageToken\` v…
    * ``startTime`` (str): Sets the beginning of the range of time shown in the report. The date is in the RFC 3339 format, for example 2010-10-28T10:26:35.000Z. The report returns all activities from \`startTime\` until \`endTim…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.activities_watch userKey=<str> applicationName=<str>
    """
    _params = dict(params)
    _params["userKey"] = userKey
    _params["applicationName"] = applicationName
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["activities"],
        "watch",
        params=_params or None,
        body=body,
    )


def channels_stop(body=None, **params):
    """
    Stop watching resources through this channel.

    HTTP: ``POST``  Discovery: ``channels.stop``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.channels_stop
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["channels"],
        "stop",
        params=_params or None,
        body=body,
    )


def customer_usage_reports_get(date, **params):
    """
    Retrieves a report which is a collection of properties and statistics for a specific
    customer's account. For more information, see the Customers Usage Report guide. For
    more information about the customer report's parameters, see the Customers Usage
    parameters reference guides.

    HTTP: ``GET``  Discovery: ``customerUsageReports.get``

    Required parameters:

    * ``date`` (str): Represents the date the usage occurred, based on UTC-8:00 (Pacific Standard Time). The timestamp is in the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO\_8601), \`yyyy-mm-dd\`.

    Optional parameters (pass via keyword args):

    * ``customerId`` (str): The unique ID of the customer to retrieve data for.
    * ``pageToken`` (str): Token to specify next page. A report with multiple pages has a \`nextPageToken\` property in the response. For your follow-on requests getting all of the report's pages, enter the \`nextPageToken\` value…
    * ``parameters`` (str): The \`parameters\` query string is a comma-separated list of event parameters that refine a report's results. The parameter is associated with a specific application. The application values for the Cus…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.customer_usage_reports_get date=<str>
    """
    _params = dict(params)
    _params["date"] = date
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["customerUsageReports"],
        "get",
        params=_params or None,
    )


def entity_usage_reports_get(entityType, entityKey, date, **params):
    """
    Retrieves a report which is a collection of properties and statistics for entities
    used by users within the account. For more information, see the Entities Usage
    Report guide. For more information about the entities report's parameters, see the
    Entities Usage parameters reference guides.

    HTTP: ``GET``  Discovery: ``entityUsageReports.get``

    Required parameters:

    * ``entityType`` (str): Represents the type of entity for the report.
    * ``entityKey`` (str): Represents the key of the object to filter the data with. It is a string which can take the value \`all\` to get activity events for all users, or any other value for an app-specific entity. For detail…
    * ``date`` (str): Represents the date the usage occurred, based on UTC-8:00 (Pacific Standard Time). The timestamp is in the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO\_8601), \`yyyy-mm-dd\`.

    Optional parameters (pass via keyword args):

    * ``customerId`` (str): The unique ID of the customer to retrieve data for.
    * ``filters`` (str): The \`filters\` query string is a comma-separated list of an application's event parameters where the parameter's value is manipulated by a relational operator. The \`filters\` query string includes the…
    * ``maxResults`` (int): Determines how many activity records are shown on each response page. For example, if the request sets \`maxResults=1\` and the report has two activities, the report has two pages. The response's \`next…
    * ``pageToken`` (str): Token to specify next page. A report with multiple pages has a \`nextPageToken\` property in the response. In your follow-on request getting the next page of the report, enter the \`nextPageToken\` value…
    * ``parameters`` (str): The \`parameters\` query string is a comma-separated list of event parameters that refine a report's results. The parameter is associated with a specific application. The application values for the Ent…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.entity_usage_reports_get entityType=<str> entityKey=<str> date=<str>
    """
    _params = dict(params)
    _params["entityType"] = entityType
    _params["entityKey"] = entityKey
    _params["date"] = date
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["entityUsageReports"],
        "get",
        params=_params or None,
    )


def user_usage_report_get(userKey, date, **params):
    """
    Retrieves a report which is a collection of properties and statistics for a set of
    users with the account. For more information, see the User Usage Report guide. For
    more information about the user report's parameters, see the Users Usage parameters
    reference guides.

    HTTP: ``GET``  Discovery: ``userUsageReport.get``

    Required parameters:

    * ``userKey`` (str): Represents the profile ID or the user email for which the data should be filtered. Can be \`all\` for all information, or \`userKey\` for a user's unique Google Workspace profile ID or their primary emai…
    * ``date`` (str): Represents the date the usage occurred, based on UTC-8:00 (Pacific Standard Time). The timestamp is in the [ISO 8601 format](https://en.wikipedia.org/wiki/ISO\_8601), \`yyyy-mm-dd\`.

    Optional parameters (pass via keyword args):

    * ``customerId`` (str): The unique ID of the customer to retrieve data for.
    * ``filters`` (str): The \`filters\` query string is a comma-separated list of an application's event parameters where the parameter's value is manipulated by a relational operator. The \`filters\` query string includes the…
    * ``groupIdFilter`` (str): Comma separated group ids (obfuscated) on which user activities are filtered, i.e. the response will contain activities for only those users that are a part of at least one of the group ids mentioned…
    * ``maxResults`` (int): Determines how many activity records are shown on each response page. For example, if the request sets \`maxResults=1\` and the report has two activities, the report has two pages. The response's \`next…
    * ``orgUnitID`` (str): ID of the organizational unit to report on. User activity will be shown only for users who belong to the specified organizational unit. Data before Dec 17, 2018 doesn't appear in the filtered results.
    * ``pageToken`` (str): Token to specify next page. A report with multiple pages has a \`nextPageToken\` property in the response. In your follow-on request getting the next page of the report, enter the \`nextPageToken\` value…
    * ``parameters`` (str): The \`parameters\` query string is a comma-separated list of event parameters that refine a report's results. The parameter is associated with a specific application. The application values for the Cus…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_admin_reports.user_usage_report_get userKey=<str> date=<str>
    """
    _params = dict(params)
    _params["userKey"] = userKey
    _params["date"] = date
    return _gws.call(
        __opts__,
        __pillar__,
        "admin-reports",
        ["userUsageReport"],
        "get",
        params=_params or None,
    )
