# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Subscribe to Google Workspace events execution module.

Subscribe to Google Workspace events

This module is generated from the Google Discovery document for ``workspaceevents/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_events"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def message_stream(body=None, **params):
    """
    SendStreamingMessage is a streaming call that will return a stream of task update
    events until the Task is in an interrupted or terminal state.

    HTTP: ``POST``  Discovery: ``message.stream``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.message_stream
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["message"],
        "stream",
        params=_params or None,
        body=body,
    )


def operations_get(name, **params):
    """
    Gets the latest state of a long-running operation. Clients can use this method to
    poll the operation result at intervals as recommended by the API service.

    HTTP: ``GET``  Discovery: ``operations.get``

    Required parameters:

    * ``name`` (str): The name of the operation resource.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.operations_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["operations"],
        "get",
        params=_params or None,
    )


def subscriptions_create(body=None, **params):
    """
    Creates a Google Workspace subscription. To learn how to use this method, see
    [Create a Google Workspace
    subscription](https://developers.google.com/workspace/events/guides/create-
    subscription). For a subscription on a [Chat target
    resource](https://developers.google.com/workspace/events/guides/events-chat), you
    can create a subscription as: - A Chat app by specifying an authorization scope that
    begins with \`chat.app\` and getting one-time administrator approval. To learn more,
    see [Authorize as a Chat app with administrator
    approval](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    app). - A user by specifying an authorization scope that doesn't include \`app\` in
    its name. To learn more, see [Authorize as a Chat
    user](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    user).

    HTTP: ``POST``  Discovery: ``subscriptions.create``

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``validateOnly`` (bool): Optional. If set to \`true\`, validates and previews the request, but doesn't create the subscription.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "create",
        params=_params or None,
        body=body,
    )


def subscriptions_delete(name, **params):
    """
    Deletes a Google Workspace subscription. To learn how to use this method, see
    [Delete a Google Workspace
    subscription](https://developers.google.com/workspace/events/guides/delete-
    subscription).

    HTTP: ``DELETE``  Discovery: ``subscriptions.delete``

    Required parameters:

    * ``name`` (str): Required. Resource name of the subscription to delete. Format: \`subscriptions/{subscription}\`

    Optional parameters (pass via keyword args):

    * ``allowMissing`` (bool): Optional. If set to \`true\` and the subscription isn't found, the request succeeds but doesn't delete the subscription.
    * ``etag`` (str): Optional. Etag of the subscription. If present, it must match with the server's etag. Otherwise, request fails with the status \`ABORTED\`.
    * ``validateOnly`` (bool): Optional. If set to \`true\`, validates and previews the request, but doesn't delete the subscription.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_delete name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "delete",
        params=_params or None,
    )


def subscriptions_get(name, **params):
    """
    Gets details about a Google Workspace subscription. To learn how to use this method,
    see [Get details about a Google Workspace
    subscription](https://developers.google.com/workspace/events/guides/get-
    subscription).

    HTTP: ``GET``  Discovery: ``subscriptions.get``

    Required parameters:

    * ``name`` (str): Required. Resource name of the subscription. Format: \`subscriptions/{subscription}\`

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "get",
        params=_params or None,
    )


def subscriptions_list(**params):
    """
    Lists Google Workspace subscriptions. To learn how to use this method, see [List
    Google Workspace
    subscriptions](https://developers.google.com/workspace/events/guides/list-
    subscriptions).

    HTTP: ``GET``  Discovery: ``subscriptions.list``

    Optional parameters (pass via keyword args):

    * ``filter`` (str): Required. A query filter. You can filter subscriptions by event type (\`event\_types\`) and target resource (\`target\_resource\`). You must specify at least one event type in your query. To filter for mul…
    * ``pageSize`` (int): Optional. The maximum number of subscriptions to return. The service might return fewer than this value. If unspecified or set to \`0\`, up to 50 subscriptions are returned. The maximum value is 100. I…
    * ``pageToken`` (str): Optional. A page token, received from a previous list subscriptions call. Provide this parameter to retrieve the subsequent page. When paginating, the filter value should match the call that provided…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "list",
        params=_params or None,
    )


def subscriptions_patch(name, body=None, **params):
    """
    Updates or renews a Google Workspace subscription. To learn how to use this method,
    see [Update or renew a Google Workspace
    subscription](https://developers.google.com/workspace/events/guides/update-
    subscription). For a subscription on a [Chat target
    resource](https://developers.google.com/workspace/events/guides/events-chat), you
    can update a subscription as: - A Chat app by specifying an authorization scope that
    begins with \`chat.app\` and getting one-time administrator approval. To learn more,
    see [Authorize as a Chat app with administrator
    approval](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    app). - A user by specifying an authorization scope that doesn't include \`app\` in
    its name. To learn more, see [Authorize as a Chat
    user](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    user).

    HTTP: ``PATCH``  Discovery: ``subscriptions.patch``

    Required parameters:

    * ``name`` (str): Identifier. Resource name of the subscription. Format: \`subscriptions/{subscription}\`

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``updateMask`` (str): Optional. The field to update. If omitted, updates any fields included in the request. You can update one of the following fields in a subscription: \* \`expire\_time\`: The timestamp when the subscripti…
    * ``validateOnly`` (bool): Optional. If set to \`true\`, validates and previews the request, but doesn't update the subscription.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_patch name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "patch",
        params=_params or None,
        body=body,
    )


def subscriptions_reactivate(name, body=None, **params):
    """
    Reactivates a suspended Google Workspace subscription. This method resets your
    subscription's \`State\` field to \`ACTIVE\`. Before you use this method, you must
    fix the error that suspended the subscription. This method will ignore or reject any
    subscription that isn't currently in a suspended state. To learn how to use this
    method, see [Reactivate a Google Workspace
    subscription](https://developers.google.com/workspace/events/guides/reactivate-
    subscription). For a subscription on a [Chat target
    resource](https://developers.google.com/workspace/events/guides/events-chat), you
    can reactivate a subscription as: - A Chat app by specifying an authorization scope
    that begins with \`chat.app\` and getting one-time administrator approval. To learn
    more, see [Authorize as a Chat app with administrator
    approval](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    app). - A user by specifying an authorization scope that doesn't include \`app\` in
    its name. To learn more, see [Authorize as a Chat
    user](https://developers.google.com/workspace/chat/authenticate-authorize-chat-
    user).

    HTTP: ``POST``  Discovery: ``subscriptions.reactivate``

    Required parameters:

    * ``name`` (str): Required. Resource name of the subscription. Format: \`subscriptions/{subscription}\`

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscriptions_reactivate name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["subscriptions"],
        "reactivate",
        params=_params or None,
        body=body,
    )


def tasks_cancel(name, body=None, **params):
    """
    Cancel a task from the agent. If supported one should expect no more task updates
    for the task.

    HTTP: ``POST``  Discovery: ``tasks.cancel``

    Required parameters:

    * ``name`` (str): The resource name of the task to cancel. Format: tasks/{task\_id}

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_cancel name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks"],
        "cancel",
        params=_params or None,
        body=body,
    )


def tasks_get(name, **params):
    """
    Get the current state of a task from the agent.

    HTTP: ``GET``  Discovery: ``tasks.get``

    Required parameters:

    * ``name`` (str): Required. The resource name of the task. Format: tasks/{task\_id}

    Optional parameters (pass via keyword args):

    * ``historyLength`` (int): The number of most recent messages from the task's history to retrieve.
    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks"],
        "get",
        params=_params or None,
    )


def tasks_subscribe(name, **params):
    """
    TaskSubscription is a streaming call that will return a stream of task update
    events. This attaches the stream to an existing in process task. If the task is
    complete the stream will return the completed task (like GetTask) and close the
    stream.

    HTTP: ``GET``  Discovery: ``tasks.subscribe``

    Required parameters:

    * ``name`` (str): The resource name of the task to subscribe to. Format: tasks/{task\_id}

    Optional parameters (pass via keyword args):

    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_subscribe name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks"],
        "subscribe",
        params=_params or None,
    )


def tasks_push_notification_configs_create(parent, body=None, **params):
    """
    Set a push notification config for a task.

    HTTP: ``POST``  Discovery: ``tasks.pushNotificationConfigs.create``

    Required parameters:

    * ``parent`` (str): Required. The parent task resource for this config. Format: tasks/{task\_id}

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``configId`` (str): Required. The ID for the new config.
    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_push_notification_configs_create parent=<str>
    """
    _params = dict(params)
    _params["parent"] = parent
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks", "pushNotificationConfigs"],
        "create",
        params=_params or None,
        body=body,
    )


def tasks_push_notification_configs_delete(name, **params):
    """
    Delete a push notification config for a task.

    HTTP: ``DELETE``  Discovery: ``tasks.pushNotificationConfigs.delete``

    Required parameters:

    * ``name`` (str): The resource name of the config to delete. Format: tasks/{task\_id}/pushNotificationConfigs/{config\_id}

    Optional parameters (pass via keyword args):

    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_push_notification_configs_delete name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks", "pushNotificationConfigs"],
        "delete",
        params=_params or None,
    )


def tasks_push_notification_configs_get(name, **params):
    """
    Get a push notification config for a task.

    HTTP: ``GET``  Discovery: ``tasks.pushNotificationConfigs.get``

    Required parameters:

    * ``name`` (str): The resource name of the config to retrieve. Format: tasks/{task\_id}/pushNotificationConfigs/{config\_id}

    Optional parameters (pass via keyword args):

    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_push_notification_configs_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks", "pushNotificationConfigs"],
        "get",
        params=_params or None,
    )


def tasks_push_notification_configs_list(parent, **params):
    """
    Get a list of push notifications configured for a task.

    HTTP: ``GET``  Discovery: ``tasks.pushNotificationConfigs.list``

    Required parameters:

    * ``parent`` (str): The parent task resource. Format: tasks/{task\_id}

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): For AIP-158 these fields are present. Usually not used/needed. The maximum number of configurations to return. If unspecified, all configs will be returned.
    * ``pageToken`` (str): A page token received from a previous ListTaskPushNotificationConfigRequest call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to \`ListTaskPushNotifica…
    * ``tenant`` (str): Optional tenant, provided as a path parameter. Experimental, might still change for 1.0 release.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.tasks_push_notification_configs_list parent=<str>
    """
    _params = dict(params)
    _params["parent"] = parent
    return _gws.call(
        __opts__,
        __pillar__,
        "events",
        ["tasks", "pushNotificationConfigs"],
        "list",
        params=_params or None,
    )


def renew(all=None, name=None, within=None, test=False):
    """
    [Helper] Renew/reactivate Workspace Events subscriptions

    Options:

    * ``all`` (optional flag): Renew all subscriptions expiring within --within window
    * ``name`` (optional value): Subscription name to reactivate (e.g., subscriptions/SUB\_ID)
    * ``within`` (optional value): Time window for --all (e.g., 1h, 30m, 2d) [default: 1h]

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.renew
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "events",
        "+renew",
        flags={
            "name": name,
            "within": within,
        },
        switches={
            "all": all,
        },
        test=test,
    )


def subscribe(
    cleanup=None,
    event_types=None,
    max_messages=None,
    no_ack=None,
    once=None,
    output_dir=None,
    poll_interval=None,
    project=None,
    subscription=None,
    target=None,
    test=False,
):
    """
    [Helper] Subscribe to Workspace events and stream them as NDJSON

    Options:

    * ``cleanup`` (optional flag): Delete created Pub/Sub resources on exit
    * ``event_types`` (optional value): Comma-separated CloudEvents types to subscribe to
    * ``max_messages`` (optional value): Max messages per pull batch (default: 10) [default: 10]
    * ``no_ack`` (optional flag): Don't auto-acknowledge messages
    * ``once`` (optional flag): Pull once and exit
    * ``output_dir`` (optional value): Write each event to a separate JSON file in this directory
    * ``poll_interval`` (optional value): Seconds between pulls (default: 5) [default: 5]
    * ``project`` (optional value): GCP project ID for Pub/Sub resources
    * ``subscription`` (optional value): Existing Pub/Sub subscription name (skip setup)
    * ``target`` (optional value): Workspace resource URI (e.g., //chat.googleapis.com/spaces/SPACE\_ID)

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_events.subscribe
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "events",
        "+subscribe",
        flags={
            "event-types": event_types,
            "max-messages": max_messages,
            "output-dir": output_dir,
            "poll-interval": poll_interval,
            "project": project,
            "subscription": subscription,
            "target": target,
        },
        switches={
            "cleanup": cleanup,
            "no-ack": no_ack,
            "once": once,
        },
        test=test,
    )
