# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Manage Google Apps Script projects execution module.

Manage Google Apps Script projects

This module is generated from the Google Discovery document for ``script/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_script"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def processes_list(**params):
    """
    List information about processes made by or on behalf of a user, such as process
    type and current status.

    HTTP: ``GET``  Discovery: ``processes.list``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of returned processes per page of results. Defaults to 50.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \\`nextPageToken\\` from a previous response.
    * ``userProcessFilter.deploymentId`` (str): Optional field used to limit returned processes to those originating from projects with a specific deployment ID.
    * ``userProcessFilter.endTime`` (str): Optional field used to limit returned processes to those that completed on or before the given timestamp.
    * ``userProcessFilter.functionName`` (str): Optional field used to limit returned processes to those originating from a script function with the given function name.
    * ``userProcessFilter.projectName`` (str): Optional field used to limit returned processes to those originating from projects with project names containing a specific string.
    * ``userProcessFilter.scriptId`` (str): Optional field used to limit returned processes to those originating from projects with a specific script ID.
    * ``userProcessFilter.startTime`` (str): Optional field used to limit returned processes to those that were started on or after the given timestamp.
    * ``userProcessFilter.statuses`` (str): Optional field used to limit returned processes to those having one of the specified process statuses.
    * ``userProcessFilter.types`` (str): Optional field used to limit returned processes to those having one of the specified process types.
    * ``userProcessFilter.userAccessLevels`` (str): Optional field used to limit returned processes to those having one of the specified user access levels.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.processes_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["processes"],
        "list",
        params=_params or None,
    )


def processes_list_script_processes(**params):
    """
    List information about a script's executed processes, such as process type and
    current status.

    HTTP: ``GET``  Discovery: ``processes.listScriptProcesses``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of returned processes per page of results. Defaults to 50.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \\`nextPageToken\\` from a previous response.
    * ``scriptId`` (str): The script ID of the project whose processes are listed.
    * ``scriptProcessFilter.deploymentId`` (str): Optional field used to limit returned processes to those originating from projects with a specific deployment ID.
    * ``scriptProcessFilter.endTime`` (str): Optional field used to limit returned processes to those that completed on or before the given timestamp.
    * ``scriptProcessFilter.functionName`` (str): Optional field used to limit returned processes to those originating from a script function with the given function name.
    * ``scriptProcessFilter.startTime`` (str): Optional field used to limit returned processes to those that were started on or after the given timestamp.
    * ``scriptProcessFilter.statuses`` (str): Optional field used to limit returned processes to those having one of the specified process statuses.
    * ``scriptProcessFilter.types`` (str): Optional field used to limit returned processes to those having one of the specified process types.
    * ``scriptProcessFilter.userAccessLevels`` (str): Optional field used to limit returned processes to those having one of the specified user access levels.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.processes_list_script_processes
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["processes"],
        "listScriptProcesses",
        params=_params or None,
    )


def projects_create(body=None, **params):
    """
    Creates a new, empty script project with no script files and a base manifest file.

    HTTP: ``POST``  Discovery: ``projects.create``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects"],
        "create",
        params=_params or None,
        body=body,
    )


def projects_get(scriptId, **params):
    """
    Gets a script project's metadata.

    HTTP: ``GET``  Discovery: ``projects.get``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_get scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects"],
        "get",
        params=_params or None,
    )


def projects_get_content(scriptId, **params):
    """
    Gets the content of the script project, including the code source and metadata for
    each script file.

    HTTP: ``GET``  Discovery: ``projects.getContent``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    Optional parameters (pass via keyword args):

    * ``versionNumber`` (int): The version number of the project to retrieve. If not provided, the project's HEAD version is returned.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_get_content scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects"],
        "getContent",
        params=_params or None,
    )


def projects_get_metrics(scriptId, **params):
    """
    Get metrics data for scripts, such as number of executions and active users.

    HTTP: ``GET``  Discovery: ``projects.getMetrics``

    Required parameters:

    * ``scriptId`` (str): Required field indicating the script to get metrics for.

    Optional parameters (pass via keyword args):

    * ``metricsFilter.deploymentId`` (str): Optional field indicating a specific deployment to retrieve metrics from.
    * ``metricsGranularity`` (str): Required field indicating what granularity of metrics are returned.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_get_metrics scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects"],
        "getMetrics",
        params=_params or None,
    )


def projects_update_content(scriptId, body=None, **params):
    """
    Updates the content of the specified script project. This content is stored as the
    HEAD version, and is used when the script is executed as a trigger, in the script
    editor, in add-on preview mode, or as a web app or Apps Script API in development
    mode. This clears all the existing files in the project.

    HTTP: ``PUT``  Discovery: ``projects.updateContent``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_update_content scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects"],
        "updateContent",
        params=_params or None,
        body=body,
    )


def projects_deployments_create(scriptId, body=None, **params):
    """
    Creates a deployment of an Apps Script project.

    HTTP: ``POST``  Discovery: ``projects.deployments.create``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_deployments_create scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "deployments"],
        "create",
        params=_params or None,
        body=body,
    )


def projects_deployments_delete(scriptId, deploymentId, **params):
    """
    Deletes a deployment of an Apps Script project.

    HTTP: ``DELETE``  Discovery: ``projects.deployments.delete``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.
    * ``deploymentId`` (str): The deployment ID to be undeployed.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_deployments_delete scriptId=<str> deploymentId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    _params["deploymentId"] = deploymentId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "deployments"],
        "delete",
        params=_params or None,
    )


def projects_deployments_get(scriptId, deploymentId, **params):
    """
    Gets a deployment of an Apps Script project.

    HTTP: ``GET``  Discovery: ``projects.deployments.get``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.
    * ``deploymentId`` (str): The deployment ID.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_deployments_get scriptId=<str> deploymentId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    _params["deploymentId"] = deploymentId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "deployments"],
        "get",
        params=_params or None,
    )


def projects_deployments_list(scriptId, **params):
    """
    Lists the deployments of an Apps Script project.

    HTTP: ``GET``  Discovery: ``projects.deployments.list``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of deployments on each returned page. Defaults to 50.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \\`nextPageToken\\` from a previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_deployments_list scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "deployments"],
        "list",
        params=_params or None,
    )


def projects_deployments_update(scriptId, deploymentId, body=None, **params):
    """
    Updates a deployment of an Apps Script project.

    HTTP: ``PUT``  Discovery: ``projects.deployments.update``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.
    * ``deploymentId`` (str): The deployment ID for this deployment.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_deployments_update scriptId=<str> deploymentId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    _params["deploymentId"] = deploymentId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "deployments"],
        "update",
        params=_params or None,
        body=body,
    )


def projects_versions_create(scriptId, body=None, **params):
    """
    Creates a new immutable version using the current code, with a unique version
    number.

    HTTP: ``POST``  Discovery: ``projects.versions.create``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_versions_create scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "versions"],
        "create",
        params=_params or None,
        body=body,
    )


def projects_versions_get(scriptId, versionNumber, **params):
    """
    Gets a version of a script project.

    HTTP: ``GET``  Discovery: ``projects.versions.get``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.
    * ``versionNumber`` (int): The version number.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_versions_get scriptId=<str> versionNumber=<int>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    _params["versionNumber"] = versionNumber
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "versions"],
        "get",
        params=_params or None,
    )


def projects_versions_list(scriptId, **params):
    """
    List the versions of a script project.

    HTTP: ``GET``  Discovery: ``projects.versions.list``

    Required parameters:

    * ``scriptId`` (str): The script project's Drive ID.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of versions on each returned page. Defaults to 50.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \\`nextPageToken\\` from a previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.projects_versions_list scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["projects", "versions"],
        "list",
        params=_params or None,
    )


def scripts_run(scriptId, body=None, **params):
    """
    HTTP: ``POST``  Discovery: ``scripts.run``

    Required parameters:

    * ``scriptId`` (str): The script ID of the script to be executed. Find the script ID on the \\*\\*Project settings\\*\\* page under "IDs." As multiple executable APIs can be deployed in new IDE for same script, this field should…

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.scripts_run scriptId=<str>
    """
    _params = dict(params)
    _params["scriptId"] = scriptId
    return _gws.call(
        __opts__,
        __pillar__,
        "script",
        ["scripts"],
        "run",
        params=_params or None,
        body=body,
    )


def push(script, dir=None, test=False):
    """
    [Helper] Upload local files to an Apps Script project

    Options:

    * ``script`` (required value): Script Project ID
    * ``dir`` (optional value): Directory containing script files (defaults to current dir)

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_script.push
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "script",
        "+push",
        flags={
            "script": script,
            "dir": dir,
        },
        test=test,
    )
