# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Manage task lists and tasks execution module.

Manage task lists and tasks

This module is generated from the Google Discovery document for ``tasks/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_tasks"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def tasklists_delete(tasklist, **params):
    """
    Deletes the authenticated user's specified task list. If the list contains assigned
    tasks, both the assigned tasks and the original tasks in the assignment surface
    (Docs, Chat Spaces) are deleted.

    HTTP: ``DELETE``  Discovery: ``tasklists.delete``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_delete tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "delete",
        params=_params or None,
    )


def tasklists_get(tasklist, **params):
    """
    Returns the authenticated user's specified task list.

    HTTP: ``GET``  Discovery: ``tasklists.get``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_get tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "get",
        params=_params or None,
    )


def tasklists_insert(body=None, **params):
    """
    Creates a new task list and adds it to the authenticated user's task lists. A user
    can have up to 2000 lists at a time.

    HTTP: ``POST``  Discovery: ``tasklists.insert``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_insert
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "insert",
        params=_params or None,
        body=body,
    )


def tasklists_list(**params):
    """
    Returns all the authenticated user's task lists. A user can have up to 2000 lists at
    a time.

    HTTP: ``GET``  Discovery: ``tasklists.list``

    Optional parameters (pass via keyword args):

    * ``maxResults`` (int): Maximum number of task lists returned on one page. Optional. The default is 1000 (max allowed: 1000).
    * ``pageToken`` (str): Token specifying the result page to return. Optional.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "list",
        params=_params or None,
    )


def tasklists_patch(tasklist, body=None, **params):
    """
    Updates the authenticated user's specified task list. This method supports patch
    semantics.

    HTTP: ``PATCH``  Discovery: ``tasklists.patch``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_patch tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "patch",
        params=_params or None,
        body=body,
    )


def tasklists_update(tasklist, body=None, **params):
    """
    Updates the authenticated user's specified task list.

    HTTP: ``PUT``  Discovery: ``tasklists.update``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasklists_update tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasklists"],
        "update",
        params=_params or None,
        body=body,
    )


def tasks_clear(tasklist, **params):
    """
    Clears all completed tasks from the specified task list. The affected tasks will be
    marked as 'hidden' and no longer be returned by default when retrieving all tasks
    for a task list.

    HTTP: ``POST``  Discovery: ``tasks.clear``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_clear tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "clear",
        params=_params or None,
    )


def tasks_delete(tasklist, task, **params):
    """
    Deletes the specified task from the task list. If the task is assigned, both the
    assigned task and the original task (in Docs, Chat Spaces) are deleted. To delete
    the assigned task only, navigate to the assignment surface and unassign the task
    from there.

    HTTP: ``DELETE``  Discovery: ``tasks.delete``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.
    * ``task`` (str): Task identifier.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_delete tasklist=<str> task=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    _params["task"] = task
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "delete",
        params=_params or None,
    )


def tasks_get(tasklist, task, **params):
    """
    Returns the specified task.

    HTTP: ``GET``  Discovery: ``tasks.get``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.
    * ``task`` (str): Task identifier.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_get tasklist=<str> task=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    _params["task"] = task
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "get",
        params=_params or None,
    )


def tasks_insert(tasklist, body=None, **params):
    """
    Creates a new task on the specified task list. Tasks assigned from Docs or Chat
    Spaces cannot be inserted from Tasks Public API; they can only be created by
    assigning them from Docs or Chat Spaces. A user can have up to 20,000 non-hidden
    tasks per list and up to 100,000 tasks in total at a time.

    HTTP: ``POST``  Discovery: ``tasks.insert``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``parent`` (str): Parent task identifier. If the task is created at the top level, this parameter is omitted. An assigned task cannot be a parent task, nor can it have a parent. Setting the parent to an assigned task…
    * ``previous`` (str): Previous sibling task identifier. If the task is created at the first position among its siblings, this parameter is omitted. Optional.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_insert tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "insert",
        params=_params or None,
        body=body,
    )


def tasks_list(tasklist, **params):
    """
    Returns all tasks in the specified task list. Doesn't return assigned tasks by
    default (from Docs, Chat Spaces). A user can have up to 20,000 non-hidden tasks per
    list and up to 100,000 tasks in total at a time.

    HTTP: ``GET``  Discovery: ``tasks.list``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.

    Optional parameters (pass via keyword args):

    * ``completedMax`` (str): Upper bound for a task's completion date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by completion date.
    * ``completedMin`` (str): Lower bound for a task's completion date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by completion date.
    * ``dueMax`` (str): Upper bound for a task's due date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by due date.
    * ``dueMin`` (str): Lower bound for a task's due date (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by due date.
    * ``maxResults`` (int): Maximum number of tasks returned on one page. Optional. The default is 20 (max allowed: 100).
    * ``pageToken`` (str): Token specifying the result page to return. Optional.
    * ``showAssigned`` (bool): Optional. Flag indicating whether tasks assigned to the current user are returned in the result. Optional. The default is False.
    * ``showCompleted`` (bool): Flag indicating whether completed tasks are returned in the result. Note that showHidden must also be True to show tasks completed in first party clients, such as the web UI and Google's mobile apps.…
    * ``showDeleted`` (bool): Flag indicating whether deleted tasks are returned in the result. Optional. The default is False.
    * ``showHidden`` (bool): Flag indicating whether hidden tasks are returned in the result. Optional. The default is False.
    * ``updatedMin`` (str): Lower bound for a task's last modification time (as a RFC 3339 timestamp) to filter by. Optional. The default is not to filter by last modification time.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_list tasklist=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "list",
        params=_params or None,
    )


def tasks_move(tasklist, task, **params):
    """
    Moves the specified task to another position in the destination task list. If the
    destination list is not specified, the task is moved within its current list. This
    can include putting it as a child task under a new parent and/or move it to a
    different position among its sibling tasks. A user can have up to 2,000 subtasks per
    task.

    HTTP: ``POST``  Discovery: ``tasks.move``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.
    * ``task`` (str): Task identifier.

    Optional parameters (pass via keyword args):

    * ``destinationTasklist`` (str): Optional. Destination task list identifier. If set, the task is moved from tasklist to the destinationTasklist list. Otherwise the task is moved within its current list. Recurrent tasks cannot curren…
    * ``parent`` (str): Optional. New parent task identifier. If the task is moved to the top level, this parameter is omitted. The task set as parent must exist in the task list and can not be hidden. Exceptions: 1. Assign…
    * ``previous`` (str): Optional. New previous sibling task identifier. If the task is moved to the first position among its siblings, this parameter is omitted. The task set as previous must exist in the task list and can…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_move tasklist=<str> task=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    _params["task"] = task
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "move",
        params=_params or None,
    )


def tasks_patch(tasklist, task, body=None, **params):
    """
    Updates the specified task. This method supports patch semantics.

    HTTP: ``PATCH``  Discovery: ``tasks.patch``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.
    * ``task`` (str): Task identifier.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_patch tasklist=<str> task=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    _params["task"] = task
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "patch",
        params=_params or None,
        body=body,
    )


def tasks_update(tasklist, task, body=None, **params):
    """
    Updates the specified task.

    HTTP: ``PUT``  Discovery: ``tasks.update``

    Required parameters:

    * ``tasklist`` (str): Task list identifier.
    * ``task`` (str): Task identifier.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_tasks.tasks_update tasklist=<str> task=<str>
    """
    _params = dict(params)
    _params["tasklist"] = tasklist
    _params["task"] = task
    return _gws.call(
        __opts__,
        __pillar__,
        "tasks",
        ["tasks"],
        "update",
        params=_params or None,
        body=body,
    )
