# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Read and write spreadsheets execution module.

Read and write spreadsheets

This module is generated from the Google Discovery document for ``sheets/v4``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_sheets"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def spreadsheets_batch_update(spreadsheetId, body=None, **params):
    """
    Applies one or more updates to the spreadsheet. Each request is validated before
    being applied. If any request is not valid then the entire request will fail and
    nothing will be applied. Some requests have replies to give you some information
    about how they are applied. The replies will mirror the requests. For example, if
    you applied 4 updates and the 3rd one had a reply, then the response will have 2
    empty replies, the actual reply, and another empty reply, in that order. Due to the
    collaborative nature of spreadsheets, it is not guaranteed that the spreadsheet will
    reflect exactly your changes after this completes, however it is guaranteed that the
    updates in the request will be applied together atomically. Your changes may be
    altered with respect to collaborator changes. If there are no collaborators, the
    spreadsheet should reflect your changes.

    HTTP: ``POST``  Discovery: ``spreadsheets.batchUpdate``

    Required parameters:

    * ``spreadsheetId`` (str): The spreadsheet to apply the updates to.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_batch_update spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets"],
        "batchUpdate",
        params=_params or None,
        body=body,
    )


def spreadsheets_create(body=None, **params):
    """
    Creates a spreadsheet, returning the newly created spreadsheet.

    HTTP: ``POST``  Discovery: ``spreadsheets.create``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets"],
        "create",
        params=_params or None,
        body=body,
    )


def spreadsheets_get(spreadsheetId, **params):
    """
    Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID.
    By default, data within grids is not returned. You can include grid data in one of 2
    ways: \* Specify a [field
    mask](https://developers.google.com/workspace/sheets/api/guides/field-masks) listing
    your desired fields using the \`fields\` URL parameter in HTTP \* Set the
    includeGridData URL parameter to true. If a field mask is set, the
    \`includeGridData\` parameter is ignored For large spreadsheets, as a best practice,
    retrieve only the specific spreadsheet fields that you want. To retrieve only
    subsets of spreadsheet data, use the ranges URL parameter. Ranges are specified
    using [A1
    notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell).
    You can define a single cell (for example, \`A1\`) or multiple cells (for example,
    \`A1:D5\`). You can also get cells from other sheets within the same spreadsheet
    (for example, \`Sheet2!A1:C4\`) or retrieve multiple ranges at once (for example,
    \`?ranges=A1:D5&ranges=Sheet2!A1:C4\`). Limiting the range returns only the portions
    of the spreadsheet that intersect the requested ranges.

    HTTP: ``GET``  Discovery: ``spreadsheets.get``

    Required parameters:

    * ``spreadsheetId`` (str): The spreadsheet to request.

    Optional parameters (pass via keyword args):

    * ``excludeTablesInBandedRanges`` (bool): True if tables should be excluded in the banded ranges. False if not set.
    * ``includeGridData`` (bool): True if grid data should be returned. This parameter is ignored if a field mask was set in the request.
    * ``ranges`` (str): The ranges to retrieve from the spreadsheet.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_get spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets"],
        "get",
        params=_params or None,
    )


def spreadsheets_get_by_data_filter(spreadsheetId, body=None, **params):
    """
    Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID.
    For more information, see [Read, write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). This
    method differs from GetSpreadsheet in that it allows selecting which subsets of
    spreadsheet data to return by specifying a dataFilters parameter. Multiple
    DataFilters can be specified. Specifying one or more data filters returns the
    portions of the spreadsheet that intersect ranges matched by any of the filters. By
    default, data within grids is not returned. You can include grid data in one of two
    ways: \* Specify a [field
    mask](https://developers.google.com/workspace/sheets/api/guides/field-masks) listing
    your desired fields using the \`fields\` URL parameter in HTTP. \* Set the
    includeGridData parameter to \`true\`. If a field mask is set, the
    \`includeGridData\` parameter is ignored. For large spreadsheets, as a best
    practice, retrieve only the specific spreadsheet fields that you want.

    HTTP: ``POST``  Discovery: ``spreadsheets.getByDataFilter``

    Required parameters:

    * ``spreadsheetId`` (str): The spreadsheet to request.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_get_by_data_filter spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets"],
        "getByDataFilter",
        params=_params or None,
        body=body,
    )


def spreadsheets_developer_metadata_get(spreadsheetId, metadataId, **params):
    """
    Returns the developer metadata with the specified ID. The caller must specify the
    spreadsheet ID and the developer metadata's unique metadataId. For more information,
    see [Read, write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata).

    HTTP: ``GET``  Discovery: ``spreadsheets.developerMetadata.get``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to retrieve metadata from.
    * ``metadataId`` (int): The ID of the developer metadata to retrieve.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_developer_metadata_get spreadsheetId=<str> metadataId=<int>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["metadataId"] = metadataId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "developerMetadata"],
        "get",
        params=_params or None,
    )


def spreadsheets_developer_metadata_search(spreadsheetId, body=None, **params):
    """
    Returns all developer metadata matching the specified DataFilter. For more
    information, see [Read, write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). If
    the provided DataFilter represents a DeveloperMetadataLookup object, this will
    return all DeveloperMetadata entries selected by it. If the DataFilter represents a
    location in a spreadsheet, this will return all developer metadata associated with
    locations intersecting that region.

    HTTP: ``POST``  Discovery: ``spreadsheets.developerMetadata.search``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to retrieve metadata from.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_developer_metadata_search spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "developerMetadata"],
        "search",
        params=_params or None,
        body=body,
    )


def spreadsheets_sheets_copy_to(spreadsheetId, sheetId, body=None, **params):
    """
    Copies a single sheet from a spreadsheet to another spreadsheet. Returns the
    properties of the newly created sheet.

    HTTP: ``POST``  Discovery: ``spreadsheets.sheets.copyTo``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet containing the sheet to copy.
    * ``sheetId`` (int): The ID of the sheet to copy.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_sheets_copy_to spreadsheetId=<str> sheetId=<int>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["sheetId"] = sheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "sheets"],
        "copyTo",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_append(spreadsheetId, range, body=None, **params):
    """
    Appends values to a spreadsheet. The input range is used to search for existing data
    and find a "table" within that range. Values will be appended to the next row of the
    table, starting with the first column of the table. See the [guide](https://develope
    rs.google.com/workspace/sheets/api/guides/values#appending\_values) and [sample code
    ](https://developers.google.com/workspace/sheets/api/samples/writing#append\_values)
    for specific details of how tables are detected and data is appended. The caller
    must specify the spreadsheet ID, range, and a valueInputOption. The
    \`valueInputOption\` only controls how the input data will be added to the sheet
    (column-wise or row-wise), it does not influence what cell the data starts being
    written to.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.append``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.
    * ``range`` (str): The [A1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell) of a range to search for a logical table of data. Values are appended after the last row of the table.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``includeValuesInResponse`` (bool): Determines if the update response should include the values of the cells that were appended. By default, responses do not include the updated values.
    * ``insertDataOption`` (str): How the input data should be inserted.
    * ``responseDateTimeRenderOption`` (str): Determines how dates, times, and durations in the response should be rendered. This is ignored if response\_value\_render\_option is FORMATTED\_VALUE. The default dateTime render option is SERIAL\_NUMBER.
    * ``responseValueRenderOption`` (str): Determines how values in the response should be rendered. The default render option is FORMATTED\_VALUE.
    * ``valueInputOption`` (str): How the input data should be interpreted.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_append spreadsheetId=<str> range=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["range"] = range
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "append",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_batch_clear(spreadsheetId, body=None, **params):
    """
    Clears one or more ranges of values from a spreadsheet. The caller must specify the
    spreadsheet ID and one or more ranges. Only values are cleared -- all other
    properties of the cell (such as formatting and data validation) are kept.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.batchClear``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_clear spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchClear",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_batch_clear_by_data_filter(spreadsheetId, body=None, **params):
    """
    Clears one or more ranges of values from a spreadsheet. For more information, see
    [Read, write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The
    caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching
    any of the specified data filters will be cleared. Only values are cleared -- all
    other properties of the cell (such as formatting, data validation, etc.) are kept.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.batchClearByDataFilter``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_clear_by_data_filter spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchClearByDataFilter",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_batch_get(spreadsheetId, **params):
    """
    Returns one or more ranges of values from a spreadsheet. The caller must specify the
    spreadsheet ID and one or more ranges.

    HTTP: ``GET``  Discovery: ``spreadsheets.values.batchGet``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to retrieve data from.

    Optional parameters (pass via keyword args):

    * ``dateTimeRenderOption`` (str): How dates, times, and durations should be represented in the output. This is ignored if value\_render\_option is FORMATTED\_VALUE. The default dateTime render option is SERIAL\_NUMBER.
    * ``majorDimension`` (str): The major dimension that results should use. For example, if the spreadsheet data is: \`A1=1,B1=2,A2=3,B2=4\`, then requesting \`ranges=["A1:B2"],majorDimension=ROWS\` returns \`[[1,2],[3,4]]\`, whereas re…
    * ``ranges`` (str): The [A1 notation or R1C1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell) of the range to retrieve values from.
    * ``valueRenderOption`` (str): How values should be represented in the output. The default render option is ValueRenderOption.FORMATTED\_VALUE.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_get spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchGet",
        params=_params or None,
    )


def spreadsheets_values_batch_get_by_data_filter(spreadsheetId, body=None, **params):
    """
    Returns one or more ranges of values that match the specified data filters. For more
    information, see [Read, write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The
    caller must specify the spreadsheet ID and one or more DataFilters. Ranges that
    match any of the data filters in the request will be returned.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.batchGetByDataFilter``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to retrieve data from.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_get_by_data_filter spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchGetByDataFilter",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_batch_update(spreadsheetId, body=None, **params):
    """
    Sets values in one or more ranges of a spreadsheet. The caller must specify the
    spreadsheet ID, a valueInputOption, and one or more ValueRanges.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.batchUpdate``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_update spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchUpdate",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_batch_update_by_data_filter(spreadsheetId, body=None, **params):
    """
    Sets values in one or more ranges of a spreadsheet. For more information, see [Read,
    write, and search
    metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The
    caller must specify the spreadsheet ID, a valueInputOption, and one or more
    DataFilterValueRanges.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.batchUpdateByDataFilter``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_batch_update_by_data_filter spreadsheetId=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "batchUpdateByDataFilter",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_clear(spreadsheetId, range, body=None, **params):
    """
    Clears values from a spreadsheet. The caller must specify the spreadsheet ID and
    range. Only values are cleared -- all other properties of the cell (such as
    formatting, data validation, etc..) are kept.

    HTTP: ``POST``  Discovery: ``spreadsheets.values.clear``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.
    * ``range`` (str): The [A1 notation or R1C1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell) of the values to clear.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_clear spreadsheetId=<str> range=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["range"] = range
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "clear",
        params=_params or None,
        body=body,
    )


def spreadsheets_values_get(spreadsheetId, range, **params):
    """
    Returns a range of values from a spreadsheet. The caller must specify the
    spreadsheet ID and a range.

    HTTP: ``GET``  Discovery: ``spreadsheets.values.get``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to retrieve data from.
    * ``range`` (str): The [A1 notation or R1C1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell) of the range to retrieve values from.

    Optional parameters (pass via keyword args):

    * ``dateTimeRenderOption`` (str): How dates, times, and durations should be represented in the output. This is ignored if value\_render\_option is FORMATTED\_VALUE. The default dateTime render option is SERIAL\_NUMBER.
    * ``majorDimension`` (str): The major dimension that results should use. For example, if the spreadsheet data in Sheet1 is: \`A1=1,B1=2,A2=3,B2=4\`, then requesting \`range=Sheet1!A1:B2?majorDimension=ROWS\` returns \`[[1,2],[3,4]]\`…
    * ``valueRenderOption`` (str): How values should be represented in the output. The default render option is FORMATTED\_VALUE.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_get spreadsheetId=<str> range=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["range"] = range
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "get",
        params=_params or None,
    )


def spreadsheets_values_update(spreadsheetId, range, body=None, **params):
    """
    Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID,
    range, and a valueInputOption.

    HTTP: ``PUT``  Discovery: ``spreadsheets.values.update``

    Required parameters:

    * ``spreadsheetId`` (str): The ID of the spreadsheet to update.
    * ``range`` (str): The [A1 notation](https://developers.google.com/workspace/sheets/api/guides/concepts#cell) of the values to update.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``includeValuesInResponse`` (bool): Determines if the update response should include the values of the cells that were updated. By default, responses do not include the updated values. If the range to write was larger than the range ac…
    * ``responseDateTimeRenderOption`` (str): Determines how dates, times, and durations in the response should be rendered. This is ignored if response\_value\_render\_option is FORMATTED\_VALUE. The default dateTime render option is SERIAL\_NUMBER.
    * ``responseValueRenderOption`` (str): Determines how values in the response should be rendered. The default render option is FORMATTED\_VALUE.
    * ``valueInputOption`` (str): How the input data should be interpreted.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.spreadsheets_values_update spreadsheetId=<str> range=<str>
    """
    _params = dict(params)
    _params["spreadsheetId"] = spreadsheetId
    _params["range"] = range
    return _gws.call(
        __opts__,
        __pillar__,
        "sheets",
        ["spreadsheets", "values"],
        "update",
        params=_params or None,
        body=body,
    )


def append(spreadsheet, json_values=None, values=None, test=False):
    """
    [Helper] Append a row to a spreadsheet

    Options:

    * ``spreadsheet`` (required value): Spreadsheet ID
    * ``json_values`` (optional value): JSON array of rows, e.g. '[["a","b"],["c","d"]]'
    * ``values`` (optional value): Comma-separated values (simple strings)

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.append
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "sheets",
        "+append",
        flags={
            "spreadsheet": spreadsheet,
            "json-values": json_values,
            "values": values,
        },
        test=test,
    )


def read(range, spreadsheet, test=False):
    """
    [Helper] Read values from a spreadsheet

    Options:

    * ``range`` (required value): Range to read (e.g. 'Sheet1!A1:B2')
    * ``spreadsheet`` (required value): Spreadsheet ID

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_sheets.read
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "sheets",
        "+read",
        flags={
            "range": range,
            "spreadsheet": spreadsheet,
        },
        test=test,
    )
