# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Filter user-generated content for safety execution module.

Filter user-generated content for safety

This module is generated from the Google Discovery document for ``modelarmor/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_modelarmor"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def create_template(location, project, template_id, json=None, preset=None, test=False):
    """
    [Helper] Create a new Model Armor template

    Options:

    * ``location`` (required value): GCP location (e.g. us-central1)
    * ``project`` (required value): GCP project ID
    * ``template_id`` (required value): Template ID to create
    * ``json`` (optional value): JSON body for the template configuration (overrides --preset)
    * ``preset`` (optional value): Use a preset template: jailbreak [possible values: jailbreak]

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_modelarmor.create_template
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "modelarmor",
        "+create-template",
        flags={
            "location": location,
            "project": project,
            "template-id": template_id,
            "json": json,
            "preset": preset,
        },
        test=test,
    )


def sanitize_prompt(template, json=None, text=None, test=False):
    """
    [Helper] Sanitize a user prompt through a Model Armor template

    Options:

    * ``template`` (required value): Full template resource name (projects/PROJECT/locations/LOCATION/templates/TEMPLATE)
    * ``json`` (optional value): Full JSON request body (overrides --text)
    * ``text`` (optional value): Text content to sanitize

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_modelarmor.sanitize_prompt
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "modelarmor",
        "+sanitize-prompt",
        flags={
            "template": template,
            "json": json,
            "text": text,
        },
        test=test,
    )


def sanitize_response(template, json=None, text=None, test=False):
    """
    [Helper] Sanitize a model response through a Model Armor template

    Options:

    * ``template`` (required value): Full template resource name (projects/PROJECT/locations/LOCATION/templates/TEMPLATE)
    * ``json`` (optional value): Full JSON request body (overrides --text)
    * ``text`` (optional value): Text content to sanitize

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_modelarmor.sanitize_response
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "modelarmor",
        "+sanitize-response",
        flags={
            "template": template,
            "json": json,
            "text": text,
        },
        test=test,
    )
