# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Manage Google Keep notes execution module.

Manage Google Keep notes

This module is generated from the Google Discovery document for ``keep/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_keep"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def media_download(name, **params):
    """
    Gets an attachment. To download attachment media via REST requires the alt=media
    query parameter. Returns a 400 bad request error if attachment media is not
    available in the requested MIME type.

    HTTP: ``GET``  Discovery: ``media.download``

    Required parameters:

    * ``name`` (str): Required. The name of the attachment.

    Optional parameters (pass via keyword args):

    * ``mimeType`` (str): The IANA MIME type format requested. The requested MIME type must be one specified in the attachment.mime\\_type. Required when downloading attachment media and ignored otherwise.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.media_download name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["media"],
        "download",
        params=_params or None,
    )


def notes_create(body=None, **params):
    """
    Creates a new note.

    HTTP: ``POST``  Discovery: ``notes.create``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes"],
        "create",
        params=_params or None,
        body=body,
    )


def notes_delete(name, **params):
    """
    Deletes a note. Caller must have the \\`OWNER\\` role on the note to delete.
    Deleting a note removes the resource immediately and cannot be undone. Any
    collaborators will lose access to the note.

    HTTP: ``DELETE``  Discovery: ``notes.delete``

    Required parameters:

    * ``name`` (str): Required. Name of the note to delete.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_delete name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes"],
        "delete",
        params=_params or None,
    )


def notes_get(name, **params):
    """
    Gets a note.

    HTTP: ``GET``  Discovery: ``notes.get``

    Required parameters:

    * ``name`` (str): Required. Name of the resource.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes"],
        "get",
        params=_params or None,
    )


def notes_list(**params):
    """
    Lists notes. Every list call returns a page of results with \\`page\\_size\\` as the
    upper bound of returned items. A \\`page\\_size\\` of zero allows the server to
    choose the upper bound. The ListNotesResponse contains at most \\`page\\_size\\`
    entries. If there are more things left to list, it provides a
    \\`next\\_page\\_token\\` value. (Page tokens are opaque values.) To get the next
    page of results, copy the result's \\`next\\_page\\_token\\` into the next request's
    \\`page\\_token\\`. Repeat until the \\`next\\_page\\_token\\` returned with a page
    of results is empty. ListNotes return consistent results in the face of concurrent
    changes, or signals that it cannot with an ABORTED error.

    HTTP: ``GET``  Discovery: ``notes.list``

    Optional parameters (pass via keyword args):

    * ``filter`` (str): Filter for list results. If no filter is supplied, the \\`trashed\\` filter is applied by default. Valid fields to filter by are: \\`create\\_time\\`, \\`update\\_time\\`, \\`trash\\_time\\`, and \\`trashed\\`. Filter syntax…
    * ``pageSize`` (int): The maximum number of results to return.
    * ``pageToken`` (str): The previous page's \\`next\\_page\\_token\\` field.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes"],
        "list",
        params=_params or None,
    )


def notes_permissions_batch_create(parent, body=None, **params):
    """
    Creates one or more permissions on the note. Only permissions with the \\`WRITER\\`
    role may be created. If adding any permission fails, then the entire request fails
    and no changes are made.

    HTTP: ``POST``  Discovery: ``notes.permissions.batchCreate``

    Required parameters:

    * ``parent`` (str): The parent resource shared by all Permissions being created. Format: \\`notes/{note}\\` If this is set, the parent field in the CreatePermission messages must either be empty or match this field.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_permissions_batch_create parent=<str>
    """
    _params = dict(params)
    _params["parent"] = parent
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes", "permissions"],
        "batchCreate",
        params=_params or None,
        body=body,
    )


def notes_permissions_batch_delete(parent, body=None, **params):
    """
    Deletes one or more permissions on the note. The specified entities will immediately
    lose access. A permission with the \\`OWNER\\` role can't be removed. If removing a
    permission fails, then the entire request fails and no changes are made. Returns a
    400 bad request error if a specified permission does not exist on the note.

    HTTP: ``POST``  Discovery: ``notes.permissions.batchDelete``

    Required parameters:

    * ``parent`` (str): The parent resource shared by all permissions being deleted. Format: \\`notes/{note}\\` If this is set, the parent of all of the permissions specified in the DeletePermissionRequest messages must match t…

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_keep.notes_permissions_batch_delete parent=<str>
    """
    _params = dict(params)
    _params["parent"] = parent
    return _gws.call(
        __opts__,
        __pillar__,
        "keep",
        ["notes", "permissions"],
        "batchDelete",
        params=_params or None,
        body=body,
    )
