# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Read and write Google Forms execution module.

Read and write Google Forms

This module is generated from the Google Discovery document for ``forms/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_forms"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def forms_batch_update(formId, body=None, **params):
    """
    Change the form with a batch of updates.

    HTTP: ``POST``  Discovery: ``forms.batchUpdate``

    Required parameters:

    * ``formId`` (str): Required. The form ID.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_batch_update formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms"],
        "batchUpdate",
        params=_params or None,
        body=body,
    )


def forms_create(body=None, **params):
    """
    Create a new form using the title given in the provided form message in the request.
    \*Important:\* Only the form.info.title and form.info.document\_title fields are
    copied to the new form. All other fields including the form description, items and
    settings are disallowed. To create a new form and add items, you must first call
    forms.create to create an empty form with a title and (optional) document title, and
    then call forms.update to add the items.

    HTTP: ``POST``  Discovery: ``forms.create``

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``unpublished`` (bool): Optional. Whether the form is unpublished. If set to \`true\`, the form doesn't accept responses. If set to \`false\` or unset, the form is published and accepts responses.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms"],
        "create",
        params=_params or None,
        body=body,
    )


def forms_get(formId, **params):
    """
    Get a form.

    HTTP: ``GET``  Discovery: ``forms.get``

    Required parameters:

    * ``formId`` (str): Required. The form ID.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_get formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms"],
        "get",
        params=_params or None,
    )


def forms_set_publish_settings(formId, body=None, **params):
    """
    Updates the publish settings of a form. Legacy forms aren't supported because they
    don't have the \`publish\_settings\` field.

    HTTP: ``POST``  Discovery: ``forms.setPublishSettings``

    Required parameters:

    * ``formId`` (str): Required. The ID of the form. You can get the id from Form.form\_id field.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_set_publish_settings formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms"],
        "setPublishSettings",
        params=_params or None,
        body=body,
    )


def forms_responses_get(formId, responseId, **params):
    """
    Get one response from the form.

    HTTP: ``GET``  Discovery: ``forms.responses.get``

    Required parameters:

    * ``formId`` (str): Required. The form ID.
    * ``responseId`` (str): Required. The response ID within the form.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_responses_get formId=<str> responseId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    _params["responseId"] = responseId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "responses"],
        "get",
        params=_params or None,
    )


def forms_responses_list(formId, **params):
    """
    List a form's responses.

    HTTP: ``GET``  Discovery: ``forms.responses.list``

    Required parameters:

    * ``formId`` (str): Required. ID of the Form whose responses to list.

    Optional parameters (pass via keyword args):

    * ``filter`` (str): Which form responses to return. Currently, the only supported filters are: \* timestamp > \*N\* which means to get all form responses submitted after (but not at) timestamp \*N\*. \* timestamp >= \*N\* which…
    * ``pageSize`` (int): The maximum number of responses to return. The service may return fewer than this value. If unspecified or zero, at most 5000 responses are returned.
    * ``pageToken`` (str): A page token returned by a previous list response. If this field is set, the form and the values of the filter must be the same as for the original request.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_responses_list formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "responses"],
        "list",
        params=_params or None,
    )


def forms_watches_create(formId, body=None, **params):
    """
    Create a new watch. If a watch ID is provided, it must be unused. For each invoking
    project, the per form limit is one watch per Watch.EventType. A watch expires seven
    days after it is created (see Watch.expire\_time).

    HTTP: ``POST``  Discovery: ``forms.watches.create``

    Required parameters:

    * ``formId`` (str): Required. ID of the Form to watch.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_watches_create formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "watches"],
        "create",
        params=_params or None,
        body=body,
    )


def forms_watches_delete(formId, watchId, **params):
    """
    Delete a watch.

    HTTP: ``DELETE``  Discovery: ``forms.watches.delete``

    Required parameters:

    * ``formId`` (str): Required. The ID of the Form.
    * ``watchId`` (str): Required. The ID of the Watch to delete.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_watches_delete formId=<str> watchId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    _params["watchId"] = watchId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "watches"],
        "delete",
        params=_params or None,
    )


def forms_watches_list(formId, **params):
    """
    Return a list of the watches owned by the invoking project. The maximum number of
    watches is two: For each invoker, the limit is one for each event type per form.

    HTTP: ``GET``  Discovery: ``forms.watches.list``

    Required parameters:

    * ``formId`` (str): Required. ID of the Form whose watches to list.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_watches_list formId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "watches"],
        "list",
        params=_params or None,
    )


def forms_watches_renew(formId, watchId, body=None, **params):
    """
    Renew an existing watch for seven days. The state of the watch after renewal is
    \`ACTIVE\`, and the \`expire\_time\` is seven days from the renewal. Renewing a
    watch in an error state (e.g. \`SUSPENDED\`) succeeds if the error is no longer
    present, but fail otherwise. After a watch has expired, RenewWatch returns
    \`NOT\_FOUND\`.

    HTTP: ``POST``  Discovery: ``forms.watches.renew``

    Required parameters:

    * ``formId`` (str): Required. The ID of the Form.
    * ``watchId`` (str): Required. The ID of the Watch to renew.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_forms.forms_watches_renew formId=<str> watchId=<str>
    """
    _params = dict(params)
    _params["formId"] = formId
    _params["watchId"] = watchId
    return _gws.call(
        __opts__,
        __pillar__,
        "forms",
        ["forms", "watches"],
        "renew",
        params=_params or None,
        body=body,
    )
