# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Manage files, folders, and shared drives execution module.

Manage files, folders, and shared drives

This module is generated from the Google Discovery document for ``drive/v3``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_drive"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def about_get(**params):
    """
    Gets information about the user, the user's Drive, and system capabilities. For more
    information, see [Return user
    info](https://developers.google.com/workspace/drive/api/guides/user-info). Required:
    The \`fields\` parameter must be set. To return the exact fields you need, see
    [Return specific
    fields](https://developers.google.com/workspace/drive/api/guides/fields-parameter).

    HTTP: ``GET``  Discovery: ``about.get``

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.about_get
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["about"],
        "get",
        params=_params or None,
    )


def accessproposals_get(fileId, proposalId, **params):
    """
    Retrieves an access proposal by ID. For more information, see [Manage pending access
    proposals](https://developers.google.com/workspace/drive/api/guides/pending-access).

    HTTP: ``GET``  Discovery: ``accessproposals.get``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the item the request is on.
    * ``proposalId`` (str): Required. The ID of the access proposal to resolve.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.accessproposals_get fileId=<str> proposalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["proposalId"] = proposalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["accessproposals"],
        "get",
        params=_params or None,
    )


def accessproposals_list(fileId, **params):
    """
    List the access proposals on a file. For more information, see [Manage pending
    access proposals](https://developers.google.com/workspace/drive/api/guides/pending-
    access). Note: Only approvers are able to list access proposals on a file. If the
    user isn't an approver, a 403 error is returned.

    HTTP: ``GET``  Discovery: ``accessproposals.list``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the item the request is on.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Optional. The number of results per page.
    * ``pageToken`` (str): Optional. The continuation token on the list of access requests.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.accessproposals_list fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["accessproposals"],
        "list",
        params=_params or None,
    )


def accessproposals_resolve(fileId, proposalId, body=None, **params):
    """
    Approves or denies an access proposal. For more information, see [Manage pending
    access proposals](https://developers.google.com/workspace/drive/api/guides/pending-
    access).

    HTTP: ``POST``  Discovery: ``accessproposals.resolve``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the item the request is on.
    * ``proposalId`` (str): Required. The ID of the access proposal to resolve.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.accessproposals_resolve fileId=<str> proposalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["proposalId"] = proposalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["accessproposals"],
        "resolve",
        params=_params or None,
        body=body,
    )


def approvals_approve(fileId, approvalId, body=None, **params):
    """
    Approves an approval. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals). This
    is used to update the ReviewerResponse of the requesting user with a Response of
    \`APPROVED\`. If this is the last required reviewer response, this also completes
    the approval and sets the approval Status to \`APPROVED\`.

    HTTP: ``POST``  Discovery: ``approvals.approve``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval to approve.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_approve fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "approve",
        params=_params or None,
        body=body,
    )


def approvals_cancel(fileId, approvalId, body=None, **params):
    """
    Cancels an approval. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals).
    Updates the approval Status to \`CANCELLED\`. This can be called by any user with
    the \`writer\` permission on the file while the approval Status is \`IN\_PROGRESS\`.

    HTTP: ``POST``  Discovery: ``approvals.cancel``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval to cancel.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_cancel fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "cancel",
        params=_params or None,
        body=body,
    )


def approvals_comment(fileId, approvalId, body=None, **params):
    """
    Comments on an approval. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals). This
    sends a notification to both the initiator and the reviewers. Additionally, a
    message is also added to the approval activity log.

    HTTP: ``POST``  Discovery: ``approvals.comment``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval to comment on.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_comment fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "comment",
        params=_params or None,
        body=body,
    )


def approvals_decline(fileId, approvalId, body=None, **params):
    """
    Declines an approval. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals). This
    is used to update the ReviewerResponse of the requesting user with a Response of
    \`DECLINED\`. This also completes the approval and sets the approval Status to
    \`DECLINED\`.

    HTTP: ``POST``  Discovery: ``approvals.decline``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval to decline.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_decline fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "decline",
        params=_params or None,
        body=body,
    )


def approvals_get(fileId, approvalId, **params):
    """
    Gets an approval by ID. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals).

    HTTP: ``GET``  Discovery: ``approvals.get``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_get fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "get",
        params=_params or None,
    )


def approvals_list(fileId, **params):
    """
    Lists the approvals on a file. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals).

    HTTP: ``GET``  Discovery: ``approvals.list``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of approvals to return. When not set, at most 100 approvals are returned.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \`nextPageToken\` from a previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_list fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "list",
        params=_params or None,
    )


def approvals_reassign(fileId, approvalId, body=None, **params):
    """
    Reassigns the reviewers on an approval. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals). Adds
    or replaces reviewers in the ReviewerResponse of the approval. This can be called by
    any user with the \`writer\` permission on the file while the approval Status is
    \`IN\_PROGRESS\` and the Response for the reviewer being reassigned is
    \`NO\_RESPONSE\`. A user with the \`reader\` permission can only reassign an
    approval that's assigned to themselves. Removing a reviewer isn't allowed.

    HTTP: ``POST``  Discovery: ``approvals.reassign``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is on.
    * ``approvalId`` (str): Required. The ID of the approval to reassign.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_reassign fileId=<str> approvalId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["approvalId"] = approvalId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "reassign",
        params=_params or None,
        body=body,
    )


def approvals_start(fileId, body=None, **params):
    """
    Starts an approval on a file. For more information, see [Manage
    approvals](https://developers.google.com/workspace/drive/api/guides/approvals).

    HTTP: ``POST``  Discovery: ``approvals.start``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file that the approval is created on.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.approvals_start fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["approvals"],
        "start",
        params=_params or None,
        body=body,
    )


def apps_get(appId, **params):
    """
    Gets a specific app. For more information, see [Return user
    info](https://developers.google.com/workspace/drive/api/guides/user-info).

    HTTP: ``GET``  Discovery: ``apps.get``

    Required parameters:

    * ``appId`` (str): The ID of the app.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.apps_get appId=<str>
    """
    _params = dict(params)
    _params["appId"] = appId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["apps"],
        "get",
        params=_params or None,
    )


def apps_list(**params):
    """
    Lists a user's installed apps. For more information, see [Return user
    info](https://developers.google.com/workspace/drive/api/guides/user-info).

    HTTP: ``GET``  Discovery: ``apps.list``

    Optional parameters (pass via keyword args):

    * ``appFilterExtensions`` (str): A comma-separated list of file extensions to limit returned results. All results within the given app query scope which can open any of the given file extensions are included in the response. If \`app…
    * ``appFilterMimeTypes`` (str): A comma-separated list of file extensions to limit returned results. All results within the given app query scope which can open any of the given MIME types will be included in the response. If \`appF…
    * ``languageCode`` (str): A language or locale code, as defined by BCP 47, with some extensions from Unicode's LDML format (http://www.unicode.org/reports/tr35/).

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.apps_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["apps"],
        "list",
        params=_params or None,
    )


def changes_get_start_page_token(**params):
    """
    Gets the starting pageToken for listing future changes. For more information, see
    [Retrieve changes](https://developers.google.com/workspace/drive/api/guides/manage-
    changes).

    HTTP: ``GET``  Discovery: ``changes.getStartPageToken``

    Optional parameters (pass via keyword args):

    * ``driveId`` (str): The ID of the shared drive for which the starting pageToken for listing future changes from that shared drive will be returned.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``teamDriveId`` (str) *(deprecated)*: Deprecated: Use \`driveId\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.changes_get_start_page_token
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["changes"],
        "getStartPageToken",
        params=_params or None,
    )


def changes_list(pageToken, **params):
    """
    Lists the changes for a user or shared drive. For more information, see [Retrieve
    changes](https://developers.google.com/workspace/drive/api/guides/manage-changes).

    HTTP: ``GET``  Discovery: ``changes.list``

    Required parameters:

    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response or to the response from the getStartPageToken method.

    Optional parameters (pass via keyword args):

    * ``driveId`` (str): The shared drive from which changes will be returned. If specified the change IDs will be reflective of the shared drive; use the combined drive ID and change ID as an identifier.
    * ``includeCorpusRemovals`` (bool): Whether changes should include the file resource if the file is still accessible by the user at the time of the request, even when a file was removed from the list of changes and there will be no fur…
    * ``includeItemsFromAllDrives`` (bool): Whether both My Drive and shared drive items should be included in results.
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only 'published' is supported.
    * ``includeRemoved`` (bool): Whether to include changes indicating that items have been removed from the list of changes, for example by deletion or loss of access.
    * ``includeTeamDriveItems`` (bool) *(deprecated)*: Deprecated: Use \`includeItemsFromAllDrives\` instead.
    * ``pageSize`` (int): The maximum number of changes to return per page.
    * ``restrictToMyDrive`` (bool): Whether to restrict the results to changes inside the My Drive hierarchy. This omits changes to files such as those in the Application Data folder or shared files which have not been added to My Driv…
    * ``spaces`` (str): A comma-separated list of spaces to query within the corpora. Supported values are 'drive' and 'appDataFolder'.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``teamDriveId`` (str) *(deprecated)*: Deprecated: Use \`driveId\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.changes_list pageToken=<str>
    """
    _params = dict(params)
    _params["pageToken"] = pageToken
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["changes"],
        "list",
        params=_params or None,
    )


def changes_watch(pageToken, body=None, **params):
    """
    Subscribes to changes for a user. For more information, see [Notifications for
    resource changes](https://developers.google.com/workspace/drive/api/guides/push).

    HTTP: ``POST``  Discovery: ``changes.watch``

    Required parameters:

    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response or to the response from the getStartPageToken method.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``driveId`` (str): The shared drive from which changes will be returned. If specified the change IDs will be reflective of the shared drive; use the combined drive ID and change ID as an identifier.
    * ``includeCorpusRemovals`` (bool): Whether changes should include the file resource if the file is still accessible by the user at the time of the request, even when a file was removed from the list of changes and there will be no fur…
    * ``includeItemsFromAllDrives`` (bool): Whether both My Drive and shared drive items should be included in results.
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only 'published' is supported.
    * ``includeRemoved`` (bool): Whether to include changes indicating that items have been removed from the list of changes, for example by deletion or loss of access.
    * ``includeTeamDriveItems`` (bool) *(deprecated)*: Deprecated: Use \`includeItemsFromAllDrives\` instead.
    * ``pageSize`` (int): The maximum number of changes to return per page.
    * ``restrictToMyDrive`` (bool): Whether to restrict the results to changes inside the My Drive hierarchy. This omits changes to files such as those in the Application Data folder or shared files which have not been added to My Driv…
    * ``spaces`` (str): A comma-separated list of spaces to query within the corpora. Supported values are 'drive' and 'appDataFolder'.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``teamDriveId`` (str) *(deprecated)*: Deprecated: Use \`driveId\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.changes_watch pageToken=<str>
    """
    _params = dict(params)
    _params["pageToken"] = pageToken
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["changes"],
        "watch",
        params=_params or None,
        body=body,
    )


def channels_stop(body=None, **params):
    """
    Stops watching resources through this channel. For more information, see
    [Notifications for resource
    changes](https://developers.google.com/workspace/drive/api/guides/push).

    HTTP: ``POST``  Discovery: ``channels.stop``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.channels_stop
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["channels"],
        "stop",
        params=_params or None,
        body=body,
    )


def comments_create(fileId, body=None, **params):
    """
    Creates a comment on a file. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).
    Required: The \`fields\` parameter must be set. To return the exact fields you need,
    see [Return specific
    fields](https://developers.google.com/workspace/drive/api/guides/fields-parameter).

    HTTP: ``POST``  Discovery: ``comments.create``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.comments_create fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["comments"],
        "create",
        params=_params or None,
        body=body,
    )


def comments_delete(fileId, commentId, **params):
    """
    Deletes a comment. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``DELETE``  Discovery: ``comments.delete``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.comments_delete fileId=<str> commentId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["comments"],
        "delete",
        params=_params or None,
    )


def comments_get(fileId, commentId, **params):
    """
    Gets a comment by ID. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).
    Required: The \`fields\` parameter must be set. To return the exact fields you need,
    see [Return specific
    fields](https://developers.google.com/workspace/drive/api/guides/fields-parameter).

    HTTP: ``GET``  Discovery: ``comments.get``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.

    Optional parameters (pass via keyword args):

    * ``includeDeleted`` (bool): Whether to return deleted comments. Deleted comments will not include their original content.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.comments_get fileId=<str> commentId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["comments"],
        "get",
        params=_params or None,
    )


def comments_list(fileId, **params):
    """
    Lists a file's comments. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).
    Required: The \`fields\` parameter must be set. To return the exact fields you need,
    see [Return specific
    fields](https://developers.google.com/workspace/drive/api/guides/fields-parameter).

    HTTP: ``GET``  Discovery: ``comments.list``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    Optional parameters (pass via keyword args):

    * ``includeDeleted`` (bool): Whether to include deleted comments. Deleted comments will not include their original content.
    * ``pageSize`` (int): The maximum number of comments to return per page.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response.
    * ``startModifiedTime`` (str): The minimum value of 'modifiedTime' for the result comments (RFC 3339 date-time).

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.comments_list fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["comments"],
        "list",
        params=_params or None,
    )


def comments_update(fileId, commentId, body=None, **params):
    """
    Updates a comment with patch semantics. For more information, see [Manage comments
    and replies](https://developers.google.com/workspace/drive/api/guides/manage-
    comments). Required: The \`fields\` parameter must be set. To return the exact
    fields you need, see [Return specific
    fields](https://developers.google.com/workspace/drive/api/guides/fields-parameter).

    HTTP: ``PATCH``  Discovery: ``comments.update``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.comments_update fileId=<str> commentId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["comments"],
        "update",
        params=_params or None,
        body=body,
    )


def drives_create(requestId, body=None, **params):
    """
    Creates a shared drive. For more information, see [Manage shared
    drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``POST``  Discovery: ``drives.create``

    Required parameters:

    * ``requestId`` (str): Required. An ID, such as a random UUID, which uniquely identifies this user's request for idempotent creation of a shared drive. A repeated request by the same user and with the same request ID will…

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_create requestId=<str>
    """
    _params = dict(params)
    _params["requestId"] = requestId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "create",
        params=_params or None,
        body=body,
    )


def drives_delete(driveId, **params):
    """
    Permanently deletes a shared drive for which the user is an \`organizer\`. The
    shared drive cannot contain any untrashed items. For more information, see [Manage
    shared drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``DELETE``  Discovery: ``drives.delete``

    Required parameters:

    * ``driveId`` (str): The ID of the shared drive.

    Optional parameters (pass via keyword args):

    * ``allowItemDeletion`` (bool): Whether any items inside the shared drive should also be deleted. This option is only supported when \`useDomainAdminAccess\` is also set to \`true\`.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then the requester will be granted access if they are an administrator of the domain to which the shared drive belongs.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_delete driveId=<str>
    """
    _params = dict(params)
    _params["driveId"] = driveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "delete",
        params=_params or None,
    )


def drives_get(driveId, **params):
    """
    Gets a shared drive's metadata by ID. For more information, see [Manage shared
    drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``GET``  Discovery: ``drives.get``

    Required parameters:

    * ``driveId`` (str): The ID of the shared drive.

    Optional parameters (pass via keyword args):

    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then the requester will be granted access if they are an administrator of the domain to which the shared drive belongs.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_get driveId=<str>
    """
    _params = dict(params)
    _params["driveId"] = driveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "get",
        params=_params or None,
    )


def drives_hide(driveId, **params):
    """
    Hides a shared drive from the default view. For more information, see [Manage shared
    drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``POST``  Discovery: ``drives.hide``

    Required parameters:

    * ``driveId`` (str): The ID of the shared drive.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_hide driveId=<str>
    """
    _params = dict(params)
    _params["driveId"] = driveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "hide",
        params=_params or None,
    )


def drives_list(**params):
    """
    Lists the user's shared drives. This method accepts the \`q\` parameter, which is a
    search query combining one or more search terms. For more information, see the
    [Search for shared
    drives](https://developers.google.com/workspace/drive/api/guides/search-
    shareddrives) guide.

    HTTP: ``GET``  Discovery: ``drives.list``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Maximum number of shared drives to return per page.
    * ``pageToken`` (str): Page token for shared drives.
    * ``q`` (str): Query string for searching shared drives.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then all shared drives of the domain in which the requester is an administrator are returned.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "list",
        params=_params or None,
    )


def drives_unhide(driveId, **params):
    """
    Restores a shared drive to the default view. For more information, see [Manage
    shared drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``POST``  Discovery: ``drives.unhide``

    Required parameters:

    * ``driveId`` (str): The ID of the shared drive.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_unhide driveId=<str>
    """
    _params = dict(params)
    _params["driveId"] = driveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "unhide",
        params=_params or None,
    )


def drives_update(driveId, body=None, **params):
    """
    Updates the metadata for a shared drive. For more information, see [Manage shared
    drives](https://developers.google.com/workspace/drive/api/guides/manage-
    shareddrives).

    HTTP: ``PATCH``  Discovery: ``drives.update``

    Required parameters:

    * ``driveId`` (str): The ID of the shared drive.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then the requester will be granted access if they are an administrator of the domain to which the shared drive belongs.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.drives_update driveId=<str>
    """
    _params = dict(params)
    _params["driveId"] = driveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["drives"],
        "update",
        params=_params or None,
        body=body,
    )


def files_copy(fileId, body=None, **params):
    """
    Creates a copy of a file and applies any requested updates with patch semantics. For
    more information, see [Create and manage
    files](https://developers.google.com/workspace/drive/api/guides/create-file).

    HTTP: ``POST``  Discovery: ``files.copy``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: Copying files into multiple folders is no longer supported. Use shortcuts instead.
    * ``ignoreDefaultVisibility`` (bool): Whether to ignore the domain's default visibility settings for the created file. Domain administrators can choose to make all uploaded files visible to the domain by default; this parameter bypasses…
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``keepRevisionForever`` (bool): Whether to set the \`keepForever\` field in the new head revision. This is only applicable to files with binary content in Google Drive. Only 200 revisions for the file can be kept forever. If the limi…
    * ``ocrLanguage`` (str): A language hint for OCR processing during image import (ISO 639-1 code).
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_copy fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "copy",
        params=_params or None,
        body=body,
    )


def files_create(body=None, upload=None, **params):
    """
    Creates a file. For more information, see [Create and manage
    files](https://developers.google.com/workspace/drive/api/guides/create-file). This
    method supports an \*/upload\* URI and accepts uploaded media with the following
    characteristics: - \*Maximum file size:\* 5,120 GB - \*Accepted Media MIME types:\*
    \`\*/\*\` (Specify a valid MIME type, rather than the literal \`\*/\*\` value. The
    literal \`\*/\*\` is only used to indicate that any valid MIME type can be uploaded.
    For more information, see [Google Workspace and Google Drive supported MIME
    types](https://developers.google.com/workspace/drive/api/guides/mime-types).) For
    more information on uploading files, see [Upload file
    data](https://developers.google.com/workspace/drive/api/guides/manage-uploads). Apps
    creating shortcuts with the \`create\` method must specify the MIME type
    \`application/vnd.google-apps.shortcut\`. Apps should specify a file extension in
    the \`name\` property when inserting files with the API. For example, an operation
    to insert a JPEG file should specify something like \`"name": "cat.jpg"\` in the
    metadata. Subsequent \`GET\` requests include the read-only \`fileExtension\`
    property populated with the extension originally specified in the \`name\` property.
    When a Google Drive user requests to download a file, or when the file is downloaded
    through the sync client, Drive builds a full filename (with extension) based on the
    name. In cases where the extension is missing, Drive attempts to determine the
    extension based on the file's MIME type.

    HTTP: ``POST``  Discovery: ``files.create``

    * ``body`` (dict): request body payload.

    * ``upload`` (str): local path of a file to upload as media content.

    Optional parameters (pass via keyword args):

    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: Creating files in multiple folders is no longer supported.
    * ``ignoreDefaultVisibility`` (bool): Whether to ignore the domain's default visibility settings for the created file. Domain administrators can choose to make all uploaded files visible to the domain by default; this parameter bypasses…
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``keepRevisionForever`` (bool): Whether to set the \`keepForever\` field in the new head revision. This is only applicable to files with binary content in Google Drive. Only 200 revisions for the file can be kept forever. If the limi…
    * ``ocrLanguage`` (str): A language hint for OCR processing during image import (ISO 639-1 code).
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``useContentAsIndexableText`` (bool): Whether to use the uploaded content as indexable text.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "create",
        params=_params or None,
        body=body,
        upload=upload,
    )


def files_delete(fileId, **params):
    """
    Permanently deletes a file owned by the user without moving it to the trash. For
    more information, see [Trash or delete files and
    folders](https://developers.google.com/workspace/drive/api/guides/delete). If the
    file belongs to a shared drive, the user must be an \`organizer\` on the parent
    folder. If the target is a folder, all descendants owned by the user are also
    deleted.

    HTTP: ``DELETE``  Discovery: ``files.delete``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    Optional parameters (pass via keyword args):

    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: If an item isn't in a shared drive and its last parent is deleted but the item itself isn't, the item will be placed under its owner's root.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_delete fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "delete",
        params=_params or None,
    )


def files_download(fileId, **params):
    """
    Downloads the content of a file. For more information, see [Download and export
    files](https://developers.google.com/workspace/drive/api/guides/manage-downloads).
    Operations are valid for 24 hours from the time of creation.

    HTTP: ``POST``  Discovery: ``files.download``

    Required parameters:

    * ``fileId`` (str): Required. The ID of the file to download.

    Optional parameters (pass via keyword args):

    * ``mimeType`` (str): Optional. The MIME type the file should be downloaded as. This field can only be set when downloading Google Workspace documents. For a list of supported MIME types, see [Export MIME types for Google…
    * ``revisionId`` (str): Optional. The revision ID of the file to download. This field can only be set when downloading blob files, Google Docs, and Google Sheets. Returns \`INVALID\_ARGUMENT\` if downloading a specific revisio…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_download fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "download",
        params=_params or None,
    )


def files_empty_trash(**params):
    """
    Permanently deletes all of the user's trashed files. For more information, see
    [Trash or delete files and
    folders](https://developers.google.com/workspace/drive/api/guides/delete).

    HTTP: ``DELETE``  Discovery: ``files.emptyTrash``

    Optional parameters (pass via keyword args):

    * ``driveId`` (str): If set, empties the trash of the provided shared drive.
    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: If an item isn't in a shared drive and its last parent is deleted but the item itself isn't, the item will be placed under its owner's root.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_empty_trash
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "emptyTrash",
        params=_params or None,
    )


def files_export(fileId, mimeType, **params):
    """
    Exports a Google Workspace document to the requested MIME type and returns exported
    byte content. For more information, see [Download and export
    files](https://developers.google.com/workspace/drive/api/guides/manage-downloads).
    Note that the exported content is limited to 10 MB.

    HTTP: ``GET``  Discovery: ``files.export``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``mimeType`` (str): Required. The MIME type of the format requested for this export. For a list of supported MIME types, see [Export MIME types for Google Workspace documents](/workspace/drive/api/guides/ref-export-form…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_export fileId=<str> mimeType=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["mimeType"] = mimeType
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "export",
        params=_params or None,
    )


def files_generate_cse_token(**params):
    """
    Generates a CSE token which can be used to create or update CSE files.

    HTTP: ``GET``  Discovery: ``files.generateCseToken``

    Optional parameters (pass via keyword args):

    * ``fileId`` (str): The ID of the file for which the JWT should be generated. If not provided, an id will be generated.
    * ``parent`` (str): The ID of the expected parent of the file. Used when generating a JWT for a new CSE file. If specified, the parent will be fetched, and if the parent is a shared drive item, the shared drive's policy…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_generate_cse_token
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "generateCseToken",
        params=_params or None,
    )


def files_generate_ids(**params):
    """
    Generates a set of file IDs which can be provided in create or copy requests. For
    more information, see [Create and manage
    files](https://developers.google.com/workspace/drive/api/guides/create-file).

    HTTP: ``GET``  Discovery: ``files.generateIds``

    Optional parameters (pass via keyword args):

    * ``count`` (int): The number of IDs to return.
    * ``space`` (str): The space in which the IDs can be used to create files. Supported values are \`drive\` and \`appDataFolder\`. (Default: \`drive\`.) For more information, see [File organization](https://developers.google.c…
    * ``type`` (str): The type of items which the IDs can be used for. Supported values are \`files\` and \`shortcuts\`. Note that \`shortcuts\` are only supported in the \`drive\` \`space\`. (Default: \`files\`.) For more informatio…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_generate_ids
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "generateIds",
        params=_params or None,
    )


def files_get(fileId, **params):
    """
    Gets a file's metadata or content by ID. For more information, see [Search for files
    and folders](https://developers.google.com/workspace/drive/api/guides/search-files).
    If you provide the URL parameter \`alt=media\`, then the response includes the file
    contents in the response body. Downloading content with \`alt=media\` only works if
    the file is stored in Drive. To download Google Docs, Sheets, and Slides use [\`file
    s.export\`](https://developers.google.com/workspace/drive/api/reference/rest/v3/file
    s/export) instead. For more information, see [Download and export
    files](https://developers.google.com/workspace/drive/api/guides/manage-downloads).

    HTTP: ``GET``  Discovery: ``files.get``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    Optional parameters (pass via keyword args):

    * ``acknowledgeAbuse`` (bool): Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when the \`alt\` parameter is set to \`media\` and the user is the owner of the fil…
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_get fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "get",
        params=_params or None,
    )


def files_list(**params):
    """
    Lists the user's files. For more information, see [Search for files and
    folders](https://developers.google.com/workspace/drive/api/guides/search-files).
    This method accepts the \`q\` parameter, which is a search query combining one or
    more search terms. This method returns \*all\* files by default, including trashed
    files. If you don't want trashed files to appear in the list, use the
    \`trashed=false\` query parameter to remove trashed files from the results.

    HTTP: ``GET``  Discovery: ``files.list``

    Optional parameters (pass via keyword args):

    * ``corpora`` (str): Specifies a collection of items (files or documents) to which the query applies. Supported items include: \* \`user\` \* \`domain\` \* \`drive\` \* \`allDrives\` Prefer \`user\` or \`drive\` to \`allDrives\` for effic…
    * ``corpus`` (str) *(deprecated)*: Deprecated: The source of files to list. Use \`corpora\` instead.
    * ``driveId`` (str): ID of the shared drive to search.
    * ``includeItemsFromAllDrives`` (bool): Whether both My Drive and shared drive items should be included in results.
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``includeTeamDriveItems`` (bool) *(deprecated)*: Deprecated: Use \`includeItemsFromAllDrives\` instead.
    * ``orderBy`` (str): A comma-separated list of sort keys. Valid keys are: \* \`createdTime\`: When the file was created. Avoid using this key for queries on large item collections as it might result in timeouts or other iss…
    * ``pageSize`` (int): The maximum number of files to return per page. Pages may be partial or empty even before reaching the end of the file list. If unspecified, at most 100 files are returned for shared drives, and the…
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \`nextPageToken\` from the previous response.
    * ``q`` (str): A query for filtering the file results. For supported syntax, see [Search for files and folders](/workspace/drive/api/guides/search-files).
    * ``spaces`` (str): A comma-separated list of spaces to query within the corpora. Supported values are \`drive\` and \`appDataFolder\`. For more information, see [File organization](https://developers.google.com/workspace/d…
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``teamDriveId`` (str) *(deprecated)*: Deprecated: Use \`driveId\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "list",
        params=_params or None,
    )


def files_list_labels(fileId, **params):
    """
    Lists the labels on a file. For more information, see [List labels on a
    file](https://developers.google.com/workspace/drive/api/guides/list-labels).

    HTTP: ``GET``  Discovery: ``files.listLabels``

    Required parameters:

    * ``fileId`` (str): The ID for the file.

    Optional parameters (pass via keyword args):

    * ``maxResults`` (int): The maximum number of labels to return per page. When not set, defaults to 100.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \`nextPageToken\` from the previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_list_labels fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "listLabels",
        params=_params or None,
    )


def files_modify_labels(fileId, body=None, **params):
    """
    Modifies the set of labels applied to a file. For more information, see [Set a label
    field on a file](https://developers.google.com/workspace/drive/api/guides/set-
    label). Returns a list of the labels that were added or modified.

    HTTP: ``POST``  Discovery: ``files.modifyLabels``

    Required parameters:

    * ``fileId`` (str): The ID of the file to which the labels belong.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_modify_labels fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "modifyLabels",
        params=_params or None,
        body=body,
    )


def files_update(fileId, body=None, upload=None, **params):
    """
    Updates a file's metadata, content, or both. When calling this method, only populate
    fields in the request that you want to modify. When updating fields, some fields
    might be changed automatically, such as \`modifiedDate\`. This method supports patch
    semantics. This method supports an \*/upload\* URI and accepts uploaded media with
    the following characteristics: - \*Maximum file size:\* 5,120 GB - \*Accepted Media
    MIME types:\* \`\*/\*\` (Specify a valid MIME type, rather than the literal
    \`\*/\*\` value. The literal \`\*/\*\` is only used to indicate that any valid MIME
    type can be uploaded. For more information, see [Google Workspace and Google Drive
    supported MIME types](https://developers.google.com/workspace/drive/api/guides/mime-
    types).) For more information on uploading files, see [Upload file
    data](https://developers.google.com/workspace/drive/api/guides/manage-uploads).

    HTTP: ``PATCH``  Discovery: ``files.update``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    * ``body`` (dict): request body payload.

    * ``upload`` (str): local path of a file to upload as media content.

    Optional parameters (pass via keyword args):

    * ``addParents`` (str): A comma-separated list of parent IDs to add.
    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: Adding files to multiple folders is no longer supported. Use shortcuts instead.
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``keepRevisionForever`` (bool): Whether to set the \`keepForever\` field in the new head revision. This is only applicable to files with binary content in Google Drive. Only 200 revisions for the file can be kept forever. If the limi…
    * ``ocrLanguage`` (str): A language hint for OCR processing during image import (ISO 639-1 code).
    * ``removeParents`` (str): A comma-separated list of parent IDs to remove.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``useContentAsIndexableText`` (bool): Whether to use the uploaded content as indexable text.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_update fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "update",
        params=_params or None,
        body=body,
        upload=upload,
    )


def files_watch(fileId, body=None, **params):
    """
    Subscribes to changes to a file. For more information, see [Notifications for
    resource changes](https://developers.google.com/workspace/drive/api/guides/push).

    HTTP: ``POST``  Discovery: ``files.watch``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``acknowledgeAbuse`` (bool): Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when the \`alt\` parameter is set to \`media\` and the user is the owner of the fil…
    * ``includeLabels`` (str): A comma-separated list of IDs of labels to include in the \`labelInfo\` part of the response.
    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.files_watch fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["files"],
        "watch",
        params=_params or None,
        body=body,
    )


def operations_get(name, **params):
    """
    Gets the latest state of a long-running operation. Clients can use this method to
    poll the operation result at intervals as recommended by the API service.

    HTTP: ``GET``  Discovery: ``operations.get``

    Required parameters:

    * ``name`` (str): The name of the operation resource.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.operations_get name=<str>
    """
    _params = dict(params)
    _params["name"] = name
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["operations"],
        "get",
        params=_params or None,
    )


def permissions_create(fileId, body=None, **params):
    """
    Creates a permission for a file or shared drive. For more information, see [Share
    files, folders, and
    drives](https://developers.google.com/workspace/drive/api/guides/manage-sharing).
    \*\*Warning:\*\* Concurrent permissions operations on the same file aren't
    supported; only the last update is applied.

    HTTP: ``POST``  Discovery: ``permissions.create``

    Required parameters:

    * ``fileId`` (str): The ID of the file or shared drive.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``emailMessage`` (str): A plain text custom message to include in the notification email.
    * ``enforceExpansiveAccess`` (bool) *(deprecated)*: Deprecated: All requests use the expansive access rules.
    * ``enforceSingleParent`` (bool) *(deprecated)*: Deprecated: See \`moveToNewOwnersRoot\` for details.
    * ``moveToNewOwnersRoot`` (bool): This parameter only takes effect if the item isn't in a shared drive and the request is attempting to transfer the ownership of the item. If set to \`true\`, the item is moved to the new owner's My Dri…
    * ``sendNotificationEmail`` (bool): Whether to send a notification email when sharing to users or groups. This defaults to \`true\` for users and groups, and is not allowed for other requests. It must not be disabled for ownership transf…
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``transferOwnership`` (bool): Whether to transfer ownership to the specified user and downgrade the current owner to a writer. This parameter is required as an acknowledgement of the side effect. For more information, see [Transf…
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator. If set to \`true\`, and if the following additional conditions are met, the requester is granted access: 1. The file ID parameter refers to a shared drive.…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.permissions_create fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["permissions"],
        "create",
        params=_params or None,
        body=body,
    )


def permissions_delete(fileId, permissionId, **params):
    """
    Deletes a permission. For more information, see [Share files, folders, and
    drives](https://developers.google.com/workspace/drive/api/guides/manage-sharing).
    \*\*Warning:\*\* Concurrent permissions operations on the same file aren't
    supported; only the last update is applied.

    HTTP: ``DELETE``  Discovery: ``permissions.delete``

    Required parameters:

    * ``fileId`` (str): The ID of the file or shared drive.
    * ``permissionId`` (str): The ID of the permission.

    Optional parameters (pass via keyword args):

    * ``enforceExpansiveAccess`` (bool) *(deprecated)*: Deprecated: All requests use the expansive access rules.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator. If set to \`true\`, and if the following additional conditions are met, the requester is granted access: 1. The file ID parameter refers to a shared drive.…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.permissions_delete fileId=<str> permissionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["permissionId"] = permissionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["permissions"],
        "delete",
        params=_params or None,
    )


def permissions_get(fileId, permissionId, **params):
    """
    Gets a permission by ID. For more information, see [Share files, folders, and
    drives](https://developers.google.com/workspace/drive/api/guides/manage-sharing).

    HTTP: ``GET``  Discovery: ``permissions.get``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``permissionId`` (str): The ID of the permission.

    Optional parameters (pass via keyword args):

    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator. If set to \`true\`, and if the following additional conditions are met, the requester is granted access: 1. The file ID parameter refers to a shared drive.…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.permissions_get fileId=<str> permissionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["permissionId"] = permissionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["permissions"],
        "get",
        params=_params or None,
    )


def permissions_list(fileId, **params):
    """
    Lists a file's or shared drive's permissions. For more information, see [Share
    files, folders, and
    drives](https://developers.google.com/workspace/drive/api/guides/manage-sharing).

    HTTP: ``GET``  Discovery: ``permissions.list``

    Required parameters:

    * ``fileId`` (str): The ID of the file or shared drive.

    Optional parameters (pass via keyword args):

    * ``includePermissionsForView`` (str): Specifies which additional view's permissions to include in the response. Only \`published\` is supported.
    * ``pageSize`` (int): The maximum number of permissions to return per page. When not set for files in a shared drive, at most 100 results will be returned. When not set for files that are not in a shared drive, the entire…
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \`nextPageToken\` from the previous response.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator. If set to \`true\`, and if the following additional conditions are met, the requester is granted access: 1. The file ID parameter refers to a shared drive.…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.permissions_list fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["permissions"],
        "list",
        params=_params or None,
    )


def permissions_update(fileId, permissionId, body=None, **params):
    """
    Updates a permission with patch semantics. For more information, see [Share files,
    folders, and
    drives](https://developers.google.com/workspace/drive/api/guides/manage-sharing).
    \*\*Warning:\*\* Concurrent permissions operations on the same file aren't
    supported; only the last update is applied.

    HTTP: ``PATCH``  Discovery: ``permissions.update``

    Required parameters:

    * ``fileId`` (str): The ID of the file or shared drive.
    * ``permissionId`` (str): The ID of the permission.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``enforceExpansiveAccess`` (bool) *(deprecated)*: Deprecated: All requests use the expansive access rules.
    * ``removeExpiration`` (bool): Whether to remove the expiration date.
    * ``supportsAllDrives`` (bool): Whether the requesting application supports both My Drives and shared drives.
    * ``supportsTeamDrives`` (bool) *(deprecated)*: Deprecated: Use \`supportsAllDrives\` instead.
    * ``transferOwnership`` (bool): Whether to transfer ownership to the specified user and downgrade the current owner to a writer. This parameter is required as an acknowledgement of the side effect. For more information, see [Transf…
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator. If set to \`true\`, and if the following additional conditions are met, the requester is granted access: 1. The file ID parameter refers to a shared drive.…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.permissions_update fileId=<str> permissionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["permissionId"] = permissionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["permissions"],
        "update",
        params=_params or None,
        body=body,
    )


def replies_create(fileId, commentId, body=None, **params):
    """
    Creates a reply to a comment. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``POST``  Discovery: ``replies.create``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.replies_create fileId=<str> commentId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["replies"],
        "create",
        params=_params or None,
        body=body,
    )


def replies_delete(fileId, commentId, replyId, **params):
    """
    Deletes a reply. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``DELETE``  Discovery: ``replies.delete``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.
    * ``replyId`` (str): The ID of the reply.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.replies_delete fileId=<str> commentId=<str> replyId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    _params["replyId"] = replyId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["replies"],
        "delete",
        params=_params or None,
    )


def replies_get(fileId, commentId, replyId, **params):
    """
    Gets a reply by ID. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``GET``  Discovery: ``replies.get``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.
    * ``replyId`` (str): The ID of the reply.

    Optional parameters (pass via keyword args):

    * ``includeDeleted`` (bool): Whether to return deleted replies. Deleted replies don't include their original content.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.replies_get fileId=<str> commentId=<str> replyId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    _params["replyId"] = replyId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["replies"],
        "get",
        params=_params or None,
    )


def replies_list(fileId, commentId, **params):
    """
    Lists a comment's replies. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``GET``  Discovery: ``replies.list``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.

    Optional parameters (pass via keyword args):

    * ``includeDeleted`` (bool): Whether to include deleted replies. Deleted replies don't include their original content.
    * ``pageSize`` (int): The maximum number of replies to return per page.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of \`nextPageToken\` from the previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.replies_list fileId=<str> commentId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["replies"],
        "list",
        params=_params or None,
    )


def replies_update(fileId, commentId, replyId, body=None, **params):
    """
    Updates a reply with patch semantics. For more information, see [Manage comments and
    replies](https://developers.google.com/workspace/drive/api/guides/manage-comments).

    HTTP: ``PATCH``  Discovery: ``replies.update``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``commentId`` (str): The ID of the comment.
    * ``replyId`` (str): The ID of the reply.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.replies_update fileId=<str> commentId=<str> replyId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["commentId"] = commentId
    _params["replyId"] = replyId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["replies"],
        "update",
        params=_params or None,
        body=body,
    )


def revisions_delete(fileId, revisionId, **params):
    """
    Permanently deletes a file version. You can only delete revisions for files with
    binary content in Google Drive, like images or videos. Revisions for other files,
    like Google Docs or Sheets, and the last remaining file version can't be deleted.
    For more information, see [Manage file
    revisions](https://developers.google.com/drive/api/guides/manage-revisions).

    HTTP: ``DELETE``  Discovery: ``revisions.delete``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``revisionId`` (str): The ID of the revision.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.revisions_delete fileId=<str> revisionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["revisionId"] = revisionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["revisions"],
        "delete",
        params=_params or None,
    )


def revisions_get(fileId, revisionId, **params):
    """
    Gets a revision's metadata or content by ID. For more information, see [Manage file
    revisions](https://developers.google.com/workspace/drive/api/guides/manage-
    revisions).

    HTTP: ``GET``  Discovery: ``revisions.get``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``revisionId`` (str): The ID of the revision.

    Optional parameters (pass via keyword args):

    * ``acknowledgeAbuse`` (bool): Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when the \`alt\` parameter is set to \`media\` and the user is the owner of the fil…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.revisions_get fileId=<str> revisionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["revisionId"] = revisionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["revisions"],
        "get",
        params=_params or None,
    )


def revisions_list(fileId, **params):
    """
    Lists a file's revisions. For more information, see [Manage file
    revisions](https://developers.google.com/workspace/drive/api/guides/manage-
    revisions). \*\*Important:\*\* The list of revisions returned by this method might
    be incomplete for files with a large revision history, including frequently edited
    Google Docs, Sheets, and Slides. Older revisions might be omitted from the response,
    meaning the first revision returned may not be the oldest existing revision. The
    revision history visible in the Workspace editor user interface might be more
    complete than the list returned by the API.

    HTTP: ``GET``  Discovery: ``revisions.list``

    Required parameters:

    * ``fileId`` (str): The ID of the file.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): The maximum number of revisions to return per page.
    * ``pageToken`` (str): The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.revisions_list fileId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["revisions"],
        "list",
        params=_params or None,
    )


def revisions_update(fileId, revisionId, body=None, **params):
    """
    Updates a revision with patch semantics. For more information, see [Manage file
    revisions](https://developers.google.com/workspace/drive/api/guides/manage-
    revisions).

    HTTP: ``PATCH``  Discovery: ``revisions.update``

    Required parameters:

    * ``fileId`` (str): The ID of the file.
    * ``revisionId`` (str): The ID of the revision.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.revisions_update fileId=<str> revisionId=<str>
    """
    _params = dict(params)
    _params["fileId"] = fileId
    _params["revisionId"] = revisionId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["revisions"],
        "update",
        params=_params or None,
        body=body,
    )


def teamdrives_create(requestId, body=None, **params):
    """
    Deprecated: Use \`drives.create\` instead.

    HTTP: ``POST``  Discovery: ``teamdrives.create``

    Required parameters:

    * ``requestId`` (str): Required. An ID, such as a random UUID, which uniquely identifies this user's request for idempotent creation of a Team Drive. A repeated request by the same user and with the same request ID will av…

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.teamdrives_create requestId=<str>
    """
    _params = dict(params)
    _params["requestId"] = requestId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["teamdrives"],
        "create",
        params=_params or None,
        body=body,
    )


def teamdrives_delete(teamDriveId, **params):
    """
    Deprecated: Use \`drives.delete\` instead.

    HTTP: ``DELETE``  Discovery: ``teamdrives.delete``

    Required parameters:

    * ``teamDriveId`` (str): The ID of the Team Drive

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.teamdrives_delete teamDriveId=<str>
    """
    _params = dict(params)
    _params["teamDriveId"] = teamDriveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["teamdrives"],
        "delete",
        params=_params or None,
    )


def teamdrives_get(teamDriveId, **params):
    """
    Deprecated: Use \`drives.get\` instead.

    HTTP: ``GET``  Discovery: ``teamdrives.get``

    Required parameters:

    * ``teamDriveId`` (str): The ID of the Team Drive

    Optional parameters (pass via keyword args):

    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then the requester will be granted access if they are an administrator of the domain to which the Team Drive belongs.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.teamdrives_get teamDriveId=<str>
    """
    _params = dict(params)
    _params["teamDriveId"] = teamDriveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["teamdrives"],
        "get",
        params=_params or None,
    )


def teamdrives_list(**params):
    """
    Deprecated: Use \`drives.list\` instead.

    HTTP: ``GET``  Discovery: ``teamdrives.list``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Maximum number of Team Drives to return.
    * ``pageToken`` (str): Page token for Team Drives.
    * ``q`` (str): Query string for searching Team Drives.
    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then all Team Drives of the domain in which the requester is an administrator are returned.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.teamdrives_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["teamdrives"],
        "list",
        params=_params or None,
    )


def teamdrives_update(teamDriveId, body=None, **params):
    """
    Deprecated: Use \`drives.update\` instead.

    HTTP: ``PATCH``  Discovery: ``teamdrives.update``

    Required parameters:

    * ``teamDriveId`` (str): The ID of the Team Drive

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``useDomainAdminAccess`` (bool): Issue the request as a domain administrator; if set to true, then the requester will be granted access if they are an administrator of the domain to which the Team Drive belongs.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.teamdrives_update teamDriveId=<str>
    """
    _params = dict(params)
    _params["teamDriveId"] = teamDriveId
    return _gws.call(
        __opts__,
        __pillar__,
        "drive",
        ["teamdrives"],
        "update",
        params=_params or None,
        body=body,
    )


def upload(file, name=None, parent=None, test=False):
    """
    [Helper] Upload a file with automatic metadata

    Positional arguments:

    * ``file`` (required): Path to file to upload

    Options:

    * ``name`` (optional value): Target filename (defaults to source filename)
    * ``parent`` (optional value): Parent folder ID

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_drive.upload
    """
    return _gws.run_helper(
        __opts__,
        __pillar__,
        "drive",
        "+upload",
        positionals=[file],
        flags={
            "name": name,
            "parent": parent,
        },
        test=test,
    )
