# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Read and write presentations execution module.

Read and write presentations

This module is generated from the Google Discovery document for ``slides/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_slides"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def presentations_batch_update(presentationId, body=None, **params):
    """
    Applies one or more updates to the presentation. Each request is validated before
    being applied. If any request is not valid, then the entire request will fail and
    nothing will be applied. Some requests have replies to give you some information
    about how they are applied. Other requests do not need to return information; these
    each return an empty reply. The order of replies matches that of the requests. For
    example, suppose you call batchUpdate with four updates, and only the third one
    returns information. The response would have two empty replies: the reply to the
    third request, and another empty reply, in that order. Because other users may be
    editing the presentation, the presentation might not exactly reflect your changes:
    your changes may be altered with respect to collaborator changes. If there are no
    collaborators, the presentation should reflect your changes. In any case, the
    updates in your request are guaranteed to be applied together atomically.

    HTTP: ``POST``  Discovery: ``presentations.batchUpdate``

    Required parameters:

    * ``presentationId`` (str): The presentation to apply the updates to.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_slides.presentations_batch_update presentationId=<str>
    """
    _params = dict(params)
    _params["presentationId"] = presentationId
    return _gws.call(
        __opts__,
        __pillar__,
        "slides",
        ["presentations"],
        "batchUpdate",
        params=_params or None,
        body=body,
    )


def presentations_create(body=None, **params):
    """
    Creates a blank presentation using the title given in the request. If a
    \`presentationId\` is provided, it is used as the ID of the new presentation.
    Otherwise, a new ID is generated. Other fields in the request, including any
    provided content, are ignored. Returns the created presentation.

    HTTP: ``POST``  Discovery: ``presentations.create``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_slides.presentations_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "slides",
        ["presentations"],
        "create",
        params=_params or None,
        body=body,
    )


def presentations_get(presentationId, **params):
    """
    Gets the latest version of the specified presentation.

    HTTP: ``GET``  Discovery: ``presentations.get``

    Required parameters:

    * ``presentationId`` (str): The ID of the presentation to retrieve.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_slides.presentations_get presentationId=<str>
    """
    _params = dict(params)
    _params["presentationId"] = presentationId
    return _gws.call(
        __opts__,
        __pillar__,
        "slides",
        ["presentations"],
        "get",
        params=_params or None,
    )


def presentations_pages_get(presentationId, pageObjectId, **params):
    """
    Gets the latest version of the specified page in the presentation.

    HTTP: ``GET``  Discovery: ``presentations.pages.get``

    Required parameters:

    * ``presentationId`` (str): The ID of the presentation to retrieve.
    * ``pageObjectId`` (str): The object ID of the page to retrieve.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_slides.presentations_pages_get presentationId=<str> pageObjectId=<str>
    """
    _params = dict(params)
    _params["presentationId"] = presentationId
    _params["pageObjectId"] = pageObjectId
    return _gws.call(
        __opts__,
        __pillar__,
        "slides",
        ["presentations", "pages"],
        "get",
        params=_params or None,
    )


def presentations_pages_get_thumbnail(presentationId, pageObjectId, **params):
    """
    Generates a thumbnail of the latest version of the specified page in the
    presentation and returns a URL to the thumbnail image. This request counts as an
    [expensive read request](https://developers.google.com/workspace/slides/limits) for
    quota purposes.

    HTTP: ``GET``  Discovery: ``presentations.pages.getThumbnail``

    Required parameters:

    * ``presentationId`` (str): The ID of the presentation to retrieve.
    * ``pageObjectId`` (str): The object ID of the page whose thumbnail to retrieve.

    Optional parameters (pass via keyword args):

    * ``thumbnailProperties.mimeType`` (str): The optional mime type of the thumbnail image. If you don't specify the mime type, the mime type defaults to PNG.
    * ``thumbnailProperties.thumbnailSize`` (str): The optional thumbnail image size. If you don't specify the size, the server chooses a default size of the image.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_slides.presentations_pages_get_thumbnail presentationId=<str> pageObjectId=<str>
    """
    _params = dict(params)
    _params["presentationId"] = presentationId
    _params["pageObjectId"] = pageObjectId
    return _gws.call(
        __opts__,
        __pillar__,
        "slides",
        ["presentations", "pages"],
        "getThumbnail",
        params=_params or None,
    )
