# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# Parameter names mirror the Google API reference verbatim (often camelCase); long Discovery
# descriptions and URLs live in the docstrings.
# pylint: disable=invalid-name,line-too-long,redefined-builtin,redefined-outer-name,too-many-lines
"""
Manage contacts and profiles execution module.

Manage contacts and profiles

This module is generated from the Google Discovery document for ``people/v1``
and drives the bundled ``gws`` CLI. Parameter names match the Google API reference verbatim;
optional parameters are passed through ``**params``.
"""

import logging

from saltext.gsuite import _binary
from saltext.gsuite import _gws

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_people"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (
            False,
            "The 'gws' binary is not available; install the platform-specific "
            "saltext.gsuite wheel or set gsuite:binary_path.",
        )
    return __virtualname__


def contact_groups_batch_get(**params):
    """
    Get a list of contact groups owned by the authenticated user by specifying a list of
    contact group resource names.

    HTTP: ``GET``  Discovery: ``contactGroups.batchGet``

    Optional parameters (pass via keyword args):

    * ``groupFields`` (str): Optional. A field mask to restrict which fields on the group are returned. Defaults to \`metadata\`, \`groupType\`, \`memberCount\`, and \`name\` if not set or set to empty. Valid fields are: \* clientData \*…
    * ``maxMembers`` (int): Optional. Specifies the maximum number of members to return for each group. Defaults to 0 if not set, which will return zero members.
    * ``resourceNames`` (str): Required. The resource names of the contact groups to get. There is a maximum of 200 resource names.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_batch_get
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "batchGet",
        params=_params or None,
    )


def contact_groups_create(body=None, **params):
    """
    Create a new contact group owned by the authenticated user. Created contact group
    names must be unique to the users contact groups. Attempting to create a group with
    a duplicate name will return a HTTP 409 error. Mutate requests for the same user
    should be sent sequentially to avoid increased latency and failures.

    HTTP: ``POST``  Discovery: ``contactGroups.create``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_create
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "create",
        params=_params or None,
        body=body,
    )


def contact_groups_delete(resourceName, **params):
    """
    Delete an existing contact group owned by the authenticated user by specifying a
    contact group resource name. Mutate requests for the same user should be sent
    sequentially to avoid increased latency and failures.

    HTTP: ``DELETE``  Discovery: ``contactGroups.delete``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the contact group to delete.

    Optional parameters (pass via keyword args):

    * ``deleteContacts`` (bool): Optional. Set to true to also delete the contacts in the specified group.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_delete resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "delete",
        params=_params or None,
    )


def contact_groups_get(resourceName, **params):
    """
    Get a specific contact group owned by the authenticated user by specifying a contact
    group resource name.

    HTTP: ``GET``  Discovery: ``contactGroups.get``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the contact group to get.

    Optional parameters (pass via keyword args):

    * ``groupFields`` (str): Optional. A field mask to restrict which fields on the group are returned. Defaults to \`metadata\`, \`groupType\`, \`memberCount\`, and \`name\` if not set or set to empty. Valid fields are: \* clientData \*…
    * ``maxMembers`` (int): Optional. Specifies the maximum number of members to return. Defaults to 0 if not set, which will return zero members.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_get resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "get",
        params=_params or None,
    )


def contact_groups_list(**params):
    """
    List all contact groups owned by the authenticated user. Members of the contact
    groups are not populated.

    HTTP: ``GET``  Discovery: ``contactGroups.list``

    Optional parameters (pass via keyword args):

    * ``groupFields`` (str): Optional. A field mask to restrict which fields on the group are returned. Defaults to \`metadata\`, \`groupType\`, \`memberCount\`, and \`name\` if not set or set to empty. Valid fields are: \* clientData \*…
    * ``pageSize`` (int): Optional. The maximum number of resources to return. Valid values are between 1 and 1000, inclusive. Defaults to 30 if not set or set to 0.
    * ``pageToken`` (str): Optional. The next\_page\_token value returned from a previous call to [ListContactGroups](/people/api/rest/v1/contactgroups/list). Requests the next page of resources.
    * ``syncToken`` (str): Optional. A sync token, returned by a previous call to \`contactgroups.list\`. Only resources changed since the sync token was created will be returned.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "list",
        params=_params or None,
    )


def contact_groups_update(resourceName, body=None, **params):
    """
    Update the name of an existing contact group owned by the authenticated user.
    Updated contact group names must be unique to the users contact groups. Attempting
    to create a group with a duplicate name will return a HTTP 409 error. Mutate
    requests for the same user should be sent sequentially to avoid increased latency
    and failures.

    HTTP: ``PUT``  Discovery: ``contactGroups.update``

    Required parameters:

    * ``resourceName`` (str): The resource name for the contact group, assigned by the server. An ASCII string, in the form of \`contactGroups/{contact\_group\_id}\`.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_update resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups"],
        "update",
        params=_params or None,
        body=body,
    )


def contact_groups_members_modify(resourceName, body=None, **params):
    """
    Modify the members of a contact group owned by the authenticated user. The only
    system contact groups that can have members added are \`contactGroups/myContacts\`
    and \`contactGroups/starred\`. Other system contact groups are deprecated and can
    only have contacts removed.

    HTTP: ``POST``  Discovery: ``contactGroups.members.modify``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the contact group to modify.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.contact_groups_members_modify resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["contactGroups", "members"],
        "modify",
        params=_params or None,
        body=body,
    )


def other_contacts_copy_other_contact_to_my_contacts_group(resourceName, body=None, **params):
    """
    Copies an "Other contact" to a new contact in the user's "myContacts" group Mutate
    requests for the same user should be sent sequentially to avoid increased latency
    and failures.

    HTTP: ``POST``  Discovery: ``otherContacts.copyOtherContactToMyContactsGroup``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the "Other contact" to copy.

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.other_contacts_copy_other_contact_to_my_contacts_group resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["otherContacts"],
        "copyOtherContactToMyContactsGroup",
        params=_params or None,
        body=body,
    )


def other_contacts_list(**params):
    """
    List all "Other contacts", that is contacts that are not in a contact group. "Other
    contacts" are typically auto created contacts from interactions. Sync tokens expire
    7 days after the full sync. A request with an expired sync token will get an error
    with an
    [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error\_info) with
    reason "EXPIRED\_SYNC\_TOKEN". In the case of such an error clients should make a
    full sync request without a \`sync\_token\`. The first page of a full sync request
    has an additional quota. If the quota is exceeded, a 429 error will be returned.
    This quota is fixed and can not be increased. When the \`sync\_token\` is specified,
    resources deleted since the last sync will be returned as a person with
    \`PersonMetadata.deleted\` set to true. When the \`page\_token\` or \`sync\_token\`
    is specified, all other request parameters must match the first call. Writes may
    have a propagation delay of several minutes for sync requests. Incremental syncs are
    not intended for read-after-write use cases. See example usage at [List the user's
    other contacts that have changed](/people/v1/other-
    contacts#list\_the\_users\_other\_contacts\_that\_have\_changed).

    HTTP: ``GET``  Discovery: ``otherContacts.list``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Optional. The number of "Other contacts" to include in the response. Valid values are between 1 and 1000, inclusive. Defaults to 100 if not set or set to 0.
    * ``pageToken`` (str): Optional. A page token, received from a previous response \`next\_page\_token\`. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to \`otherContacts.list\` must…
    * ``readMask`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. What values are valid depend on what ReadSourceType is us…
    * ``requestSyncToken`` (bool): Optional. Whether the response should return \`next\_sync\_token\` on the last page of results. It can be used to get incremental changes since the last request by setting it on the request \`sync\_token\`.…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT if not set. Possible values for this field are: \* READ\_SOURCE\_TYPE\_CONTACT \* READ\_SOURCE\_TYPE\_CONTACT,READ\_SOURCE…
    * ``syncToken`` (str): Optional. A sync token, received from a previous response \`next\_sync\_token\` Provide this to retrieve only the resources changed since the last request. When syncing, all other parameters provided to…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.other_contacts_list
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["otherContacts"],
        "list",
        params=_params or None,
    )


def other_contacts_search(**params):
    """
    Provides a list of contacts in the authenticated user's other contacts that matches
    the search query. The query matches on a contact's \`names\`, \`emailAddresses\`,
    and \`phoneNumbers\` fields that are from the OTHER\_CONTACT source.
    \*\*IMPORTANT\*\*: Before searching, clients should send a warmup request with an
    empty query to update the cache. See https://developers.google.com/people/v1/other-
    contacts#search\_the\_users\_other\_contacts

    HTTP: ``GET``  Discovery: ``otherContacts.search``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Optional. The number of results to return. Defaults to 10 if field is not set, or set to 0. Values greater than 30 will be capped to 30.
    * ``query`` (str): Required. The plain-text query for the request. The query is used to match prefix phrases of the fields on a person. For example, a person with name "foo name" matches queries such as "f", "fo", "foo…
    * ``readMask`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* emailAddresses \* metadata \* names \* p…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.other_contacts_search
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["otherContacts"],
        "search",
        params=_params or None,
    )


def people_batch_create_contacts(body=None, **params):
    """
    Create a batch of new contacts and return the PersonResponses for the newly Mutate
    requests for the same user should be sent sequentially to avoid increased latency
    and failures.

    HTTP: ``POST``  Discovery: ``people.batchCreateContacts``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_batch_create_contacts
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "batchCreateContacts",
        params=_params or None,
        body=body,
    )


def people_batch_delete_contacts(body=None, **params):
    """
    Delete a batch of contacts. Any non-contact data will not be deleted. Mutate
    requests for the same user should be sent sequentially to avoid increased latency
    and failures.

    HTTP: ``POST``  Discovery: ``people.batchDeleteContacts``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_batch_delete_contacts
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "batchDeleteContacts",
        params=_params or None,
        body=body,
    )


def people_batch_update_contacts(body=None, **params):
    """
    Update a batch of contacts and return a map of resource names to PersonResponses for
    the updated contacts. Mutate requests for the same user should be sent sequentially
    to avoid increased latency and failures.

    HTTP: ``POST``  Discovery: ``people.batchUpdateContacts``

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_batch_update_contacts
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "batchUpdateContacts",
        params=_params or None,
        body=body,
    )


def people_create_contact(body=None, **params):
    """
    Create a new contact and return the person resource for that contact. The request
    returns a 400 error if more than one field is specified on a field that is a
    singleton for contact sources: \* biographies \* birthdays \* genders \* names
    Mutate requests for the same user should be sent sequentially to avoid increased
    latency and failures.

    HTTP: ``POST``  Discovery: ``people.createContact``

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``personFields`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Defaults to all fields if not set. Valid values are: \* ad…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT and READ\_SOURCE\_TYPE\_PROFILE if not set.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_create_contact
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "createContact",
        params=_params or None,
        body=body,
    )


def people_delete_contact(resourceName, **params):
    """
    Delete a contact person. Any non-contact data will not be deleted. Mutate requests
    for the same user should be sent sequentially to avoid increased latency and
    failures.

    HTTP: ``DELETE``  Discovery: ``people.deleteContact``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the contact to delete.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_delete_contact resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "deleteContact",
        params=_params or None,
    )


def people_delete_contact_photo(resourceName, **params):
    """
    Delete a contact's photo. Mutate requests for the same user should be done
    sequentially to avoid // lock contention.

    HTTP: ``DELETE``  Discovery: ``people.deleteContactPhoto``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the contact whose photo will be deleted.

    Optional parameters (pass via keyword args):

    * ``personFields`` (str): Optional. A field mask to restrict which fields on the person are returned. Multiple fields can be specified by separating them with commas. Defaults to empty if not set, which will skip the post mut…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT and READ\_SOURCE\_TYPE\_PROFILE if not set.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_delete_contact_photo resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "deleteContactPhoto",
        params=_params or None,
    )


def people_get(resourceName, **params):
    """
    Provides information about a person by specifying a resource name. Use \`people/me\`
    to indicate the authenticated user. The request returns a 400 error if
    'personFields' is not specified.

    HTTP: ``GET``  Discovery: ``people.get``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name of the person to provide information about. - To get information about the authenticated user, specify \`people/me\`. - To get information about a google account, specify \`p…

    Optional parameters (pass via keyword args):

    * ``personFields`` (str): Required. A field mask to restrict which fields on the person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``requestMask.includeField`` (str): Required. Comma-separated list of person fields to be included in the response. Each path should start with \`person.\`: for example, \`person.names\` or \`person.photos\`.
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_PROFILE and READ\_SOURCE\_TYPE\_CONTACT if not set.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_get resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "get",
        params=_params or None,
    )


def people_get_batch_get(**params):
    """
    Provides information about a list of specific people by specifying a list of
    requested resource names. Use \`people/me\` to indicate the authenticated user. The
    request returns a 400 error if 'personFields' is not specified.

    HTTP: ``GET``  Discovery: ``people.getBatchGet``

    Optional parameters (pass via keyword args):

    * ``personFields`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``requestMask.includeField`` (str): Required. Comma-separated list of person fields to be included in the response. Each path should start with \`person.\`: for example, \`person.names\` or \`person.photos\`.
    * ``resourceNames`` (str): Required. The resource names of the people to provide information about. It's repeatable. The URL query parameter should be resourceNames=<name1>&resourceNames=<name2>&... - To get information about…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT and READ\_SOURCE\_TYPE\_PROFILE if not set.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_get_batch_get
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "getBatchGet",
        params=_params or None,
    )


def people_list_directory_people(**params):
    """
    Provides a list of domain profiles and domain contacts in the authenticated user's
    domain directory. When the \`sync\_token\` is specified, resources deleted since the
    last sync will be returned as a person with \`PersonMetadata.deleted\` set to true.
    When the \`page\_token\` or \`sync\_token\` is specified, all other request
    parameters must match the first call. Writes may have a propagation delay of several
    minutes for sync requests. Incremental syncs are not intended for read-after-write
    use cases. See example usage at [List the directory people that have
    changed](/people/v1/directory#list\_the\_directory\_people\_that\_have\_changed).

    HTTP: ``GET``  Discovery: ``people.listDirectoryPeople``

    Optional parameters (pass via keyword args):

    * ``mergeSources`` (str): Optional. Additional data to merge into the directory sources if they are connected through verified join keys such as email addresses or phone numbers.
    * ``pageSize`` (int): Optional. The number of people to include in the response. Valid values are between 1 and 1000, inclusive. Defaults to 100 if not set or set to 0.
    * ``pageToken`` (str): Optional. A page token, received from a previous response \`next\_page\_token\`. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to \`people.listDirectoryPeopl…
    * ``readMask`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``requestSyncToken`` (bool): Optional. Whether the response should return \`next\_sync\_token\`. It can be used to get incremental changes since the last request by setting it on the request \`sync\_token\`. More details about sync beh…
    * ``sources`` (str): Required. Directory sources to return.
    * ``syncToken`` (str): Optional. A sync token, received from a previous response \`next\_sync\_token\` Provide this to retrieve only the resources changed since the last request. When syncing, all other parameters provided to…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_list_directory_people
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "listDirectoryPeople",
        params=_params or None,
    )


def people_search_contacts(**params):
    """
    Provides a list of contacts in the authenticated user's grouped contacts that
    matches the search query. The query matches on a contact's \`names\`, \`nickNames\`,
    \`emailAddresses\`, \`phoneNumbers\`, and \`organizations\` fields that are from the
    CONTACT source. \*\*IMPORTANT\*\*: Before searching, clients should send a warmup
    request with an empty query to update the cache. See
    https://developers.google.com/people/v1/contacts#search\_the\_users\_contacts

    HTTP: ``GET``  Discovery: ``people.searchContacts``

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Optional. The number of results to return. Defaults to 10 if field is not set, or set to 0. Values greater than 30 will be capped to 30.
    * ``query`` (str): Required. The plain-text query for the request. The query is used to match prefix phrases of the fields on a person. For example, a person with name "foo name" matches queries such as "f", "fo", "foo…
    * ``readMask`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT if not set.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_search_contacts
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "searchContacts",
        params=_params or None,
    )


def people_search_directory_people(**params):
    """
    Provides a list of domain profiles and domain contacts in the authenticated user's
    domain directory that match the search query.

    HTTP: ``GET``  Discovery: ``people.searchDirectoryPeople``

    Optional parameters (pass via keyword args):

    * ``mergeSources`` (str): Optional. Additional data to merge into the directory sources if they are connected through verified join keys such as email addresses or phone numbers.
    * ``pageSize`` (int): Optional. The number of people to include in the response. Valid values are between 1 and 500, inclusive. Defaults to 100 if not set or set to 0.
    * ``pageToken`` (str): Optional. A page token, received from a previous response \`next\_page\_token\`. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to \`SearchDirectoryPeople\` mu…
    * ``query`` (str): Required. Prefix query that matches fields in the person. Does NOT use the read\_mask for determining what fields to match.
    * ``readMask`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``sources`` (str): Required. Directory sources to return.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_search_directory_people
    """
    _params = dict(params)
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "searchDirectoryPeople",
        params=_params or None,
    )


def people_update_contact(resourceName, body=None, **params):
    """
    Update contact data for an existing contact person. Any non-contact data will not be
    modified. Any non-contact data in the person to update will be ignored. All fields
    specified in the \`update\_mask\` will be replaced. The server returns a 400 error
    if \`person.metadata.sources\` is not specified for the contact to be updated or if
    there is no contact source. The server returns a 400 error with reason
    \`"failedPrecondition"\` if \`person.metadata.sources.etag\` is different than the
    contact's etag, which indicates the contact has changed since its data was read.
    Clients should get the latest person and merge their updates into the latest person.
    If making sequential updates to the same person, the etag from the \`updateContact\`
    response should be used to avoid failures. The server returns a 400 error if
    \`memberships\` are being updated and there are no contact group memberships
    specified on the person. The server returns a 400 error if more than one field is
    specified on a field that is a singleton for contact sources: \* biographies \*
    birthdays \* genders \* names Mutate requests for the same user should be sent
    sequentially to avoid increased latency and failures.

    HTTP: ``PATCH``  Discovery: ``people.updateContact``

    Required parameters:

    * ``resourceName`` (str): The resource name for the person, assigned by the server. An ASCII string in the form of \`people/{person\_id}\`.

    * ``body`` (dict): request body payload.

    Optional parameters (pass via keyword args):

    * ``personFields`` (str): Optional. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Defaults to all fields if not set. Valid values are: \* ad…
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT and READ\_SOURCE\_TYPE\_PROFILE if not set.
    * ``updatePersonFields`` (str): Required. A field mask to restrict which fields on the person are updated. Multiple fields can be specified by separating them with commas. All updated fields will be replaced. Valid values are: \* ad…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_update_contact resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "updateContact",
        params=_params or None,
        body=body,
    )


def people_update_contact_photo(resourceName, body=None, **params):
    """
    Update a contact's photo. Mutate requests for the same user should be sent
    sequentially to avoid increased latency and failures.

    HTTP: ``PATCH``  Discovery: ``people.updateContactPhoto``

    Required parameters:

    * ``resourceName`` (str): Required. Person resource name

    * ``body`` (dict): request body payload.

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_update_contact_photo resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people"],
        "updateContactPhoto",
        params=_params or None,
        body=body,
    )


def people_connections_list(resourceName, **params):
    """
    Provides a list of the authenticated user's contacts. Sync tokens expire 7 days
    after the full sync. A request with an expired sync token will get an error with an
    [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error\_info) with
    reason "EXPIRED\_SYNC\_TOKEN". In the case of such an error clients should make a
    full sync request without a \`sync\_token\`. The first page of a full sync request
    has an additional quota. If the quota is exceeded, a 429 error will be returned.
    This quota is fixed and can not be increased. When the \`sync\_token\` is specified,
    resources deleted since the last sync will be returned as a person with
    \`PersonMetadata.deleted\` set to true. When the \`page\_token\` or \`sync\_token\`
    is specified, all other request parameters must match the first call. Writes may
    have a propagation delay of several minutes for sync requests. Incremental syncs are
    not intended for read-after-write use cases. See example usage at [List the user's
    contacts that have
    changed](/people/v1/contacts#list\_the\_users\_contacts\_that\_have\_changed).

    HTTP: ``GET``  Discovery: ``people.connections.list``

    Required parameters:

    * ``resourceName`` (str): Required. The resource name to return connections for. Only \`people/me\` is valid.

    Optional parameters (pass via keyword args):

    * ``pageSize`` (int): Optional. The number of connections to include in the response. Valid values are between 1 and 1000, inclusive. Defaults to 100 if not set or set to 0.
    * ``pageToken`` (str): Optional. A page token, received from a previous response \`next\_page\_token\`. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to \`people.connections.list\`…
    * ``personFields`` (str): Required. A field mask to restrict which fields on each person are returned. Multiple fields can be specified by separating them with commas. Valid values are: \* addresses \* ageRanges \* biographies \*…
    * ``requestMask.includeField`` (str): Required. Comma-separated list of person fields to be included in the response. Each path should start with \`person.\`: for example, \`person.names\` or \`person.photos\`.
    * ``requestSyncToken`` (bool): Optional. Whether the response should return \`next\_sync\_token\` on the last page of results. It can be used to get incremental changes since the last request by setting it on the request \`sync\_token\`.…
    * ``sortOrder`` (str): Optional. The order in which the connections should be sorted. Defaults to \`LAST\_MODIFIED\_ASCENDING\`.
    * ``sources`` (str): Optional. A mask of what source types to return. Defaults to READ\_SOURCE\_TYPE\_CONTACT and READ\_SOURCE\_TYPE\_PROFILE if not set.
    * ``syncToken`` (str): Optional. A sync token, received from a previous response \`next\_sync\_token\` Provide this to retrieve only the resources changed since the last request. When syncing, all other parameters provided to…

    CLI Example:

    .. code-block:: bash

        salt '*' gsuite_people.people_connections_list resourceName=<str>
    """
    _params = dict(params)
    _params["resourceName"] = resourceName
    return _gws.call(
        __opts__,
        __pillar__,
        "people",
        ["people", "connections"],
        "list",
        params=_params or None,
    )
