# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import MagicMock

import pytest

import saltext.gsuite.states.gsuite_drive as state

STATE_CASES = [
    {
        "absent": "comments_absent",
        "create_key": "gsuite_drive.comments_create",
        "delete_key": "gsuite_drive.comments_delete",
        "get_key": "gsuite_drive.comments_get",
        "present": "comments_present",
    },
    {
        "absent": "drives_absent",
        "create_key": "gsuite_drive.drives_create",
        "delete_key": "gsuite_drive.drives_delete",
        "get_key": "gsuite_drive.drives_get",
        "present": "drives_present",
    },
    {
        "absent": "files_absent",
        "create_key": "gsuite_drive.files_create",
        "delete_key": "gsuite_drive.files_delete",
        "get_key": "gsuite_drive.files_get",
        "present": "files_present",
    },
    {
        "absent": "permissions_absent",
        "create_key": "gsuite_drive.permissions_create",
        "delete_key": "gsuite_drive.permissions_delete",
        "get_key": "gsuite_drive.permissions_get",
        "present": "permissions_present",
    },
    {
        "absent": "replies_absent",
        "create_key": "gsuite_drive.replies_create",
        "delete_key": "gsuite_drive.replies_delete",
        "get_key": "gsuite_drive.replies_get",
        "present": "replies_present",
    },
    {
        "absent": "teamdrives_absent",
        "create_key": "gsuite_drive.teamdrives_create",
        "delete_key": "gsuite_drive.teamdrives_delete",
        "get_key": "gsuite_drive.teamdrives_get",
        "present": "teamdrives_present",
    },
]


def _loader(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": False}, "__pillar__": {}}}


def _loader_test(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": True}, "__pillar__": {}}}


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_creates_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(return_value={"id": "new"}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is True
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_noop_when_present_no_body(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_test_mode_reports_create(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader_test(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is None
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_deletes_when_present(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["delete_key"]: MagicMock(return_value={}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {"deleted": "the-id"}
    salt[case["delete_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_noop_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["delete_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["delete_key"]].assert_not_called()
