# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import MagicMock

import pytest

import saltext.gsuite.states.gsuite_events as state

STATE_CASES = [
    {
        "absent": "subscriptions_absent",
        "create_key": "gsuite_events.subscriptions_create",
        "delete_key": "gsuite_events.subscriptions_delete",
        "get_key": "gsuite_events.subscriptions_get",
        "present": "subscriptions_present",
    },
    {
        "absent": "tasks_push_notification_configs_absent",
        "create_key": "gsuite_events.tasks_push_notification_configs_create",
        "delete_key": "gsuite_events.tasks_push_notification_configs_delete",
        "get_key": "gsuite_events.tasks_push_notification_configs_get",
        "present": "tasks_push_notification_configs_present",
    },
]


def _loader(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": False}, "__pillar__": {}}}


def _loader_test(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": True}, "__pillar__": {}}}


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_creates_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(return_value={"id": "new"}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is True
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_noop_when_present_no_body(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_test_mode_reports_create(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader_test(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is None
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_deletes_when_present(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["delete_key"]: MagicMock(return_value={}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {"deleted": "the-id"}
    salt[case["delete_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_noop_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["delete_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["delete_key"]].assert_not_called()
