# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
from unittest.mock import MagicMock

import pytest

import saltext.gsuite.states.gsuite_classroom as state

STATE_CASES = [
    {
        "absent": "courses_absent",
        "create_key": "gsuite_classroom.courses_create",
        "delete_key": "gsuite_classroom.courses_delete",
        "get_key": "gsuite_classroom.courses_get",
        "present": "courses_present",
    },
    {
        "absent": "courses_announcements_absent",
        "create_key": "gsuite_classroom.courses_announcements_create",
        "delete_key": "gsuite_classroom.courses_announcements_delete",
        "get_key": "gsuite_classroom.courses_announcements_get",
        "present": "courses_announcements_present",
    },
    {
        "absent": "courses_announcements_add_on_attachments_absent",
        "create_key": "gsuite_classroom.courses_announcements_add_on_attachments_create",
        "delete_key": "gsuite_classroom.courses_announcements_add_on_attachments_delete",
        "get_key": "gsuite_classroom.courses_announcements_add_on_attachments_get",
        "present": "courses_announcements_add_on_attachments_present",
    },
    {
        "absent": "courses_course_work_absent",
        "create_key": "gsuite_classroom.courses_course_work_create",
        "delete_key": "gsuite_classroom.courses_course_work_delete",
        "get_key": "gsuite_classroom.courses_course_work_get",
        "present": "courses_course_work_present",
    },
    {
        "absent": "courses_course_work_add_on_attachments_absent",
        "create_key": "gsuite_classroom.courses_course_work_add_on_attachments_create",
        "delete_key": "gsuite_classroom.courses_course_work_add_on_attachments_delete",
        "get_key": "gsuite_classroom.courses_course_work_add_on_attachments_get",
        "present": "courses_course_work_add_on_attachments_present",
    },
    {
        "absent": "courses_course_work_rubrics_absent",
        "create_key": "gsuite_classroom.courses_course_work_rubrics_create",
        "delete_key": "gsuite_classroom.courses_course_work_rubrics_delete",
        "get_key": "gsuite_classroom.courses_course_work_rubrics_get",
        "present": "courses_course_work_rubrics_present",
    },
    {
        "absent": "courses_course_work_materials_absent",
        "create_key": "gsuite_classroom.courses_course_work_materials_create",
        "delete_key": "gsuite_classroom.courses_course_work_materials_delete",
        "get_key": "gsuite_classroom.courses_course_work_materials_get",
        "present": "courses_course_work_materials_present",
    },
    {
        "absent": "courses_course_work_materials_add_on_attachments_absent",
        "create_key": "gsuite_classroom.courses_course_work_materials_add_on_attachments_create",
        "delete_key": "gsuite_classroom.courses_course_work_materials_add_on_attachments_delete",
        "get_key": "gsuite_classroom.courses_course_work_materials_add_on_attachments_get",
        "present": "courses_course_work_materials_add_on_attachments_present",
    },
    {
        "absent": "courses_posts_add_on_attachments_absent",
        "create_key": "gsuite_classroom.courses_posts_add_on_attachments_create",
        "delete_key": "gsuite_classroom.courses_posts_add_on_attachments_delete",
        "get_key": "gsuite_classroom.courses_posts_add_on_attachments_get",
        "present": "courses_posts_add_on_attachments_present",
    },
    {
        "absent": "courses_students_absent",
        "create_key": "gsuite_classroom.courses_students_create",
        "delete_key": "gsuite_classroom.courses_students_delete",
        "get_key": "gsuite_classroom.courses_students_get",
        "present": "courses_students_present",
    },
    {
        "absent": "courses_teachers_absent",
        "create_key": "gsuite_classroom.courses_teachers_create",
        "delete_key": "gsuite_classroom.courses_teachers_delete",
        "get_key": "gsuite_classroom.courses_teachers_get",
        "present": "courses_teachers_present",
    },
    {
        "absent": "courses_topics_absent",
        "create_key": "gsuite_classroom.courses_topics_create",
        "delete_key": "gsuite_classroom.courses_topics_delete",
        "get_key": "gsuite_classroom.courses_topics_get",
        "present": "courses_topics_present",
    },
    {
        "absent": "invitations_absent",
        "create_key": "gsuite_classroom.invitations_create",
        "delete_key": "gsuite_classroom.invitations_delete",
        "get_key": "gsuite_classroom.invitations_get",
        "present": "invitations_present",
    },
]


def _loader(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": False}, "__pillar__": {}}}


def _loader_test(salt):
    return {state: {"__salt__": salt, "__opts__": {"test": True}, "__pillar__": {}}}


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_creates_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(return_value={"id": "new"}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is True
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_noop_when_present_no_body(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["present"] for c in STATE_CASES])
def test_present_test_mode_reports_create(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["create_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader_test(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["present"])(name="the-id", body={"k": "v"})
    assert ret["result"] is None
    assert ret["changes"] == {"created": "the-id"}
    salt[case["create_key"]].assert_not_called()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_deletes_when_present(case):
    salt = {
        case["get_key"]: MagicMock(return_value={"id": "the-id"}),
        case["delete_key"]: MagicMock(return_value={}),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {"deleted": "the-id"}
    salt[case["delete_key"]].assert_called_once()


@pytest.mark.parametrize("case", STATE_CASES, ids=[c["absent"] for c in STATE_CASES])
def test_absent_noop_when_absent(case):
    salt = {
        case["get_key"]: MagicMock(return_value=None),
        case["delete_key"]: MagicMock(),
    }
    with pytest.MonkeyPatch.context() as mp:
        for attr, value in _loader(salt)[state].items():
            mp.setattr(state, attr, value, raising=False)
        ret = getattr(state, case["absent"])(name="the-id")
    assert ret["result"] is True
    assert ret["changes"] == {}
    salt[case["delete_key"]].assert_not_called()
