#!/usr/bin/env python
"""
Regenerate the entire ``saltext.gsuite`` module surface from Google Discovery + the bundled
``gws`` CLI.

This is a *reconciler*, not an additive scaffolder: each run recomputes the full fileset for
the current CLI/Discovery release and creates, updates, and deletes generated modules, states,
tests, docs, and schema snapshots so the tree matches exactly what the CLI exposes. Hand-tuned
code lives only in ``states/overrides/`` and is never overwritten.

Usage::

    python tools/generate_modules.py --all
    python tools/generate_modules.py --service drive --service gmail
    python tools/generate_modules.py --all --no-cache     # force re-fetch Discovery docs
"""

from __future__ import annotations

import argparse
import json
import os
import pprint
import subprocess
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _codegen import discovery  # noqa: E402
from _codegen import helpers as helpers_mod  # noqa: E402
from _codegen import naming  # noqa: E402

try:
    from jinja2 import Environment
    from jinja2 import FileSystemLoader
except ImportError:  # pragma: no cover
    sys.exit("jinja2 is required: pip install jinja2")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "saltext", "gsuite")
META = os.path.join(SRC, "metadata")
MODULES = os.path.join(SRC, "modules")
STATES = os.path.join(SRC, "states")
OVERRIDES = os.path.join(STATES, "overrides")
SCHEMAS = os.path.join(META, "schemas")
TESTS_M = os.path.join(ROOT, "tests", "unit", "modules")
TESTS_S = os.path.join(ROOT, "tests", "unit", "states")
DOCS_M = os.path.join(ROOT, "docs", "ref", "modules")
DOCS_S = os.path.join(ROOT, "docs", "ref", "states")
MANIFEST = os.path.join(META, "generated_manifest.json")
TEMPLATES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_codegen", "templates")

HEADER = "# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten."

_ENV = Environment(
    loader=FileSystemLoader(TEMPLATES),
    keep_trailing_newline=True,
    trim_blocks=False,
    lstrip_blocks=False,
)
_ENV.filters["tojson"] = json.dumps


# --------------------------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------------------------
def _rel(path):
    return os.path.relpath(path, ROOT)


def resolve_binary(explicit=None):
    """Locate a gws binary for generation (dev sandbox copy preferred)."""
    if explicit:
        return explicit
    for candidate in (
        os.path.join(ROOT, "sandbox", "gws"),
        os.path.join(SRC, "_vendor", "gws"),
        os.path.join(SRC, "_vendor", "gws.exe"),
    ):
        if os.path.isfile(candidate):
            return candidate
    raise SystemExit("No gws binary found (looked in sandbox/ and _vendor/).")


def load_services():
    with open(os.path.join(META, "services.json"), encoding="utf-8") as handle:
        return json.load(handle)["services"]


def _indent(text, prefix="    "):
    return "\n".join(prefix + line if line else "" for line in text.splitlines())


def _wrap(text, width=88, indent="    "):
    if not text:
        return ""
    return textwrap.fill(
        naming.rst_escape(naming.clean_description(text)),
        width=width,
        initial_indent=indent,
        subsequent_indent=indent,
    )


def _cap(text, limit=200):
    text = naming.clean_description(text)
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "\N{HORIZONTAL ELLIPSIS}"
    return naming.rst_escape(text)


# --------------------------------------------------------------------------------------------
# context builders
# --------------------------------------------------------------------------------------------
def build_method_docstring(virtualname, method, required, optional):
    lines = []
    if method.description:
        lines.append(_wrap(method.description))
        lines.append("")
    lines.append(f"    HTTP: ``{method.http_method}``  Discovery: ``{method.dotted}``")
    lines.append("")
    if required:
        lines.append("    Required parameters:")
        lines.append("")
        for param in required:
            lines.append(f"    * ``{param['orig']}`` ({param['type']}): {_cap(param['desc'])}")
        lines.append("")
    if method.has_body:
        lines.append("    * ``body`` (dict): request body payload.")
        lines.append("")
    if method.supports_media_upload:
        lines.append("    * ``upload`` (str): local path of a file to upload as media content.")
        lines.append("")
    if optional:
        lines.append("    Optional parameters (pass via keyword args):")
        lines.append("")
        for param in optional:
            flag = " *(deprecated)*" if param.get("deprecated") else ""
            lines.append(f"    * ``{param['orig']}`` ({param['type']}){flag}: {_cap(param['desc'])}")
        lines.append("")
    example_args = " ".join(f"{p['orig']}=<{p['type']}>" for p in required[:3])
    lines.append("    CLI Example:")
    lines.append("")
    lines.append("    .. code-block:: bash")
    lines.append("")
    lines.append(f"        salt '*' {virtualname}.{method_fn_name(method)} {example_args}".rstrip())
    return "\n".join(lines).rstrip()


def method_fn_name(method):
    return naming.function_name(method.resource_path, method.name)


def build_method_context(virtualname, method):
    required = naming.required_params(method)
    optional = naming.optional_params(method)
    parts = [p["py"] for p in required]
    if method.has_body:
        parts.append("body=None")
    if method.supports_media_upload:
        parts.append("upload=None")
    parts.append("**params")
    return {
        "fn_name": method_fn_name(method),
        "method_name": method.name,
        "signature": ", ".join(parts),
        "required": required,
        "has_body": method.has_body,
        "has_upload": method.supports_media_upload,
        "docstring": build_method_docstring(virtualname, method, required, optional),
    }


def build_helper_docstring(virtualname, helper):
    lines = []
    if helper.description:
        lines.append(_wrap(f"[Helper] {helper.description}"))
        lines.append("")
    if helper.args:
        lines.append("    Positional arguments:")
        lines.append("")
        for arg in helper.args:
            req = "required" if arg.required else "optional"
            lines.append(f"    * ``{arg.py}`` ({req}): {_cap(arg.desc) or arg.name}")
        lines.append("")
    if helper.options:
        lines.append("    Options:")
        lines.append("")
        for opt in helper.options:
            req = "required" if opt.required else "optional"
            kind = "value" if opt.takes_value else "flag"
            lines.append(f"    * ``{opt.py}`` ({req} {kind}): {_cap(opt.desc)}")
        lines.append("")
    lines.append("    CLI Example:")
    lines.append("")
    lines.append("    .. code-block:: bash")
    lines.append("")
    lines.append(f"        salt '*' {virtualname}.{helper.py}")
    return "\n".join(lines).rstrip()


def build_helper_context(virtualname, helper):
    required = [a.py for a in helper.args if a.required]
    required += [o.py for o in helper.options if o.required]
    optional = [a.py for a in helper.args if not a.required]
    optional += [o.py for o in helper.options if not o.required]
    parts = list(required) + [f"{name}=None" for name in optional] + ["test=False"]
    return {
        "fn_name": helper.py,
        "command": helper.command,
        "signature": ", ".join(parts),
        "positionals": [a.py for a in helper.args],
        "positionals_repr": ", ".join(a.py for a in helper.args),
        "flags": [{"long": o.long, "py": o.py} for o in helper.options if o.takes_value],
        "switches": [{"long": o.long, "py": o.py} for o in helper.options if not o.takes_value],
        "docstring": build_helper_docstring(virtualname, helper),
    }


def detect_crud(methods):
    """Group methods by resource and emit state contexts for CRUD-shaped resources."""
    by_resource = {}
    for method in methods:
        by_resource.setdefault(method.resource_path, {})[method.name] = method
    resources = []
    for resource_path in sorted(by_resource):
        names = by_resource[resource_path]
        get = names.get("get")
        create = "create" if "create" in names else ("insert" if "insert" in names else None)
        update = "patch" if "patch" in names else ("update" if "update" in names else None)
        delete = "delete" if "delete" in names else None
        if not (get and create and delete):
            continue
        get_required = naming.required_params(get)
        if not get_required:
            continue
        id_param = get_required[-1]["orig"]
        base = "_".join(naming.snake(p) for p in resource_path)
        resources.append(
            {
                "present_name": f"{base}_present",
                "absent_name": f"{base}_absent",
                "label": resource_path[-1],
                "id_param": id_param,
                "get_fn": naming.function_name(resource_path, get.name),
                "create_fn": naming.function_name(resource_path, create),
                "update_fn": naming.function_name(resource_path, update) if update else None,
                "update_method": update,
                "delete_fn": naming.function_name(resource_path, delete),
            }
        )
    return resources


# --------------------------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------------------------
def _write(path, content, produced):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    produced.add(_rel(path))


def generate_service(service, binary, use_cache, produced, report):
    module = service["module"]
    cli = service["cli"]
    pymodule = f"gsuite_{module}"
    exec_vn = f"gsuite_{module}"

    methods = []
    if service.get("discovery", True):
        schema = discovery.load_service(service["api"], service["version"], use_cache=use_cache)
        exposed = helpers_mod.list_resources(binary, cli)
        methods = [m for m in schema.methods if m.resource_path[0] in exposed]
        # snapshot resolved schema for this service (deterministic)
        snap = {
            "api": schema.api,
            "version": schema.version,
            "revision": schema.revision,
            "methods": [
                {
                    "fn": method_fn_name(m),
                    "resource_path": list(m.resource_path),
                    "method": m.name,
                    "http_method": m.http_method,
                    "has_body": m.has_body,
                    "supports_media_upload": m.supports_media_upload,
                    "required": [p["orig"] for p in naming.required_params(m)],
                }
                for m in methods
            ],
        }
        _write(
            os.path.join(SCHEMAS, f"{module}.json"),
            json.dumps(snap, indent=2, sort_keys=True) + "\n",
            produced,
        )

    parsed_helpers = helpers_mod.parse_service_helpers(binary, cli)

    method_ctxs = [build_method_context(exec_vn, m) for m in methods]
    helper_ctxs = [build_helper_context(exec_vn, h) for h in parsed_helpers]
    helper_ctxs.sort(key=lambda h: h["fn_name"])

    # ---- execution module ----
    exec_src = _ENV.get_template("execution_module.py.jinja").render(
        header=HEADER,
        title=service["description"],
        description=service["description"],
        api=service["api"],
        version=service["version"],
        virtualname=exec_vn,
        service=cli,
        methods=[
            {**ctx, "resource_path_repr": json.dumps(list(m.resource_path))}
            for ctx, m in zip(method_ctxs, methods)
        ],
        helpers=helper_ctxs,
    )
    _write(os.path.join(MODULES, f"{pymodule}.py"), exec_src, produced)

    # ---- state module ----
    resources = detect_crud(methods)
    overrides_file = os.path.join(OVERRIDES, f"{module}.py")
    overrides_import = os.path.isfile(overrides_file)
    if resources:
        state_src = _ENV.get_template("state_module.py.jinja").render(
            header=HEADER,
            title=service["description"],
            module=module,
            virtualname=f"gsuite_{module}",
            exec_virtualname=exec_vn,
            resources=resources,
            overrides_import=overrides_import,
        )
        _write(os.path.join(STATES, f"{pymodule}.py"), state_src, produced)

    # ---- tests ----
    method_cases = [
        {
            "fn": ctx["fn_name"],
            "service": cli,
            "path": list(m.resource_path),
            "method": m.name,
            "required": {p["py"]: _sample(p) for p in ctx["required"]},
            "orig_required": {p["orig"]: _sample(p) for p in ctx["required"]},
        }
        for ctx, m in zip(method_ctxs, methods)
    ]
    helper_cases = [
        {
            "fn": ctx["fn_name"],
            "service": cli,
            "command": ctx["command"],
            "required": {
                name: "x"
                for name in _helper_required_names(ctx["signature"])
            },
        }
        for ctx in helper_ctxs
    ]
    test_src = _ENV.get_template("unit_test_module.py.jinja").render(
        header=HEADER,
        pymodule=pymodule,
        virtualname=exec_vn,
        method_cases=pprint.pformat(method_cases, indent=4, width=98, sort_dicts=True),
        helper_cases=pprint.pformat(helper_cases, indent=4, width=98, sort_dicts=True),
        method_cases_nonempty=bool(method_cases),
        helper_cases_nonempty=bool(helper_cases),
    )
    _write(os.path.join(TESTS_M, f"test_{pymodule}.py"), test_src, produced)

    if resources:
        state_cases = [
            {
                "present": r["present_name"],
                "absent": r["absent_name"],
                "get_key": f"{exec_vn}.{r['get_fn']}",
                "create_key": f"{exec_vn}.{r['create_fn']}",
                "delete_key": f"{exec_vn}.{r['delete_fn']}",
            }
            for r in resources
        ]
        state_test_src = _ENV.get_template("unit_test_state.py.jinja").render(
            header=HEADER,
            pymodule=pymodule,
            state_cases=pprint.pformat(state_cases, indent=4, width=98, sort_dicts=True),
        )
        _write(os.path.join(TESTS_S, f"test_{pymodule}.py"), state_test_src, produced)

    # ---- docs ----
    _write(
        os.path.join(DOCS_M, f"{pymodule}.rst"),
        _autodoc_rst(pymodule, f"saltext.gsuite.modules.{pymodule}"),
        produced,
    )
    if resources:
        _write(
            os.path.join(DOCS_S, f"{pymodule}.rst"),
            _autodoc_rst(pymodule, f"saltext.gsuite.states.{pymodule}"),
            produced,
        )

    report["services"].append(
        {
            "module": module,
            "methods": len(methods),
            "helpers": len(helper_ctxs),
            "states": len(resources),
        }
    )
    return {"has_state": bool(resources)}


def _sample(param):
    return {"int": 1, "float": 1.0, "bool": True, "list": ["x"], "dict": {}}.get(
        param["type"], "x"
    )


def _helper_required_names(signature):
    names = []
    for token in signature.split(", "):
        if "=" in token or token.startswith("*"):
            continue
        names.append(token)
    return names


def _autodoc_rst(title, dotted):
    underline = "=" * len(title)
    return f"{title}\n{underline}\n\n.. automodule:: {dotted}\n    :members:\n"


def _write_indices(produced):
    module_pages = sorted(
        name[:-4] for name in os.listdir(DOCS_M) if name.endswith(".rst") and name != "index.rst"
    )
    lines = [
        "Execution Modules",
        "=================",
        "",
        ".. toctree::",
        "    :maxdepth: 1",
        "",
    ]
    lines += [f"    {page}" for page in module_pages]
    _write(os.path.join(DOCS_M, "index.rst"), "\n".join(lines) + "\n", produced)

    state_pages = sorted(
        name[:-4] for name in os.listdir(DOCS_S) if name.endswith(".rst") and name != "index.rst"
    )
    lines = [
        "State Modules",
        "=============",
        "",
        ".. toctree::",
        "    :maxdepth: 1",
        "",
    ]
    lines += [f"    {page}" for page in state_pages]
    _write(os.path.join(DOCS_S, "index.rst"), "\n".join(lines) + "\n", produced)


def _format(paths):
    py = [p for p in paths if p.endswith(".py")]
    abs_py = [os.path.join(ROOT, p) for p in py]
    if not abs_py:
        return
    subprocess.run(
        [sys.executable, "-m", "isort", "--quiet", *abs_py], check=False, cwd=ROOT
    )
    subprocess.run(
        [sys.executable, "-m", "black", "--quiet", "--fast", *abs_py], check=False, cwd=ROOT
    )


def _prune(produced, report):
    old = set()
    if os.path.isfile(MANIFEST):
        with open(MANIFEST, encoding="utf-8") as handle:
            old = set(json.load(handle).get("files", []))
    stale = sorted(old - produced)
    for rel in stale:
        path = os.path.join(ROOT, rel)
        if os.path.isfile(path):
            os.remove(path)
    report["pruned"] = stale
    with open(MANIFEST, "w", encoding="utf-8") as handle:
        json.dump(
            {"files": sorted(produced)}, handle, indent=2, sort_keys=True
        )
        handle.write("\n")


def _ensure_scaffold():
    for path in (MODULES, STATES, OVERRIDES, SCHEMAS, TESTS_M, TESTS_S, DOCS_M, DOCS_S):
        os.makedirs(path, exist_ok=True)
    init = os.path.join(OVERRIDES, "__init__.py")
    if not os.path.isfile(init):
        with open(init, "w", encoding="utf-8") as handle:
            handle.write(
                '"""Hand-tuned state overrides. The generator prefers functions defined '
                'here\nover their auto-generated counterparts (merged by name)."""\n'
            )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true", help="generate every service")
    parser.add_argument("--service", action="append", default=[], help="generate one service")
    parser.add_argument("--binary", help="path to a gws binary (default: sandbox/ or _vendor/)")
    parser.add_argument("--no-cache", action="store_true", help="force re-fetch Discovery docs")
    parser.add_argument("--report", help="write the JSON generation report to this path")
    args = parser.parse_args(argv)

    services = load_services()
    if args.service:
        wanted = set(args.service)
        services = [s for s in services if s["module"] in wanted or s["cli"] in wanted]
        if not services:
            raise SystemExit(f"No matching services for {sorted(wanted)}")
    elif not args.all:
        raise SystemExit("Specify --all or --service <name>")

    binary = resolve_binary(args.binary)
    _ensure_scaffold()

    produced = {_rel(os.path.join(OVERRIDES, "__init__.py"))}
    report = {"services": [], "pruned": []}

    # gsuite_util is hand-written but owns a doc page so the index is complete.
    _write(
        os.path.join(DOCS_M, "gsuite_util.rst"),
        _autodoc_rst("gsuite_util", "saltext.gsuite.modules.gsuite_util"),
        produced,
    )

    for service in services:
        try:
            generate_service(service, binary, not args.no_cache, produced, report)
        except Exception as exc:  # pylint: disable=broad-except
            print(f"  ! {service['module']}: {exc}", file=sys.stderr)
            raise

    _write_indices(produced)

    # Only prune when generating the full set (partial runs must not delete other services).
    if args.all:
        _prune(produced, report)
    else:
        # merge into existing manifest without deleting
        old = set()
        if os.path.isfile(MANIFEST):
            with open(MANIFEST, encoding="utf-8") as handle:
                old = set(json.load(handle).get("files", []))
        with open(MANIFEST, "w", encoding="utf-8") as handle:
            json.dump({"files": sorted(old | produced)}, handle, indent=2, sort_keys=True)
            handle.write("\n")

    _format(sorted(produced))

    total_m = sum(s["methods"] for s in report["services"])
    total_h = sum(s["helpers"] for s in report["services"])
    total_s = sum(s["states"] for s in report["services"])
    print(
        f"Generated {len(report['services'])} services: "
        f"{total_m} methods, {total_h} helpers, {total_s} state resources. "
        f"Pruned {len(report['pruned'])} stale files."
    )
    for entry in report["services"]:
        print(
            f"  {entry['module']:<16} methods={entry['methods']:<4} "
            f"helpers={entry['helpers']:<3} states={entry['states']}"
        )
    if args.report:
        with open(args.report, "w", encoding="utf-8") as handle:
            json.dump(report, handle, indent=2, sort_keys=True)
            handle.write("\n")
    return report


if __name__ == "__main__":
    main()
