# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage Chat spaces and messages state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/chat.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_chat"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def custom_emojis_present(name, body=None, **params):
    """
    Ensure the customEmojis identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``name`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-custom_emojis_present:
          gsuite_chat.custom_emojis_present:
            - name: name-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.custom_emojis_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"customEmojis '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"customEmojis '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_chat.custom_emojis_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"customEmojis '{name}' created"
    return ret


def custom_emojis_absent(name, **params):
    """
    Ensure the customEmojis identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-custom_emojis_absent:
          gsuite_chat.custom_emojis_absent:
            - name: name-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.custom_emojis_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"customEmojis '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"customEmojis '{name}' would be deleted"
        return ret
    __salt__["gsuite_chat.custom_emojis_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"customEmojis '{name}' deleted"
    return ret


def spaces_present(name, body=None, **params):
    """
    Ensure the spaces identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``name`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-spaces_present:
          gsuite_chat.spaces_present:
            - name: name-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"spaces '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["name"] = name
            __salt__["gsuite_chat.spaces_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"spaces '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"spaces '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"spaces '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_chat.spaces_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"spaces '{name}' created"
    return ret


def spaces_absent(name, **params):
    """
    Ensure the spaces identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-spaces_absent:
          gsuite_chat.spaces_absent:
            - name: name-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"spaces '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"spaces '{name}' would be deleted"
        return ret
    __salt__["gsuite_chat.spaces_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"spaces '{name}' deleted"
    return ret


def spaces_members_present(name, body=None, **params):
    """
    Ensure the members identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``name`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-spaces_members_present:
          gsuite_chat.spaces_members_present:
            - name: name-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_members_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"members '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["name"] = name
            __salt__["gsuite_chat.spaces_members_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"members '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"members '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"members '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_chat.spaces_members_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"members '{name}' created"
    return ret


def spaces_members_absent(name, **params):
    """
    Ensure the members identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-spaces_members_absent:
          gsuite_chat.spaces_members_absent:
            - name: name-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_members_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"members '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"members '{name}' would be deleted"
        return ret
    __salt__["gsuite_chat.spaces_members_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"members '{name}' deleted"
    return ret


def spaces_messages_present(name, body=None, **params):
    """
    Ensure the messages identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``name`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-spaces_messages_present:
          gsuite_chat.spaces_messages_present:
            - name: name-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_messages_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"messages '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["name"] = name
            __salt__["gsuite_chat.spaces_messages_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"messages '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"messages '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"messages '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_chat.spaces_messages_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"messages '{name}' created"
    return ret


def spaces_messages_absent(name, **params):
    """
    Ensure the messages identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-spaces_messages_absent:
          gsuite_chat.spaces_messages_absent:
            - name: name-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_chat.spaces_messages_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"messages '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"messages '{name}' would be deleted"
        return ret
    __salt__["gsuite_chat.spaces_messages_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"messages '{name}' deleted"
    return ret
