# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage task lists and tasks state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/tasks.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_tasks"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def tasklists_present(name, body=None, **params):
    """
    Ensure the tasklists identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``tasklist`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-tasklists_present:
          gsuite_tasks.tasklists_present:
            - name: tasklist-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["tasklist"] = name
    existing = None
    try:
        existing = __salt__["gsuite_tasks.tasklists_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"tasklists '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["tasklist"] = name
            __salt__["gsuite_tasks.tasklists_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"tasklists '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"tasklists '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"tasklists '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_tasks.tasklists_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"tasklists '{name}' created"
    return ret


def tasklists_absent(name, **params):
    """
    Ensure the tasklists identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-tasklists_absent:
          gsuite_tasks.tasklists_absent:
            - name: tasklist-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["tasklist"] = name
    existing = None
    try:
        existing = __salt__["gsuite_tasks.tasklists_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"tasklists '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"tasklists '{name}' would be deleted"
        return ret
    __salt__["gsuite_tasks.tasklists_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"tasklists '{name}' deleted"
    return ret


def tasks_present(name, body=None, **params):
    """
    Ensure the tasks identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``task`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-tasks_present:
          gsuite_tasks.tasks_present:
            - name: task-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["task"] = name
    existing = None
    try:
        existing = __salt__["gsuite_tasks.tasks_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"tasks '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["task"] = name
            __salt__["gsuite_tasks.tasks_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"tasks '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"tasks '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"tasks '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_tasks.tasks_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"tasks '{name}' created"
    return ret


def tasks_absent(name, **params):
    """
    Ensure the tasks identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-tasks_absent:
          gsuite_tasks.tasks_absent:
            - name: task-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["task"] = name
    existing = None
    try:
        existing = __salt__["gsuite_tasks.tasks_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"tasks '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"tasks '{name}' would be deleted"
        return ret
    __salt__["gsuite_tasks.tasks_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"tasks '{name}' deleted"
    return ret
