# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage Google Keep notes state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/keep.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_keep"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def notes_present(name, body=None, **params):
    """
    Ensure the notes identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``name`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-notes_present:
          gsuite_keep.notes_present:
            - name: name-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_keep.notes_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"notes '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"notes '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_keep.notes_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"notes '{name}' created"
    return ret


def notes_absent(name, **params):
    """
    Ensure the notes identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-notes_absent:
          gsuite_keep.notes_absent:
            - name: name-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["name"] = name
    existing = None
    try:
        existing = __salt__["gsuite_keep.notes_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"notes '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"notes '{name}' would be deleted"
        return ret
    __salt__["gsuite_keep.notes_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"notes '{name}' deleted"
    return ret
