# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Send, read, and manage email state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/gmail.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_gmail"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def users_drafts_present(name, body=None, **params):
    """
    Ensure the drafts identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``id`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-users_drafts_present:
          gsuite_gmail.users_drafts_present:
            - name: id-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_drafts_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"drafts '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["id"] = name
            __salt__["gsuite_gmail.users_drafts_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"drafts '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"drafts '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"drafts '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_drafts_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"drafts '{name}' created"
    return ret


def users_drafts_absent(name, **params):
    """
    Ensure the drafts identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_drafts_absent:
          gsuite_gmail.users_drafts_absent:
            - name: id-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_drafts_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"drafts '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"drafts '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_drafts_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"drafts '{name}' deleted"
    return ret


def users_labels_present(name, body=None, **params):
    """
    Ensure the labels identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``id`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-users_labels_present:
          gsuite_gmail.users_labels_present:
            - name: id-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_labels_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"labels '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["id"] = name
            __salt__["gsuite_gmail.users_labels_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"labels '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"labels '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"labels '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_labels_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"labels '{name}' created"
    return ret


def users_labels_absent(name, **params):
    """
    Ensure the labels identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_labels_absent:
          gsuite_gmail.users_labels_absent:
            - name: id-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_labels_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"labels '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"labels '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_labels_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"labels '{name}' deleted"
    return ret


def users_messages_present(name, body=None, **params):
    """
    Ensure the messages identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``id`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-users_messages_present:
          gsuite_gmail.users_messages_present:
            - name: id-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_messages_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"messages '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"messages '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_messages_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"messages '{name}' created"
    return ret


def users_messages_absent(name, **params):
    """
    Ensure the messages identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_messages_absent:
          gsuite_gmail.users_messages_absent:
            - name: id-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_messages_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"messages '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"messages '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_messages_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"messages '{name}' deleted"
    return ret


def users_settings_cse_identities_present(name, body=None, **params):
    """
    Ensure the identities identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``cseEmailAddress`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_cse_identities_present:
          gsuite_gmail.users_settings_cse_identities_present:
            - name: cseEmailAddress-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["cseEmailAddress"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_cse_identities_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"identities '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["cseEmailAddress"] = name
            __salt__["gsuite_gmail.users_settings_cse_identities_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"identities '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"identities '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"identities '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_cse_identities_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"identities '{name}' created"
    return ret


def users_settings_cse_identities_absent(name, **params):
    """
    Ensure the identities identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_cse_identities_absent:
          gsuite_gmail.users_settings_cse_identities_absent:
            - name: cseEmailAddress-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["cseEmailAddress"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_cse_identities_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"identities '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"identities '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_cse_identities_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"identities '{name}' deleted"
    return ret


def users_settings_delegates_present(name, body=None, **params):
    """
    Ensure the delegates identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``delegateEmail`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_delegates_present:
          gsuite_gmail.users_settings_delegates_present:
            - name: delegateEmail-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["delegateEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_delegates_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"delegates '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"delegates '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_delegates_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"delegates '{name}' created"
    return ret


def users_settings_delegates_absent(name, **params):
    """
    Ensure the delegates identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_delegates_absent:
          gsuite_gmail.users_settings_delegates_absent:
            - name: delegateEmail-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["delegateEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_delegates_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"delegates '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"delegates '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_delegates_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"delegates '{name}' deleted"
    return ret


def users_settings_filters_present(name, body=None, **params):
    """
    Ensure the filters identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``id`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_filters_present:
          gsuite_gmail.users_settings_filters_present:
            - name: id-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_filters_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"filters '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"filters '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_filters_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"filters '{name}' created"
    return ret


def users_settings_filters_absent(name, **params):
    """
    Ensure the filters identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_filters_absent:
          gsuite_gmail.users_settings_filters_absent:
            - name: id-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_filters_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"filters '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"filters '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_filters_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"filters '{name}' deleted"
    return ret


def users_settings_forwarding_addresses_present(name, body=None, **params):
    """
    Ensure the forwardingAddresses identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``forwardingEmail`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_forwarding_addresses_present:
          gsuite_gmail.users_settings_forwarding_addresses_present:
            - name: forwardingEmail-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["forwardingEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_forwarding_addresses_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"forwardingAddresses '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"forwardingAddresses '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_forwarding_addresses_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"forwardingAddresses '{name}' created"
    return ret


def users_settings_forwarding_addresses_absent(name, **params):
    """
    Ensure the forwardingAddresses identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_forwarding_addresses_absent:
          gsuite_gmail.users_settings_forwarding_addresses_absent:
            - name: forwardingEmail-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["forwardingEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_forwarding_addresses_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"forwardingAddresses '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"forwardingAddresses '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_forwarding_addresses_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"forwardingAddresses '{name}' deleted"
    return ret


def users_settings_send_as_present(name, body=None, **params):
    """
    Ensure the sendAs identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``sendAsEmail`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_send_as_present:
          gsuite_gmail.users_settings_send_as_present:
            - name: sendAsEmail-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["sendAsEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_send_as_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"sendAs '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["sendAsEmail"] = name
            __salt__["gsuite_gmail.users_settings_send_as_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"sendAs '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"sendAs '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"sendAs '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_send_as_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"sendAs '{name}' created"
    return ret


def users_settings_send_as_absent(name, **params):
    """
    Ensure the sendAs identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_send_as_absent:
          gsuite_gmail.users_settings_send_as_absent:
            - name: sendAsEmail-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["sendAsEmail"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_send_as_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"sendAs '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"sendAs '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_send_as_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"sendAs '{name}' deleted"
    return ret


def users_settings_send_as_smime_info_present(name, body=None, **params):
    """
    Ensure the smimeInfo identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``id`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create.

    CLI Example:

    .. code-block:: yaml

        my-users_settings_send_as_smime_info_present:
          gsuite_gmail.users_settings_send_as_smime_info_present:
            - name: id-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_send_as_smime_info_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        ret["result"] = True
        ret["comment"] = f"smimeInfo '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"smimeInfo '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_gmail.users_settings_send_as_smime_info_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"smimeInfo '{name}' created"
    return ret


def users_settings_send_as_smime_info_absent(name, **params):
    """
    Ensure the smimeInfo identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-users_settings_send_as_smime_info_absent:
          gsuite_gmail.users_settings_send_as_smime_info_absent:
            - name: id-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["id"] = name
    existing = None
    try:
        existing = __salt__["gsuite_gmail.users_settings_send_as_smime_info_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"smimeInfo '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"smimeInfo '{name}' would be deleted"
        return ret
    __salt__["gsuite_gmail.users_settings_send_as_smime_info_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"smimeInfo '{name}' deleted"
    return ret
