# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage Google Apps Script projects state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/script.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_script"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def projects_deployments_present(name, body=None, **params):
    """
    Ensure the deployments identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``deploymentId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-projects_deployments_present:
          gsuite_script.projects_deployments_present:
            - name: deploymentId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["deploymentId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_script.projects_deployments_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"deployments '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["deploymentId"] = name
            __salt__["gsuite_script.projects_deployments_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"deployments '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"deployments '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"deployments '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_script.projects_deployments_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"deployments '{name}' created"
    return ret


def projects_deployments_absent(name, **params):
    """
    Ensure the deployments identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-projects_deployments_absent:
          gsuite_script.projects_deployments_absent:
            - name: deploymentId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["deploymentId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_script.projects_deployments_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"deployments '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"deployments '{name}' would be deleted"
        return ret
    __salt__["gsuite_script.projects_deployments_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"deployments '{name}' deleted"
    return ret
