# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage files, folders, and shared drives state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/drive.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_drive"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def comments_present(name, body=None, **params):
    """
    Ensure the comments identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``commentId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-comments_present:
          gsuite_drive.comments_present:
            - name: commentId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["commentId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.comments_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"comments '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["commentId"] = name
            __salt__["gsuite_drive.comments_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"comments '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"comments '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"comments '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.comments_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"comments '{name}' created"
    return ret


def comments_absent(name, **params):
    """
    Ensure the comments identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-comments_absent:
          gsuite_drive.comments_absent:
            - name: commentId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["commentId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.comments_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"comments '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"comments '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.comments_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"comments '{name}' deleted"
    return ret


def drives_present(name, body=None, **params):
    """
    Ensure the drives identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``driveId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-drives_present:
          gsuite_drive.drives_present:
            - name: driveId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["driveId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.drives_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"drives '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["driveId"] = name
            __salt__["gsuite_drive.drives_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"drives '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"drives '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"drives '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.drives_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"drives '{name}' created"
    return ret


def drives_absent(name, **params):
    """
    Ensure the drives identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-drives_absent:
          gsuite_drive.drives_absent:
            - name: driveId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["driveId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.drives_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"drives '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"drives '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.drives_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"drives '{name}' deleted"
    return ret


def files_present(name, body=None, **params):
    """
    Ensure the files identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``fileId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-files_present:
          gsuite_drive.files_present:
            - name: fileId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["fileId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.files_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"files '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["fileId"] = name
            __salt__["gsuite_drive.files_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"files '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"files '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"files '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.files_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"files '{name}' created"
    return ret


def files_absent(name, **params):
    """
    Ensure the files identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-files_absent:
          gsuite_drive.files_absent:
            - name: fileId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["fileId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.files_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"files '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"files '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.files_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"files '{name}' deleted"
    return ret


def permissions_present(name, body=None, **params):
    """
    Ensure the permissions identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``permissionId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-permissions_present:
          gsuite_drive.permissions_present:
            - name: permissionId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["permissionId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.permissions_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"permissions '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["permissionId"] = name
            __salt__["gsuite_drive.permissions_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"permissions '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"permissions '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"permissions '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.permissions_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"permissions '{name}' created"
    return ret


def permissions_absent(name, **params):
    """
    Ensure the permissions identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-permissions_absent:
          gsuite_drive.permissions_absent:
            - name: permissionId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["permissionId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.permissions_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"permissions '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"permissions '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.permissions_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"permissions '{name}' deleted"
    return ret


def replies_present(name, body=None, **params):
    """
    Ensure the replies identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``replyId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-replies_present:
          gsuite_drive.replies_present:
            - name: replyId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["replyId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.replies_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"replies '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["replyId"] = name
            __salt__["gsuite_drive.replies_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"replies '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"replies '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"replies '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.replies_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"replies '{name}' created"
    return ret


def replies_absent(name, **params):
    """
    Ensure the replies identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-replies_absent:
          gsuite_drive.replies_absent:
            - name: replyId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["replyId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.replies_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"replies '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"replies '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.replies_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"replies '{name}' deleted"
    return ret


def teamdrives_present(name, body=None, **params):
    """
    Ensure the teamdrives identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``teamDriveId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-teamdrives_present:
          gsuite_drive.teamdrives_present:
            - name: teamDriveId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["teamDriveId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.teamdrives_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"teamdrives '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["teamDriveId"] = name
            __salt__["gsuite_drive.teamdrives_update"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"teamdrives '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"teamdrives '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"teamdrives '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_drive.teamdrives_create"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"teamdrives '{name}' created"
    return ret


def teamdrives_absent(name, **params):
    """
    Ensure the teamdrives identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-teamdrives_absent:
          gsuite_drive.teamdrives_absent:
            - name: teamDriveId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["teamDriveId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_drive.teamdrives_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"teamdrives '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"teamdrives '{name}' would be deleted"
        return ret
    __salt__["gsuite_drive.teamdrives_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"teamdrives '{name}' deleted"
    return ret
