# DO NOT EDIT - generated by tools/generate_modules.py. Changes will be overwritten.
# pylint: disable=invalid-name,line-too-long,broad-except
"""
Manage calendars and events state module (best-effort, generated).

Auto-generated ``present``/``absent`` states derived from the CRUD method pattern of each
resource. Identity/diffing is shallow; resources that need real idempotency logic should be
hand-tuned in ``saltext/gsuite/states/overrides/calendar.py`` (which the generator prefers
over the auto-generated version).
"""

import logging

from saltext.gsuite import _binary

log = logging.getLogger(__name__)

__virtualname__ = "gsuite_calendar"


def __virtual__():
    if not _binary.is_available(opts=__opts__, pillar=__pillar__):
        return (False, "The 'gws' binary is not available")
    return __virtualname__


def acl_present(name, body=None, **params):
    """
    Ensure the acl identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``ruleId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-acl_present:
          gsuite_calendar.acl_present:
            - name: ruleId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["ruleId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.acl_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"acl '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["ruleId"] = name
            __salt__["gsuite_calendar.acl_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"acl '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"acl '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"acl '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_calendar.acl_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"acl '{name}' created"
    return ret


def acl_absent(name, **params):
    """
    Ensure the acl identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-acl_absent:
          gsuite_calendar.acl_absent:
            - name: ruleId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["ruleId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.acl_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"acl '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"acl '{name}' would be deleted"
        return ret
    __salt__["gsuite_calendar.acl_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"acl '{name}' deleted"
    return ret


def calendar_list_present(name, body=None, **params):
    """
    Ensure the calendarList identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``calendarId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-calendar_list_present:
          gsuite_calendar.calendar_list_present:
            - name: calendarId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["calendarId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.calendar_list_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"calendarList '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["calendarId"] = name
            __salt__["gsuite_calendar.calendar_list_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"calendarList '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"calendarList '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"calendarList '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_calendar.calendar_list_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"calendarList '{name}' created"
    return ret


def calendar_list_absent(name, **params):
    """
    Ensure the calendarList identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-calendar_list_absent:
          gsuite_calendar.calendar_list_absent:
            - name: calendarId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["calendarId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.calendar_list_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"calendarList '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"calendarList '{name}' would be deleted"
        return ret
    __salt__["gsuite_calendar.calendar_list_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"calendarList '{name}' deleted"
    return ret


def calendars_present(name, body=None, **params):
    """
    Ensure the calendars identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``calendarId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-calendars_present:
          gsuite_calendar.calendars_present:
            - name: calendarId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["calendarId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.calendars_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"calendars '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["calendarId"] = name
            __salt__["gsuite_calendar.calendars_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"calendars '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"calendars '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"calendars '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_calendar.calendars_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"calendars '{name}' created"
    return ret


def calendars_absent(name, **params):
    """
    Ensure the calendars identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-calendars_absent:
          gsuite_calendar.calendars_absent:
            - name: calendarId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["calendarId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.calendars_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"calendars '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"calendars '{name}' would be deleted"
        return ret
    __salt__["gsuite_calendar.calendars_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"calendars '{name}' deleted"
    return ret


def events_present(name, body=None, **params):
    """
    Ensure the events identified by ``name`` exists (best-effort).

    ``name`` is the value of the ``eventId`` identifier. Additional required
    parameters (e.g. parent identifiers) and query parameters are passed via ``**params``.
    ``body`` is the resource representation used on create/update.

    CLI Example:

    .. code-block:: yaml

        my-events_present:
          gsuite_calendar.events_present:
            - name: eventId-value
            - body: {}
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["eventId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.events_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if existing:
        if body:
            if test:
                ret["result"] = None
                ret["changes"] = {"updated": name}
                ret["comment"] = f"events '{name}' would be updated"
                return ret
            update_args = dict(params)
            update_args["eventId"] = name
            __salt__["gsuite_calendar.events_patch"](body=body, **update_args)
            ret["result"] = True
            ret["changes"] = {"updated": name}
            ret["comment"] = f"events '{name}' updated"
            return ret
        ret["result"] = True
        ret["comment"] = f"events '{name}' is already present"
        return ret

    if test:
        ret["result"] = None
        ret["changes"] = {"created": name}
        ret["comment"] = f"events '{name}' would be created"
        return ret
    create_args = dict(params)
    __salt__["gsuite_calendar.events_insert"](body=body, **create_args)
    ret["result"] = True
    ret["changes"] = {"created": name}
    ret["comment"] = f"events '{name}' created"
    return ret


def events_absent(name, **params):
    """
    Ensure the events identified by ``name`` is absent (best-effort).

    CLI Example:

    .. code-block:: yaml

        remove-events_absent:
          gsuite_calendar.events_absent:
            - name: eventId-value
    """
    ret = {"name": name, "changes": {}, "result": None, "comment": ""}
    test = __opts__.get("test", False)
    lookup = dict(params)
    lookup["eventId"] = name
    existing = None
    try:
        existing = __salt__["gsuite_calendar.events_get"](**lookup)
    except Exception:  # pylint: disable=broad-except
        existing = None

    if not existing:
        ret["result"] = True
        ret["comment"] = f"events '{name}' is already absent"
        return ret
    if test:
        ret["result"] = None
        ret["changes"] = {"deleted": name}
        ret["comment"] = f"events '{name}' would be deleted"
        return ret
    __salt__["gsuite_calendar.events_delete"](**lookup)
    ret["result"] = True
    ret["changes"] = {"deleted": name}
    ret["comment"] = f"events '{name}' deleted"
    return ret
